### ISSUE TITLE
Sandbox and Future payments - can't complete payment

### ISSUE THREAD

**Issue by Shadowstep33** [paypal/PayPal-REST-API-issues#100]
### General information

* Environment: 
Sandbox
* `PayPal-Debug-ID` values: 
no debug id
* Language, language version, and OS: 
Node v6.9.2, Ionic (Ionic Paypal Native), Paypal REST API v1

### Issue description

I am trying to create a future payment. I am receiving consent from the mobile side and getting a refresh token on the server. I am then getting an access token and sending the client meta data id from mobile to server. My code is as follows:

```       
var refresh_token = params.rt;

        var future_payment_config = {
			'client_metadata_id': params.clientmetadataid, 
			'refresh_token': refresh_token
		};

        //Set up payment details
        var create_payment_json = {
            "intent": "sale",
            "payer": {
                "payment_method": "paypal"
            },
            "transactions": [{
                "amount": {
                    "currency": "USD",
                    "total": "1.00"
                },
                "description": "This is the payment description."
            }],
			"redirect_urls": {
				"return_url": "http://www.paypal.com/return",
				"cancel_url": "http://www.paypal.com/cancel"
			}			 
        };

        //Create future payment
        paypal.payment.create(create_payment_json, future_payment_config, function (error, payment) {
            if (error) {
                console.log(error.response);
                throw error;
            } else {
                console.log("Create Payment Response");
                console.log(payment);
				cb(payment);
            }
        });
```

The response is as follows:

```
{ id: 'PAY-5DA87743FB103235ULFIXQBY',
  intent: 'sale',
  state: 'created',
  payer: { payment_method: 'paypal' },
  transactions:
   [ { amount: [Object],
       description: 'This is the payment description.',
       related_resources: [] } ],
  create_time: '2017-06-26T21:09:27Z',
  links:
   [ { href: 'https://api.sandbox.paypal.com/v1/payments/payment/PAY-5DA87743FB103235ULFIXQBY',
       rel: 'self',
       method: 'GET' },
     { href: 'https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-0WP49782EH205653Y',
       rel: 'approval_url',
       method: 'REDIRECT' },
     { href: 'https://api.sandbox.paypal.com/v1/payments/payment/PAY-5DA87743FB103235ULFIXQBY/execute',
       rel: 'execute',
       method: 'POST' } ],
  httpStatusCode: 201 }
```

My question is, since I approved future payments, what do I do next? The status should say completed right? I've tried:

- remove redirect urls: API throws an error saying they are required
- call the execute (or capture after a transformation) url: API throws PAYMENT_NOT_AUTHORIZED

Is there something obvious I am doing wrong? Do future payments just not work for Sandbox?

**Comment by xiaoleih41** [comment]
What's your sandbox email address?

**Comment by Shadowstep33** [comment]
godavid33@gmail.com

**Comment by xiaoleih41** [comment]
This is a personal account. What's your receiver account? do you have a `debugId` for it. Also, future payment is deprecated on PayPal side. I am not sure if you can get it approved for production anymore. PayPal will soon release a new product on REST platform to replace future payment.

**Comment by Shadowstep33** [comment]
Oh ok, good to know. I'll test with a facilitator account.

As to future payments being deprecated... what would you propose as a solution? Just normal approval flow per transaction? That is kind of cumbersome UX, but if it's the only solution it's what I'll use.

What will apps like Uber do when future payments is deprecated?

**Comment by xiaoleih41** [comment]
Please contact the customer service number listed on your account and request to talk to sales rep. The sales team should be able to help you find the right product for your specific business needs. All the advanced features will need to be vetted by PayPal. Therefore it will be better to start in that way.

**Comment by xiaoleih41** [comment]
Close this issue as suggestion has been given.
