### ISSUE TITLE
Cannot set multiple params in Update vaulted credit card Api

### ISSUE THREAD

**Issue by laudukang** [paypal/PayPal-REST-API-issues#102]
### General information

* Environment: Sandbox 
* `PayPal-Debug-ID` values: 600b1bf32a22c
* Language, language version, and OS:  Java 1.8.0_131-b11 on Windows 10.0.15063

### Issue description

As Billing Agreements API [Update agreement](https://developer.paypal.com/docs/api/payments.billing-agreements#agreement_update) can set multiple update params in `value ` parameter, like follow
```json
[
  {
  "op": "replace",
  "path": "/",
  "value": {
    "description": "Updated description.",
    "start_date": "2017-12-22T09:13:49Z",
    "shipping_address": {
    "line1": "Hotel Blue Diamond",
    "line2": "Church Street",
    "city": "San Jose",
    "state": "CA",
    "postal_code": "95112",
    "country_code": "US"
    }
  }
  }
]
```
Why Vault API [Update vaulted credit card](https://developer.paypal.com/docs/api/vault/#credit-card_update) cannot. Once I set multiple update params(even one param) in `value ` parameter, like 
follows request parameters, I receive failed response.
Request param:
```json
[
  {
    "op": "replace",
    "path": "/",
    "value": {
      "expire_month": 5
    }
  }
]
```
Failed response:
```json
{
    "name": "INVALID_PATCH",
    "debug_id": "600b1bf32a22c",
    "message": "Invalid PATCH request",
    "information_link": "https://developer.paypal.com/docs/api/vault/#errors"
}
```

Only requlet like follow can pass
```json
[
  {
  "op": "replace",
  "path": "/expire_month",
  "value": 5
  }
]
```

Postman request screenshot
![Imgur](http://i.imgur.com/3MR1ujm.png)

**Comment by xiaoleih41** [comment]
You can updated multiple parameters by doing below:
````
[
  {
  "op": "replace",
  "path": "/billing_address/line1",
  "value": "53 N Main St."
     
  },
  
  {
  "op": "replace",
  "path": "/expire_month",
    "value":5
  }
]
````

**Comment by laudukang** [comment]
@xiaoleih41 of course it does, but cannot update multiple parameters in 'value ' parameter, is it a bug?

**Comment by xiaoleih41** [comment]
These two handle json_patch differently. It is not a bug but could use some improvement based on the needs.
