### ISSUE TITLE
Cart items out of order?

### ISSUE THREAD

**Issue by jaesoonis** [paypal/PayPal-REST-API-issues#110]
So then, i've come across an issue on PROD that i've never encountered on the Sandbox environment.

Now i'm not sure if this is an API issue or an issue with PDT or IPN.

I'm currently using C# and the PayPal REST API to create a PayPal payment.

I add in 2 items in the cart thinking that the items sent will be in order as I need to do some processing once the transaction gets completed.

During sandbox testing, every item always came in the exact order as they were added into the Items list which was fine as I needed the first item to be a specific value and the second to be another specific value.

On PROD, i can see that the list is sent in the correct order, but sometimes when the PDT token is received (after confirming the payment ID and getting the transaction ID from it), the item order in the cart flips around which throws off my calculations.

Sending in the list - i expect it to be in this order - 1 then 2,

`items = new List<Item>()
{
	// Item 1.
	new Item()
	{
		name = "1",
		price = "1",
		currency = "USD",
		quantity = "1",
		sku = "1",
		description = "This is Spongebob",
	},
	// Item 2
	new Item()
	{
		name = "2",
		price = "2",
		currency = "USD",
		quantity = "2",
		sku = "2",
		description = "This is Patrick",
	},
}`

And when the PDT gets called, it returns the items in an incorrect order
`item_number1=2
item_number2=1
item_name1=2
item_name2=1
`
And when IPN is called, it returns the items in the correct order
`item_number1=1
item_number2=2
item_name1=1
item_name2=2`

I can't reliably replicate this as it's never happened on the sandbox environment during testing and only happened in PROD which means I have to use real money to test

Are cart item order not guaranteed? Is that done by design?

Please feel free to move this post to the relevant are if this isn't an API issue.

**Comment by xiaoleih41** [comment]
I can see that you have asked this issue under PDT repository. This is not a REST API issue as PDT is only available for website payment standard.  Are you using PayPal shopping cart?  I would suggest you to stick with IPN if that's the case.

**Comment by pp-randy** [comment]
As @xiaoleih41 indicated, PDT is used with Payment Standard product and not with REST PayPal Payments.  

Can you clarify for us a bit more?  Are you getting the order changed in your [Execute Payment response](https://developer.paypal.com/docs/api/payments/#payment_execute_response)?

**Comment by jaesoonis** [comment]
Hi xialeih and randy,

So this was my scenario,

I first started off with a button created from PayPal's website, after doing a bit more research, i wanted to make sure that the transactions that took place were legit and found out that I could use PDT and IPN to ping PayPal servers and verify that the transaction ID was correct.

Also during my testing it showed that PDT was probably much faster than IPN (maybe about a minute or 2 faster than IPN) and since i needed to show data straight after processing, i used PDT to verify along with IPN.

Fast forward a few months, i implemented the APIs to programmatically create payments and noticed that it returns a different URL parameter from what would happen if you used a PayPal button from the website. (previously, the Pay Now button returned a single item, using the API, it returned a cart with items inside it)

(Correct me if im not on the right track) I thought i should also check that the API response is valid so I get the payment code, and extracted the Transaction ID and called the PDT servers to verify that the transaction was legit.

It's while doing the PDT checks that i realised that the cart item order can be jumbled up instead of being in the order that it was sent in.

IPN always returns the cart items in the right order but i'm slightly wary about this in thinking IPN responses could do the same thing at any time.

So then, first off, is what i'm doing necessary? Should i skip the PDT checks if i'm using the API to complete the transaction? Is getting payment information from the API call sufficient to check that the request is legit and valid?

If the API payment check by itself is sufficient, please let me know and I will remove the PDT checking as it would be redundant as i'll be doing double checks.

I guess, even if the above is the case, PDT callbacks still return out of order cart items.


Thanks in advance.

**Comment by pp-randy** [comment]
Since you are now using the API, you should use the API to get the information and no longer use PDT.  If the order is incorrect with the Payment lookup or Execute response then please let us know. 

Before you change a lot of things can you give an overview of the API calls you are using?   I just want to make sure I'm not giving bad advice.  

I also encourage the continued use of IPN either as it can be good if an API call times out or has another issue and a transaction is still created.

**Comment by jaesoonis** [comment]
Ah yes I see,

I guess its an overkill now then as i'm using the API now, the PDT check won't be needed as the API payment ID would be used to verify if the payment is legit or not.

Do you have a private message box where I can contact you on? I can provide you with the samples that I have and you can see if the cart items are being modified or not on PayPal's end.


As for the API, i am using the Payment().Execute() method to call the payments after the user goes through the PayPal page.

**Comment by pp-randy** [comment]
You can Private Message me on Gitter 
https://gitter.im/paypal/PayPal-REST-API-issues

However, since you are using the API and if you are providing the item information from your server and not the client side then it should not be getting tampered with like a Payment Standard button could.
