### ISSUE TITLE
Only verified users can pay

### ISSUE THREAD

**Issue by rjz1371** [paypal/PayPal-REST-API-issues#111]
### General information

* Environment: Sandbox
* Language, language version, and OS: PHP, PHP7, CentOS7

### Issue description

we have paypal merchant for our site and want to specify it just for verified accounts for payment.
is it possible to do this ?
thank you in advance.

**Comment by xiaoleih41** [comment]
There's no setting in PayPal to specify that but you can integrate login with PayPal and include **Account Status** in the [scope](https://developer.paypal.com/docs/integration/direct/identity/attributes/) to get user's verified status before directing them to checkout page.

**Comment by xiaoleih41** [comment]
Close this issue as the answered has been given.
