### ISSUE TITLE
Uncaught Error: No value passed to payment

### ISSUE THREAD

**Issue by koraniar** [paypal/PayPal-REST-API-issues#113]
## General information

* Environment: Sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: ASP.Net Framework 4.5.2 on Windows

## Code
I am configuring my integration with paypal using **Server-side REST**, my code is the same that this https://github.com/paypal/PayPal-NET-SDK/blob/develop/Samples/Source/PaymentWithPayPal.aspx.cs, no diference.

### Payment Model
The Payment model created are this:
`{"intent":"sale","payer":{"payment_method":"paypal"},"transactions":[{"amount":{"currency":"USD","total":"100.00","details":{"subtotal":"75","shipping":"10","tax":"15"}},"description":"Transaction description.","invoice_number":"608961","item_list":{"items":[{"sku":"sku","name":"Item Name","quantity":"5","price":"15","currency":"USD"}]}}],"redirect_urls":{"return_url":"http://localhost:51379/PaymentWithPayPal.aspx?guid=60896","cancel_url":"http://localhost:51379/PaymentWithPayPal.aspx?guid=60896&cancel=true"}}`

**After Payment model is created**
I execute this method => `this.flow.AddNewRequest("Create PayPal payment", payment);` 
And after, I execute this method => `var createdPayment = payment.Create(apiContext);`

### CreatedPayment
And the `createdPayment` variable is equals to:
`{"id":"PAY-8TG15254J2564684XLFQUQHQ","intent":"sale","payer":{"payment_method":"paypal"},"transactions":[{"related_resources":[],"amount":{"currency":"USD","total":"100.00","details":{"subtotal":"75.00","shipping":"10.00","tax":"15.00"}},"description":"Transaction description.","invoice_number":"608961","item_list":{"items":[{"sku":"sku","name":"Item Name","quantity":"5","price":"15.00","currency":"USD"}]}}],"state":"created","create_time":"2017-07-08T21:01:18Z","links":[{"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-8TG15254J2564684XLFQUQHQ","rel":"self","method":"GET"},{"href":"https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-6PE445186E489192C","rel":"approval_url","method":"REDIRECT"},{"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-8TG15254J2564684XLFQUQHQ/execute","rel":"execute","method":"POST"}]}`

## Error
after, the code continues without any error, and when it finish, the paypal window closes and I am getting the next error on javascript:
**Error: No value passed to payment**
`Object {stack: "Error: No value passed to payment↵    at https://w…://www.paypalobjects.com/api/checkout.js:2390:13)", errtype: "[object Error]", timestamp: 1499547706746, windowID: "5148517b93", pageID: "510d0e1522"…}
country:"US"
env:"sandbox"
errtype:"[object Error]"
host:"www.sandbox.paypal.com"
lang:"en"
pageID:"510d0e1522"
path:"/webapps/hermes/button"
referer:"http://localhost:51379"
stack:"Error: No value passed to payment↵    at https://www.paypalobjects.com/api/checkout.js:7986:52↵    at https://www.paypalobjects.com/api/checkout.js:7417:54↵    at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:7441:27)↵    at ZalgoPromise.resolve (https://www.paypalobjects.com/api/checkout.js:7386:22)↵    at https://www.paypalobjects.com/api/checkout.js:7363:48↵    at https://www.paypalobjects.com/api/checkout.js:7417:54↵    at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:7441:27)↵    at ZalgoPromise.resolve (https://www.paypalobjects.com/api/checkout.js:7386:22)↵    at https://www.paypalobjects.com/api/checkout.js:7440:42↵    at ZalgoPromise.dispatch (https://www.paypalobjects.com/api/checkout.js:7441:27)↵    at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.js:2471:118)↵    at receiveMessage (https://www.paypalobjects.com/api/checkout.js:2369:77)↵    at messageListener (https://www.paypalobjects.com/api/checkout.js:2390:13)"
timestamp
:
1499547706746
uid
:
"8cb15883be"
ver
:
"4.0.89"
windowID
:
"5148517b93"
__proto__
:
Object`

**Comment by pp-randy** [comment]
What does the JavaScript code for PayPal CheckoutJS you are using look like?

**Comment by koraniar** [comment]
This is my js
  
```
  paypal.Button.render({
            env: 'sandbox',
            commit: true,
            payment: function () {

                // Set up a url on your server to create the payment
                var CREATE_URL = "@Url.Action("MakePaymentWithPayPal", "Payment")";

                // Make a call to your server to set up the payment
                return paypal.request.post(CREATE_URL)
                    .then(function (res) {
                        console.log("res");
                        console.log(res);//this is always empty
                        return res.paymentID;
                    }).catch(function (err) {
                        reject("err");
                        reject(err);
                    });
            },
            onAuthorize: function (data, actions) {

                // Set up a url on your server to execute the payment
                var EXECUTE_URL = '/demo/checkout/api/paypal/payment/execute/';

                // Set up the data you need to pass to your server
                var data = {
                    paymentID: data.paymentID,
                    payerID: data.payerID
                };

                // Make a call to your server to execute the payment
                return paypal.request.post(EXECUTE_URL, data)
                    .then(function (res) {
                        window.alert('Payment Complete!');
                        console.log(res);
                    });
            }
        }, '#paypal-button');`
```

**Comment by pp-randy** [comment]
When you post to your `CREATE_URL` is it responding with Content-Type for JSON?  Does it also have a JSON formatted body? 

If you go to your `CREATE_URL` in the browser it should have a header of
`Content-Type: application/json`
Your body should look like `{"paymentID": "PAY-#############"}` 

You can check the headers using your browsers developer tools and the network tab.

**Comment by koraniar** [comment]
No, I was not returning anything because at the sample the method type is Void, but it has resolved here https://stackoverflow.com/questions/45002342/uncaught-error-no-value-passed-to-payment

Thanks to all
