### ISSUE TITLE
Payments Execute using MYR - Items with negative price cause 500

### ISSUE THREAD

**Issue by pp-randy** [paypal/PayPal-REST-API-issues#116]
*Migrated issue from https://github.com/paypal/PayPal-PHP-SDK/issues/888*

> Known workarounds or alternative products: Occurs only for certain MYR amount totals, try a lower or higher amount. 

> For internal bookkeeping: PPPLMER-35001

Payments in MYR currency with negative line items can return 500 errors during execute.

Example: 
```
"transactions": [{
  "amount": {
	"total": 200,
	"currency": "MYR",
	"details": {
	  "subtotal": 180,
	  "shipping": 20
	}
  },
  "description": "Testing",
  "item_list": {
	"items": [{
		"currency": "MYR",
		"price": 200,
		"quantity": 1,
		"name": "Test Item"
	  }, {
		"currency": "MYR",
		"price": -20,
		"quantity": 1,
		"name": "Discount"
	  }
	]
  }
}
]
```

**Comment by shoguniphicus** [comment]
Well, if anyone like me stumbled across this issue in the future, please know that this is not a bug/defect, but an intended rule to throw timeout error if the amount is MYR200.

Here are the official reply from the Paypal support.
I suppose this issue can be closed now.
<img width="1392" alt="screenshot 2017-07-18 18 17 14" src="https://user-images.githubusercontent.com/5608586/28312373-7d633230-6be5-11e7-8af5-e75386e0ba2f.png">

**Comment by pp-randy** [comment]
Thank you for the update, it looks like the simulator for this currency indeed does handle the amount this way.
