### ISSUE TITLE
Specify Default Status for Billing Plan List [dev-docs]

### ISSUE THREAD

**Issue by livingcodes** [paypal/PayPal-REST-API-issues#117]
> Known workarounds or alternative products: None

> For internal bookkeeping: DEVDOC-733

### Issue description

In the [API Reference for listing /billing-plans](https://developer.paypal.com/docs/api/payments.billing-plans#plan_list) will you please specify the "status" parameter default?

Example of added text: The default is "CREATED".

The default appears to be "CREATED" when it is not sent in the request. This filters all other plans (such as "ACTIVE") and that was not intuitive to me. I expected the plans to not be filtered by status. There's already another open issue for changing the functionality (which I'm less concerned about), instead this issue is only to get the docs updated.

The "page" and "page_size" parameters have their defaults specified already which is good.

Might as well specify the default for "total_required" parameter while you are at it (default appears to be "no").

**Comment by pp-randy** [comment]
Thank you for the suggestion, I have added internal tracking information to your comment.

**Comment by xiaoleih41** [comment]
Close as the issue has been solved.
