### ISSUE TITLE
REST API "payee_metadata_info" object doesn't actually exist

### ISSUE THREAD

**Issue by dsyno** [paypal/PayPal-REST-API-issues#118]
### General information
The REST API documentation details a "payee_metadata_info" object, however, that object doesn't seem to exist in the actual API.

* Environment: Production (probably Sandbox as well)
* `PayPal-Debug-ID` values: Not applicable
* Language, language version, and OS: PayPal .NET SDK 1.8.0

### Issue description
The "payee_metadata_info" is detailed in the documentation ( https://developer.paypal.com/docs/api/payments/#definition-payee_metadata_info ) however, that object does not actually seem to exist in the API.

We have downloaded and installed the PayPal .NET SDK (version 1.8.0) into Visual Studio. So far, every object in the API documentation is available in the API, except for the "payee_metadata_info" object. 

I also downloaded the source code for the API, and nowhere in that source could I find any mention of the "payee_metadata_info" object.

Though the API documentation contains the "payee_metadata_info" object, that object just simply does not seem to exist in the API.

Am I missing something? How do we use the "payee_metadata_info" object?

**Comment by pp-randy** [comment]
I tested the `payee_metadata_info` and it is available under `payee` object.  I will look over the SDK most likely that is where the object is missing.

**Comment by pp-randy** [comment]
Created a new issue in the SDK https://github.com/paypal/PayPal-NET-SDK/issues/277 as this is an SDK issue.
