### ISSUE TITLE
Billing Agreement Status Explanation

### ISSUE THREAD

**Issue by alexd2580** [paypal/PayPal-REST-API-issues#119]
>For internal bookkeeping: DEVDOC-744

Need definition of each state of [agreement](https://developer.paypal.com/docs/api/payments.billing-agreements#agreement_create_response) object  state and of each status of [transaction_agreement]( https://developer.paypal.com/docs/api/payments.billing-agreements#agreement_transactions_response) object for billing agreement API

While working with the Python PayPal SDK i found that there is not a lot of documentation for whether a Buyer *is* in a valid subscription at the moment or not. For now i've solved it by checking whether the status of the `BillingAgreement` is one of the following => `[CREATED, ACTIVE, REACTIVATED]`. The `agreement_transaction_list` uses the same states as the billing agreement current sandbox api.

The docs do not explain what the status means, there is only a listing of the states.
In the context of an infinitely running subscription what do these states mean for a `BillingAgreement`, and also what do they mean for elements of the transaction list.
Are the docs for this located elsewhere than the API documentation?

**Comment by xiaoleih41** [comment]
It looks like state and status are same, the definition of status is at [here](https://developer.paypal.com/docs/api/payments.billing-agreements#definition-agreement_transaction). **status** is under [**agreement_transaction** object](https://developer.paypal.com/docs/api/payments.billing-agreements#definition-agreement_transaction) while **state** is under [**agreement** obeject](https://developer.paypal.com/docs/api/payments.billing-agreements#agreement_transactions_response).

**Comment by alexd2580** [comment]
Thank you for your reply!

Well thats the point - the docs do not explain what these values mean, there's just a listing.
In the screenshot, is this what you're referring to in your answer?
![screenshot_2017-07-21_13-22-35](https://user-images.githubusercontent.com/15080856/28461654-e7a80f92-6e17-11e7-993f-5b024a5175a2.png)
There is no explanation as to what it means that a billinb aggr is `Completed`, or `Active`, or `Reactivated`, ... . Same holds for the transaction list.

Is there a link to a more detailed description which i was unable to find?

**Comment by xiaoleih41** [comment]
I could not find more detail description on these status/state. I have sent a request to product for more info. I will update this issue once I get more info on this.

**Comment by xiaoleih41** [comment]
Close as this issue has been resolved.
