### ISSUE TITLE
Update billing plan succeeds but response is causing JSON parse errors

### ISSUE THREAD

**Issue by pp-randy** [paypal/PayPal-REST-API-issues#120]
*Migrated issue from https://github.com/paypal/PayPal-node-SDK/issues/284*

> Known workarounds or alternative products: NA

> For internal bookkeeping: PPPLPAYPT-24946

Update billing plan on production is returning a response that is causing JSON parse errors.  This behavior is not seen in sandbox.

**Comment by pp-randy** [comment]
@fernandocalsa if you know this could help with the investigation into the issue. Did the behavior of the production response change 5 days ago, or is that when you first started with production?

**Comment by jeprojects** [comment]
@pp-randy I am getting this error also.

`
{ [Error: Invalid JSON Response Received. If the response received is empty, please checkthe httpStatusCode attribute of error message for 401 or 403. It is possible that the client credentialsare invalid for the environment you are using, be it live or sandbox.]
  error: { name: 'Invalid JSON Response Received, JSON Parse Error.' },
  response: '',
  httpStatusCode: 200 }
`

**Comment by pikoloshanti** [comment]
@pp-randy  we started getting this error yesterday evening on production.

**Comment by fernandocalsa** [comment]
@pp-randy we noticed the error on 19th of July. We started on production at the beginning of the month and it was working fine. On 19th we started to receive the same error than @jeprojects to fix it in production while PayPal find a solution we changed this code on  [lib/client.js:L114](https://github.com/paypal/PayPal-node-SDK/blob/master/lib/client.js#L114)

`if (typeof res.headers['content-type'] === "string" &&
                    res.headers['content-type'].match(/^application\/json(?:;.*)?$/) !== null && response !== "") {
                    response = JSON.parse(response);
                }`

We added the last condition `response !== ""` if the response is empty we don't parse the response to don't have the error. I hope this will help you. If you are using another SDK it will be a similar fix.

**Comment by jeprojects** [comment]
@fernandocalsa Thanks for a temp fix. Hopefully Paypal can get it fixed quickly because I can imaging it will be effecting everybody creating new billing agreements.

**Comment by basex** [comment]
Same problem here, using the Ruby SDK. Any temporary fix?

**Comment by pikoloshanti** [comment]
Do you guys have ETA on the fix? Our business is really pissed.

**Comment by pp-randy** [comment]
Is this limited to the patch for billing plans?  If other API functions are causing this as well, please let me know so I can include them in our internal ticket.

**Comment by basex** [comment]
We aren't able to create new billing plans, since we have to patch the plan to change the status to Active.

**Comment by fernandocalsa** [comment]
@basex what SDK are you using?

**Comment by pp-randy** [comment]
@basex https://github.com/paypal/PayPal-Ruby-SDK/pull/303 should help

**Comment by basex** [comment]
@fernandocalsa @pp-randy https://github.com/paypal/PayPal-Ruby-SDK/pull/303 solved the problem. Thanks a lot.

**Comment by WayneUong** [comment]
@pp-randy Is there a fix for the node library yet?

**Comment by pp-randy** [comment]
@WayneUong the Node fix is here https://github.com/paypal/PayPal-node-SDK/pull/286

**Comment by WayneUong** [comment]
@pp-randy Thank you very much. Are you planning a new version release soon or should I install directly from the github repo?

**Comment by pikoloshanti** [comment]
Here's temp fix we did:

`        #TODO: this is a temporary hack which should be deleted when PayPal fixes its issue
        PayPal::SDK::Core::API::REST.class_eval do
          def format_response(payload)
            response = payload[:response]
            payload[:data] =
              if response.body && response.body.strip == ''
                {}
              elsif response.code >= '200' and response.code <= '299'
                response.body && response.content_type == 'application/json' ? MultiJson.load(response.body) : {}
              elsif response.content_type == 'application/json'
                { 'error' => flat_hash(MultiJson.load(response.body)) }
              else
                { 'error' => { 'name' => response.code, 'message' => response.message,
                               'developer_msg' => response } }
              end
            payload
          end
        end`

**Comment by pp-randy** [comment]
The issue should be resolve on the API side at this point.  Please let me know if you are still experiencing an issue.
