### ISSUE TITLE
PayPal Plus PATCH does not update the address

### ISSUE THREAD

**Issue by lojzatran** [paypal/PayPal-REST-API-issues#124]
>For internal bookkeeping: PPPLMER-36878

In sandbox environment, Address added by PATCH after the payment creation doesn't get to added successfully in a consistent basis.  

### General information

* Environment: sandbox
* `PayPal-Debug-ID` values: f02130d18dedb
* Language, language version, and OS: Java(TM) SE Runtime Environment (build 1.8.0_131-b11) Mac OS Sierra 10.12.5

### Issue description

I’m currently developing the payment process and I got a problem with one of my integration tests. In the test, I create a payment, patch the shipping address and then look up this payment and check that the shipping address is correctly applied. However, this test fails from time to time. The problem is patch payment or look up payment sometimes does not return the payment with address.

Example:

First I updated the created payment with this address:

```curl
curl --request PATCH -v 'https://api.sandbox.paypal.com/v1/payments/payment/PAY-12R90485UR711001QQGFRVUI' \
-H "Authorization: Bearer A21AAFDtnVjkfjybxtQdAE43Rt3CNocku4KRRI093yY2_VXFhlASpbU90MBIs6Jdvbsa7ps61N_AEjRtXZ-yzMnPfu3BMiC6g" \
-H "User-Agent: PayPalSDK/  (v=1.8.0_131; vendor=Oracle Corporation; bit=64; os=Mac_OS_X 10.12.5)" \
-H "PayPal-Request-Id: 0bef0f20-5efc-45f2-87c9-84d6da9ff6f6" \
-H "Content-Type: application/json" \
-d '[
  {
    "op": "add",
    "path": "/transactions/0/item_list/shipping_address",
    "value": {
      "recipient_name": "Mustermann",
      "phone": "+491234567890",
      "line1": "Kurfürstendamm 100",
      "city": "Berlin",
      "country_code": "DE",
      "postal_code": "10709"
    }
  }
]'
```
I received response 200 OK with the payment in the response body, but this payment does NOT contain the address I've just patched.

Sometimes the PATCH step works and the response does return payment with shipping address. Then I look up for this payment using the following command:
```curl
curl -v 'https://api.sandbox.paypal.com/v1/payments/payment/PAY-12R90485UR711001QQGFRVUI' \
-H "Authorization: Bearer A21AAFDtnVjkfjybxtQdAE43Rt3CNocku4KRRI093yY2_VXFhlASpbU90MBIs6Jdvbsa7ps61N_AEjRtXZ-yzMnPfu3BMiC6g" \
-H "User-Agent: PayPalSDK/  (v=1.8.0_131; vendor=Oracle Corporation; bit=64; os=Mac_OS_X 10.12.5)" \
-H "PayPal-Request-Id: 4f2a5160-81ad-45b1-8224-35155c799b98" \
-H "Content-Type: application/json" \
```

Same problem with the response from look up. Sometimes I receive payment with shipping address, sometimes I don't.

**Comment by pp-randy** [comment]
Are you patching the payment before the payment is executed?

You should not be able to patch a payment afterwards according to the documentation https://developer.paypal.com/docs/api/payments/#payment_update
> Partially updates a payment, by ID. You can update the amount, shipping address, invoice ID, and custom data. You cannot update a payment after the payment executes.

**Comment by lojzatran** [comment]
Yes, I patch before payment. Otherwise I would get error code and not 200 OK, right? Anyway, sometimes when I patch again after first failure, it works.

**Comment by xiaoleih41** [comment]
This appears to be a known issue that PayPal is looking into. However it only affects sandbox environment. The live environment will not reproduce this error and is stable.

**Comment by lojzatran** [comment]
Will it be fixed anytime soon? We want to write integration tests and it would be good to have a stable sandbox environment.

**Comment by xiaoleih41** [comment]
We have reported the issue but we don't have the estimated timeline on this.

**Comment by xiaoleih41** [comment]
Can you try to recreate the issue again? We need the `debugId` associated with the API call.  Please help provide for us to troubleshoot the issue.

**Comment by lojzatran** [comment]
Hi @xiaoleih41 I gave above in General information the debugId already, is it enough?

**Comment by xiaoleih41** [comment]
Got it. We have submitted the issue and waiting for the fix at this time.

**Comment by andrii-kovalenko-ct** [comment]
Pls, verify the same problem in `GET https://api.sandbox.paypal.com/v1/payments/payment/`:
i created `installment` payment with `"external_selected_funding_instrument_type":"CREDIT"`, but when i fetch it by id:
```bash 
curl -v 'https://api.sandbox.paypal.com/v1/payments/payment/PAY-7FL44980EU589283SLG36YII' \
-H "Authorization: Bearer XXXXX" \
-H "User-Agent: PayPalSDK/  (v=1.8.0_121; vendor=Oracle Corporation; bit=64; os=Mac_OS_X 10.11.6)" \
-H "PayPal-Request-Id: c864ef1b-2a0e-4513-94dc-7af7f787c368" \
-H "Content-Type: application/json"
```

from time to time i receive payment including `payer_info` (correct), some times - without (incorrect).

**Paypal-Debug-Id=[6882e53a4b3b6]**

**Comment by engharb** [comment]
Hi,
I have the same problem in testing phase (using sandbox mode). is it fixed or not yet?
We need to write an integration test to verify the success of payment process and updates before payment executing.

Regards,

**Comment by xiaoleih41** [comment]
This issue should have been fixed. Please provide `debugId` and describe your flow if it's still an issue to you.

**Comment by SmitaHasole** [comment]
I am facing same issue with PayPal Patch API **NOT** PayPal Plus PATCH
https://developer.paypal.com/docs/api/payments/v1/#payment_update
We are using V1 Rest API's and testing it on sandbox account.
this the request 
  const updatePaymentReq = {
        "strictSSL": false,
        "url": "https://api.sandbox.paypal.com/v1/payments/payment/"+req.params.payment_id,
        "method": "PATCH",
        "headers": {
           
            "Content-Type": "application/json",
            "Authorization": req.headers.authorization
        },
      
            "patch_request": [
                {
                  "op": "replace",
                  "path": "/transactions/0/amount",
                  "value":{"total":"27",
                  "currency":"USD",
                  "details":{"subtotal":"20","tax":"1.00","shipping":"6.00",
                  "handling_fee":"0.00","insurance":"0.00","shipping_discount":"0.00"}
                }
                },
                {
                  "op": "add",
                  "path": "/transactions/0/item_list/shipping_address",
                  "value": {"line1":"4thFloor","line2":"unit#33","city":"San Jose",
                  "country_code":"US","postal_code":"95133","state":"CA"}
                }
              ]
            ,
        "json": true
    };

It returns 204 status code. But its not updating the created payment entry also
