### ISSUE TITLE
DoReferenceTransaction returns error code 11451 for Billing Agreement ceated using PayPal REST API SDK(.Net)

### ISSUE THREAD

**Issue by vishnudassoman** [paypal/PayPal-REST-API-issues#126]
### General information

* Environment: Production
* `PayPal-Debug-ID` values: c1d654eef106a, 531c2caa2f06f
* Language, language version, and OS: .Net, Windows

### Issue description
We have successfully created a recurring payment plan through PayPal REST API in the live PayPal business account on 8/8/2017 and the Billing Agreement Id was used for creating the Subscription in Recurly(www.recurly.com) which is a third party subscription management system. 

The recurring payment plan created in PayPal has got 1 day trial and the trial period ended on 8/9/2017 at  12:18 PM UTC. After this, the buyer account has got charged $1.00 which is the recurring charge for the plan. And this amount got credited to our PayPal business account too.

However, when the third party subscription management system(Recurly) tries to contact PayPal using the Billing Agreement Id, it is getting the following error message from the PayPal
payment gateway. This could be an NVP/SOAP API call that attempts a DoReferenceTransaction.

Gateway Message : Billing Agreement Id or transaction Id is not valid
Gateway Error Code : 11451 

The billing agreement id for which we are getting this error message is: I-MLF7PS70TTEU

If we look at the Recurring Billing Plan in our PayPal business account, we can see this Billing Agreement as Active.

The API call from Recurly is made using the API login name and password associated with our PayPal business account. From the error code (11452) returned by PayPal, I assume that it is an NVP/SOAP API call happening from Recurly to PayPal. 

From this link - https://developer.paypal.com/docs/classic/api/errors/?mark=11451 – I think the API call is the one mentioned below. 

DoReferenceTransaction 

Could you please check the transaction details which has happened from Recurly and let us know what is going wrong with this transaction related to the Billing Agreement Id I-MLF7PS70TTEU ?

Is this Billing Agreement with id - I-MLF7PS70TTEU, a valid one for an operation like DoReferenceTransaction which I have mentioned above? 
If not, what
could be the reason ? 
Is there any other way to achieve the same ?

**Comment by vishnudassoman** [comment]
We would like to talk to one of your SDK developers on this regard, since this is having an impact on our production go live plans. We have reached out to the tech support guys and they asked us to create an issue here in git. 
Please let us know whether some one from the technical team can join a conference call to discuss the same.

**Comment by pp-randy** [comment]
I apologize for the confusion.  The Billing Agreements in the REST API are Recurring Payments in the Classic API.  You can Create the Billing Agreement you need with the Classic API https://developer.paypal.com/docs/classic/api/merchant/CreateBillingAgreement_API_Operation_NVP/.   

What was your technical support ticket number?

**Comment by xiaoleih41** [comment]
REST API billing agreement ID doesn't work with NVP/SOAP APIs. You will need to use REST API calls for that billing agreement ID. These are two different environments that cannot be interchanged. Please refer to [here](https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECReferenceTxns/) on how to create reference transaction with NVP/SOAP APIs.

**Comment by jeffpatrick** [comment]
Hi, I'm working with Vishnu on this issue and wanted to provide the infrormation requested.  Here it is:

Our incident # with Paypal Support (Haikal) is 170809-000186.

**Comment by pp-randy** [comment]
Hi Jeff,

Thank you for the information and again I apologize for the confusion.   

To be clear and add to my previous comment the REST Billing Agreements starting in `I-` are more like subscriptions and are called Recurring Payments in the Classic API. These will be billed in a batch process by PayPal and do not support Merchant Initiated or On Demand billing via reference transactions. 

If you want to call `DoReferenceTransaction` you need to use https://developer.paypal.com/docs/classic/api/merchant/CreateBillingAgreement_API_Operation_NVP/.  These will start with `BA-`.   Here is more on the Overall process to use Express Checkout to create the Classic Billing Agreements https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECReferenceTxns/. 

Unfortunately, the REST counter-part has not been launched publicly at this point.

**Comment by vishnudassoman** [comment]
Thanks Randy for the detailed response. I would like to get few more things clarified. For integrating the classic API, can I use PayPal Merchant SDK (https://github.com/paypal/merchant-sdk-dotnet)?
Does Merchant SDK supports the classic Billing Agreements ?
Also, the second link (https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECReferenceTxns/) is marked as deprecated. Hope, PayPal is not going to stop the support in near future.

**Comment by pp-randy** [comment]
The Classic API where it shows SOAP/NVP is marked deprecated, but you are OK to integrate it as REST does not provide you with a suitable workaround at this time.  Yes, that is the correct SDK for the Classic Billing Agreements.  You will use Express Checkout and follow the integration guide to ensure your SetExpressCheckout call is set to create a billing agreement.
![image](https://user-images.githubusercontent.com/6819909/29321981-ad311c80-81a1-11e7-9f5c-d77de5e5a2be.png)

**Comment by vishnudassoman** [comment]
Thanks Randy.

**Comment by pp-randy** [comment]
You're welcome. Please let me know if you need further assistance.
