### ISSUE TITLE
Payments - Clarify state parameter in address

### ISSUE THREAD

**Issue by JosephDev** [paypal/PayPal-REST-API-issues#127]
> For internal bookkeeping: DEVDOC-835

In PayPal [documentation](https://developer.paypal.com/docs/api/payments/#definition-address) `state` in address is described 
```
state string
The two-letter code for US states or the equivalent for other countries. Maximum length is 100 characters.
```
However, We don't know what countries should pass 'state' as requirement.

I have an error below with Canada without state
`u'VALIDATION_ERROR', u'details': [{u'field': u'state', u'issue': u'Required field missing'}]}`

Please mention which countries should pass `state`

**Comment by pp-randy** [comment]
I will follow up on the documentation, it is documented well for the NVP / SOAP API.

https://developer.paypal.com/docs/classic/api/merchant/SetExpressCheckout_API_Operation_NVP/
![image](https://user-images.githubusercontent.com/6819909/29466051-13bb412c-8401-11e7-81c0-afa7eafb1071.png)

**Comment by JosephDev** [comment]
@pp-randy according to customers payment history, I think PayPal doesn't check state if customer payout with mobile. Some orders payed without state. Please check this case too.

**Comment by pp-randy** [comment]
You have example transaction ids?

**Comment by JosephDev** [comment]
@pp-randy in here public board? is that safe?

**Comment by pp-randy** [comment]
You got a sandbox example?

**Comment by pp-randy** [comment]
PayPal Debug IDs would be OK.  Did you get this error in the Payment Create? Because that would occur prior to being a mobile checkout or not.

**Comment by JosephDev** [comment]
We don't know exactly, but we pass `state` as requirement only for US. 
So, some customers complained that they cannot placed order which shipping address is Canada.
I reviewed our transaction history and find some orders has beed placed successfully without `state` even the shipping address is Canada.

Now I am testing can collect more test cases in Sandbox. 
I will report if I will figure out what happen with `state`

**Comment by xiaoleih41** [comment]
Close this issue due to inactivity. Please resubmit when the issue persists.
