### ISSUE TITLE
Getting null PayPal Debug ID in Sandbox API Call History

### ISSUE THREAD

**Issue by emanu11** [paypal/PayPal-REST-API-issues#129]
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description
1. the debug Id is not displayed in the Api Call History.( see photo 1)
2. when a payout is created, the items are null(see photo 2)
Photo 1
![b086d1f8-2f59-11e7-8d4b-268dceb550fb](https://user-images.githubusercontent.com/17272446/29603565-4fd5ff04-87ed-11e7-9165-a6986ba2fc94.png)
Photo 2
![capture2](https://user-images.githubusercontent.com/17272446/29603566-4fd781d0-87ed-11e7-8b5e-79d6c7076a93.PNG)

**Comment by emanu11** [comment]
The problem is that I use a Single Payout on sync_mode='false' and I want to check the payout status after the async call is made

**Comment by pp-randy** [comment]
My understanding is the debug does not populate for successful calls.  

Are your payouts showing at all though?

**Comment by emanu11** [comment]
Yes, the payouts are shown in the list, but without the debugId

**Comment by emanu11** [comment]
Is there a way to use the Create in async mode and check the status of transaction immediately?

**Comment by pp-randy** [comment]
You can use the `payout_batch_id` to [show the batch payout details](https://developer.paypal.com/docs/api/payments.payouts-batch#payouts_get); however, you should also look into using webhooks for notifications on payouts.

**Comment by xiaoleih41** [comment]
Close this ticket as the answer has been given.
