### ISSUE TITLE
Paypal Rest API issues with amount format when going to live 

### ISSUE THREAD

**Issue by nagro** [paypal/PayPal-REST-API-issues#133]
### General information

* Environment: Production
* `PayPal-Debug-ID` values: dc60e0012af71
* Language, language version, and OS: PHP 7 on Windows7

### Issue description

I'm writing a custom paypal gateway for woocommerce using paypal rest api. I've almost done, everything is working fine while testing with sandbox account. But after switching to Live, i got a lot of errors "Currency amount must be non-negative number" This is what i got:

PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 400 when accessing https://api.paypal.com/v1/payments/payment. {"name":"VALIDATION_ERROR","details":[{"field":"transactions[0].item_list.items[0].price","issue":"Currency amount must be non-negative number, contain exactly 2 decimal places separated by '.' (JPY contains 0 decimal places), optional thousands separator ',', limited to 7 digits before the decimal point and currency which is a valid ISO Currency Code"},{"field":"transactions[0].amount.details.subtotal","issue":"Currency amount must be non-negative number, contain exactly 2 decimal places separated by '.' (JPY contains 0 decimal places), optional thousands separator ',', limited to 7 digits before the decimal point and currency which is a valid ISO Currency Code"},{"field":"transactions[0].amount.total","issue":"Currency amount must be non-negative number, contain exactly 2 decimal places separated by '.' (JPY contains 0 decimal places), optional thousands separator ',', limited to 7 digits before the decimal point and currency which is a valid ISO Currency Code"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"dc60e0012af71"}

For each issue i have tried to cast to float, double, even using number format but the problem still persist. Using the same code it was working on sandbox, i've done some test. But the problem occur using Live.
Is there something i should do ?

**Comment by xiaoleih41** [comment]
The currency I saw there was XAF. I don't think PayPal support  this currency.

**Comment by nagro** [comment]
Thanks for the reply. I'll try other currencies. So it isn't due to number format but to the currency?

**Comment by xiaoleih41** [comment]
Yes, that's what I see from here.

**Comment by nagro** [comment]
I tried with EUR and the problem persist

**Comment by xiaoleih41** [comment]
can you give me the debug ID? Do you have EUR open balance on your account?

**Comment by nagro** [comment]
9a1b96644681a
15c50639e4386
a4fe2619e3a5b

**Comment by xiaoleih41** [comment]
The first EUR one is a different error. The subtotal, shipping and tax are not added up correctly. The rest two were in some other currency that PayPal doesn't support. As it's live production and we are on an open forum, I cannot disclose specific information. It will be great if you open a ticket at www.paypal-techsupport.com. The engineer there can discuss more specifics with you.

**Comment by nagro** [comment]
ok thanks
