### ISSUE TITLE
The invoicing api for cancel and refund returns a 404 Not Found if you post with no data.

### ISSUE THREAD

**Issue by trainerbill** [paypal/PayPal-REST-API-issues#134]
> For internal tracking: PPPLMER-38877

404 instead of 400 error message for [invoicing API](https://developer.paypal.com/docs/api/invoicing/) when trying to cancel or refund if no data is posted.

### General information
Shouldn't this be a 400 Bad request?  Took me hours to figure this out so I am sure someone else will trip on it.  Not sure if that is how other apis work or not but I would expect that response to be a 400 since the endpoint and invoice id in the URL were correct.

* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by xiaoleih41** [comment]
Do you have a debug ID associated with this?

**Comment by pp-randy** [comment]
Closing due to internal discussion.
