### ISSUE TITLE
Webhook simulator payment.sale.refunded looks wrong

### ISSUE THREAD

**Issue by jleclanche** [paypal/PayPal-REST-API-issues#136]
I just received a webhook of type `payment.sale.refunded` which looks nothing like the one in the webhook simulator. The simulator sends an event_type of `sale`, whereas live sends an event_type `refund`.

**Comment by xiaoleih41** [comment]
I am not sure as I checked simulator for `payment.sale.refund` webhook event, it shows. ````"resource_type": "sale",
"event_type": "PAYMENT.SALE.REFUNDED",````

**Comment by xiaoleih41** [comment]
Close this issue as we cannot reproduce the error.
