### ISSUE TITLE
Missing payer_id field from user_info object for Identity API

### ISSUE THREAD

**Issue by veelenga** [paypal/PayPal-REST-API-issues#138]
### General information

* Environment: sandbox/live
* Language, language version, and OS: [paypal-ruby-sdk 1.6.0](https://github.com/paypal/PayPal-Ruby-SDK), OS X

### Issue description

We want to ensure our users don't use multiple PayPal accounts to get payments. Email address can't guarantee this because the user can add multiple email addresses in his Paypal profile.

We are thinking about identification via [Identity API](https://developer.paypal.com/docs/api/identity/). According to this official API, response to `/v1/identity/openidconnect/userinfo` should contain `payer_id` attribute, which according to this [SO thread](https://stackoverflow.com/questions/7121574/what-is-a-paypal-payer-id) uniquely identifies PayPal  account.

The problem is that response does not have `payer_id` attribute:

```
{
 account_creation_date: "2016-01-05",
 account_type: "BUSINESS",
 address: {
   country: "US",
   locality: "San Jose",
   postal_code: "95131",
   region: "CA",
   street_address: "1 Main St"
 },
 age_range: "31-35",
 birthday: "1982-08-02",
 email: "test-facilitator@gmail.com",
 email_verified: true,
 family_name: "facilitator",
 given_name: "test",
 language: "en_US",
 locale: "en_US",
 name: "test facilitator",
 phone_number: "4089354148",
 user_id: "https://www.paypal.com/webapps/auth/identity/user/XXXXXX",
 verified: true,
 verified_account: true,
 zoneinfo: "America/Los_Angeles"
}
```

1. Why does API not respond with `payer_id`? Should it?
2. Can we obtain `payer_id` without doing a payment?
3. Can we use other attributes to identify the PayPal account (maybe `user_id`)?

**Comment by xiaoleih41** [comment]
I am looking into this but most likely the `payer_id` field was removed afterwards. However you should be able to create a payment and acquire the customer's approval to get the `payer_id`. You should be able to compare and confirm the `payer_id` before actually execute the payment. In this way, you will avoid to process duplicated payment from one PayPal account.

**Comment by veelenga** [comment]
@xiaoleih41 unfortunately, in some cases and due to some reasons we have to pay manually. So everything we know is user's PayPal email address. But we can force user to login with PayPal OpenId and get some information about his profile... Can you confirm that `user_id` is a unique identifier of PayPal account?

**Comment by xiaoleih41** [comment]
@veelenga Yes you can use `user_id` as it's unique to each PayPal account.  `payer_id` may be a restricted feature that only certain contracted partner or merchant can have access to it.

**Comment by ssi-hu-miklos-kosarkar** [comment]
@xiaoleih41 I have the exact same problem. I tried to contanct customer service, they sent me to technical service which only confimed that the documentation is lacking. Is there anyone who can actually tell if the payer_id can be obtained throught the identity API?

**Comment by xiaoleih41** [comment]
@ssi-hu-miklos-kosarkar  Can you email me at xwheelock@paypal.com with your PayPal account email ( live and sandbox). I will see what I can do. It is a limited feature.

**Comment by xiaoleih41** [comment]
The issue should have been solved.

**Comment by veelenga** [comment]
Do you mean globally solved? I still can't access `payer_id` using Identity API. Could you please provide info whether this is restricted attribute or not and who can we contact to have access to it? Unfortunately, I didn't have a chance to contact you privately...

**Comment by xiaoleih41** [comment]
It is a restricted attribute.  Do you have a partner contract with PayPal? To get it enabled for live, you will need to talk to your PayPal account manager and have him apply for you.

**Comment by veelenga** [comment]
@xiaoleih41 okay, thank you.

**Comment by nicolasbrugneaux** [comment]
I'm aware `payer_id` is a restricted feature for partners, but is there any way to access it in sandbox?

**Comment by xiaoleih41** [comment]
@nicolasbrugneaux You will need to talk to your PayPal account manager on that.
