### ISSUE TITLE
payments are pending

### ISSUE THREAD

**Issue by KES777** [paypal/PayPal-REST-API-issues#139]
### General information

* Environment: sandbox
* `PayPal-Debug-ID` values: WH-5DX6806483328223V-4Y760589T11530803
* Language, language version, and OS: perl linux mint 18

### Issue description

can not understand why payments are pending on [page](https://developer.paypal.com/developer/dashboard/webhooks/sandbox)

You should report what is wrong with them

**Comment by xiaoleih41** [comment]
Is this live or sandbox? what type of call are you trying to make? What's the `debugId` for your actual API call?

**Comment by KES777** [comment]
1.
>Is this live or sandbox?

>Environment: sandbox

2. 
>what type of call are you trying to make?

I did call already to `/v1/payments/payment`. I do not understand why state is `pending` instead of `completed`.
We can see that hook on the [page](https://developer.paypal.com/developer/dashboard/webhooks/sandbox) (see screen shot below)


3. 
>What's the debugId for your actual API call?

http://joxi.ru/52aydBYHGv7EW2


### DETAILS

```
{
	"id": "WH-5DX6806483328223V-4Y760589T11530803",
	"create_time": "2017-09-09T13:07:06.867Z",
	"resource_type": "sale",
	"event_type": "PAYMENT.SALE.PENDING",
	"summary": "Payment pending for EUR 30.0 EUR",
	"resource": {
		"reason_code": "RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION",
		"amount": {
			"total": "30.00",
			"currency": "EUR",
			"details": {
				"subtotal": "30.00"
			}
		},
		"id": "4B0772326X093293P",
		"parent_payment": "PAY-19M89871B8275590XLGZ6OSQ",
		"update_time": "2017-09-09T13:06:47Z",
		"create_time": "2017-09-09T13:06:47Z",
		"payment_mode": "INSTANT_TRANSFER",
		"state": "pending",
		"links": [
			{
				"href": "https://api.sandbox.paypal.com/v1/payments/sale/4B0772326X093293P",
				"rel": "self",
				"method": "GET"
			},
			{
				"href": "https://api.sandbox.paypal.com/v1/payments/sale/4B0772326X093293P/refund",
				"rel": "refund",
				"method": "POST"
			},
			{
				"href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-19M89871B8275590XLGZ6OSQ",
				"rel": "parent_payment",
				"method": "GET"
			}
		],
		"invoice_number": "",
		"protection_eligibility_type": "ITEM_NOT_RECEIVED_ELIGIBLE,UNAUTHORIZED_PAYMENT_ELIGIBLE",
		"protection_eligibility": "ELIGIBLE"
	},
	"status": "SUCCESS",
	"transmissions": [
		{
			"webhook_url": "https://XXXX/payment_test/paypal",
			"response_headers": {
				"Strict-Transport-Security": "max-age=31536000; includeSubdomains;",
				"HTTP/1.1 200 OK": "",
				"Date": "Sat, 09 Sep 2017 13:07:16 GMT",
				"Access-Control-Allow-Origin": "",
				"Content-Length": "2",
				"SERVER_INFO": "",
				"Set-Cookie": "app=XXX----XXX; expires=Sat, 16 Sep 2017 13:07:16 GMT; path=/; HttpOnly",
				"Content-Type": "text/html;charset=UTF-8",
				"Connection": "keep-alive",
				"Access-Control-Allow-Credentials": "true",
				"Server": "nginx/1.10.3"
			},
			"transmission_id": "c8370450-955f-11e7-ac1e-6b62a8a99ac4",
			"status": "SUCCESS",
			"timestamp": "2017-09-09T13:07:07Z"
		}
	],
	"links": [
		{
			"href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-5DX6806483328223V-4Y760589T11530803",
			"rel": "self",
			"method": "GET",
			"encType": "application/json"
		},
		{
			"href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-5DX6806483328223V-4Y760589T11530803/resend",
			"rel": "resend",
			"method": "POST",
			"encType": "application/json"
		}
	],
	"event_version": "1.0"
}


```

**Comment by xiaoleih41** [comment]
The payment status is **unclaimed** as EUR is not an open currency on your account. You only have USD currency on your account. In payment receiving preference, it is set the way that the receiver should log in the account to accept or deny the payment if it's not in the currency open on the PayPal account.  once the receiver **accept** the payment, the payment will be completed.

**Comment by KES777** [comment]
>You only have USD currency on your account

**Comment by xiaoleih41** [comment]
if you log into www.sandbox.paypal.com, click on your balance, you should see **Manage Currencies** button. Click on it, add or remove currencies.

**Comment by KES777** [comment]
I can not login there: http://joxi.net/ZrJ4gkyi10gG52.jpg

I use login/password from dashboard. Which login/password should I use?

And why this interface *Manage Currencies* is not available from dashboard?
(Where can I report feature request about this?)

**Comment by KES777** [comment]
**Terrible** interface.

I use this credentials: http://joxi.ru/zAN4l6Vil5g9Mm to login.
but still do not see **Manage Currencies**
http://joxi.ru/J2byLBlH4LyzBm

**Comment by KES777** [comment]
Which UI designer should I fire??? :-D

**Comment by pp-randy** [comment]
Hey @KES777 I changed your facilitator account to just have you accept payments in other currencies for now. Let me know if you need further changes.

**Comment by KES777** [comment]
@pp-randy Thank you very much. But I should know how to do such changes myself.

I do not want ask again someone to change facilitator currency next time I will integrate another company.

So. How do you change the currency? Is there a step-by-step doc?

**Comment by pp-randy** [comment]
https://www.paypal.com/us/selfhelp/article/payment-receiving-preferences-faq2406

**Comment by KES777** [comment]
sadly you you have error in your instruction.
First of all for  **Business** account it do not require to login (first paragraph is missed)
Second the place where I should login must be specified: is it dashboard or production or sandbox?
And third it does not resolve the issue.

I found next:
>Yes, accept and convert them to U.S. Dollars.

But customer has account in EUR and want:
>Yes, accept and convert them to EUR.

Is there possible to do such thing?

**Comment by pp-randy** [comment]
Sorry for not clarifying that FAQ is for the production site.  You would follow the same but for sandbox.  

You need to change the primary currency to EUR.  I can help you do that.  If not this is the production FAQ for how to do it https://www.paypal.com/us/selfhelp/article/how-do-i-change-my-primary-currency-faq1030.

Try this link for sandbox: https://www.sandbox.paypal.com/us/cgi-bin/customerprofileweb?cmd=_profile-currencies

**Comment by KES777** [comment]
oh, I never did that alone. I google many answers but did not find those links.

Should I open new issues for dashboard feedback? @xiaoleih41 #156 

So in your dashboard you should have global switch: `LIVE / SANDBOX` [sceenshot](http://joxi.ru/1A516GpIKOMOZA)
Which will switch all link from production to sandbox and vice-versa.

You should create `Payments` menu entry. and put there two option (as I see now):

1. Primary currency

2. Accept payments in all currencies and convert them to primary currency

This will be clear and easy to setup.

As far as I face some problem again I will update.

**Comment by pp-randy** [comment]
Were you able to add a EUR balance and make it your primary currency?
