### ISSUE TITLE
Unique Transaction ID in web interface is not the same value that's returned from API

### ISSUE THREAD

**Issue by swvjeff** [paypal/PayPal-REST-API-issues#143]
### General information

* Environment: Sandbox 
* Language, language version, and OS: PHP 7.1.9 on CentOS

### Issue description

I've searched around and found some similar issues, but haven't found an answer to my specific question...

I'd like to store the transaction ID after executing a payment, so I try to retrieve it by calling the following:

```php
$result = $payment->execute($execution, $apiContext);
$transaction = $result->getTransactions()[0];
$transactionId = $transaction->getRelatedResources()[0]->getSale()->getId();
```

I'm able to obtain a transaction ID, but it doesn't appear to be the same value that's listed in the PayPal web UI under the "Unique Transaction ID" field.  I've also tried calling ```Payment::get($paymentId)``` after ```$payment->execute()``` but I'm still getting a different transaction ID value. The weird thing is, if I search the PayPal web UI for the transaction ID returned by the above code, the the correct transaction is returned, but it displays a different Unique Transaction ID on the payment details page. Am I doing something wrong or is this expected behavior?

**Comment by xiaoleih41** [comment]
Where do you see the unique transaction ID? from the sender's account or from the receiver's account?  The `transaction Id` of the sender and receiver is different for the same transaction. The  **saleId** should match to the **unique transaction ID** of the **receiver's account**.

**Comment by swvjeff** [comment]
Ahh, thank you. It looks like I was logged into the buyer account when testing my transactions. I wasn't aware buyers and receivers have separate transaction IDs.
