### ISSUE TITLE
Execute Billing Agreement response does not contain plan "name" per the docs

### ISSUE THREAD

**Issue by radiantone** [paypal/PayPal-REST-API-issues#145]
### General information

* Environment: sandbox
* `PayPal-Debug-ID` values: none visible in my dashboard
* Language, language version, and OS: python, ubuntu 16.04

### Issue description

After I call BillingAgreement.execute(payment_token) the response contains details of the plan except for the name and plan id. Without these two pieces of information I have no way of knowing what plan the user just executed because the PayPal redirect only contains the payment token.

Since the web application is orchestrating the subscription flow, it should be possible to connect the chosen plan at the onset of the flow with the executed agreement redirect that completes it.

**Comment by xiaoleih41** [comment]
This issue has been tracked at https://github.com/paypal/PayPal-REST-API-issues/issues/92. Please refer to the workaround in the discussion thread of that issue.

**Comment by radiantone** [comment]
Thanks. I read the workaround. Not entirely workable in every situation. In my opinion this is an adoption blocker to this API. Since it involves binding agreements and commerce, the exact plan being agreed to needs to be returned from the authority of the transaction, paypal. Linking these entities on our side puts a bit of liability there. I would see about resolving this as a serious bug rather than a feature. Just my suggestion.

**Comment by xiaoleih41** [comment]
The feedback has been noted. Closing this issue. Please follow the above issue for any updates.
