### ISSUE TITLE
Continually and randomly getting 'Internal Error' status code 400

### ISSUE THREAD

**Issue by alexstanbury** [paypal/PayPal-REST-API-issues#146]
I have received no reply from Tech Support, contacted them 4 days ago. This is happening on a production site and is losing us and PayPal money. 

### General information

* Environment:Production
* `PayPal-Debug-ID` values: 7e26bc6d73989, 6c9196f1d8655 (I could provide hundreds)
* Language, language version, and OS: All of them

### Issue description

I'm creating a billing plan each time as our subscriptions are available in different currencies and we offer discounts. The API is failing randomly given exactly the same data, sometimes 9 times out of 10 (or worse) and sometimes 3 in 10, but there is definitely something wrong.

Here is my code:

```
app.post('/paypal/createBillingPlan', function (req, res, next) {

    var jsonData = JSON.parse(req.body.jsonData);
    var paymentObj = getUpgradePaymentObj(jsonData);

    var setupBillingPlan = function () {

        var billingPlanAttribs = {
            "name": "TEST PLAN",
            "description": 'DESCRIPTION GOES HERE',
            "type": "INFINITE",
            "payment_definitions": [{
                "name": "Standard Plan",
                "type": "REGULAR",
                "frequency_interval": "1",
                "frequency": "MONTH",
                "cycles": "0",
                "amount": {
                    "currency": "USD",
                    "value": "10"
                }
            }],

            "merchant_preferences": {
                "cancel_url": "http://www.test.com",
                "return_url": "http://www.test.com",
                "max_fail_attempts": "3",
                "auto_bill_amount": "YES",
                "initial_fail_amount_action": "CANCEL"
            }
        };

        var billingPlanUpdateAttributes = [{
            "op": "replace",
            "path": "/",
            "value": {
                "state": "ACTIVE"
            }
        }];

        paypal.billingPlan.create(billingPlanAttribs, function (err, billingPlan) {
            if (err) {
                reportError('could not create billing plan...', err);
                return next(err);
            } else {
                console.log('update with id', billingPlan.id);
                console.log('update with attrs', billingPlanUpdateAttributes);
                // Activate the plan by changing status to Active
                paypal.billingPlan.update(billingPlan.id, billingPlanUpdateAttributes,
                    function (err, response) {
                        if (err) {
                            **/////////////ERROR HAPPENS HERE//////////////**
                            reportError('could not update billing plan...', err, paymentObj, billingPlan, billingPlanAttribs);
                            return next(err);
                        } else {
```

The completely unhelpful error object returned is as follows:

```
{ name: 'INTERNAL_ERROR',
     message: 'Internal error',
     information_link: 'https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_ERROR',
     debug_id: '6c9196f1d8655',
     httpStatusCode: 400 },
```

I'm sick to the back teeth with PayPal, we've had nothing but issues the whole time. We tried speaking to your customer services who were completely unhelpful and had no idea what to say, they did say that a response from tech support could take 30 (yes, thirty!!) days! Surely a company that makes as much money as PayPal can afford to hire enough staff to deal with their merchants?

Anyway, rant over - hopefully someone here can offer some light at the end of the tunnel...

Thanks

**Comment by xiaoleih41** [comment]
Please provide the support ticket number. I will have them follow up.

**Comment by alexstanbury** [comment]
Sure, it's #170922-000033, thanks.

**Comment by xiaoleih41** [comment]
The issue has been escalated. They are taking care of it and will reach out to you once it's solved.

**Comment by alexstanbury** [comment]
Thanks :)

**Comment by jeprojects** [comment]
I am getting this same issue too.. Looking forward to a resolution.

**Comment by xiaoleih41** [comment]
@jeprojects  It might be a bug. Please submit a ticket at www.paypal-techsupport.com. They will track and prioritize the issue fix.

**Comment by jeprojects** [comment]
@xiaoleih41 Are you serious? I need to signup for an account on that site just to get support to fix something that has been working for a long time and no longer works? An internal error means just that, PayPal has an internal error.

Bugs seem like a very common place for PayPal these days.

Here is a debug id: fc5987b566834

**Comment by pp-randy** [comment]
Yes, file please file a ticket here: https://www.paypal-techsupport.com/app/ask/. 

Are you creating a lot of billing plans?  Guesstimate on how many have you created so far?  I will try to reproduce if I can.  

I would advise reusing plans, where you can, if its currently only plan patching that is impacted and not agreement creation.

**Comment by jeprojects** [comment]
@pp-randy Ok I will raise a ticket there.

No I am not creating many billing plans. I am reusing most of the time.

The only time a new billing plan is created is when there needs to be a special initial payment amount.

I would say there should only be about 10-15 billing plans.

**Comment by alexstanbury** [comment]
This appears to be fixed for us now. Still had no communication from tech support though. Thanks for those here that may have helped speed up the fix anyway. Hopefully Tech Support will now do something about the other issue I filed with them and have had no response about as well!

**Comment by xiaoleih41** [comment]
@alexstanbury Leave comments on your ticket numbers. I'll have someone look at. Close this issue as the issue has been fixed.
