### ISSUE TITLE
Accepting direct card payments with Payments API

### ISSUE THREAD

**Issue by bobby-nicholas** [paypal/PayPal-REST-API-issues#147]
Hello -  My company is developing an app to take credit card orders over the phone.  I am using the .NET SDK and am pointing at the Payments end point.  On sandbox, the payments are approved, but I get UNAUTHORIZED_TRANSACTION when on live.  This is a US based company with only US and CA customers.

Is there any way I can enable direct card payments using the Payments API (without a page redirect) instead of having to go the PayPal Payments Pro/Payflow route?  Is there a different endpoint or account setting that can be configured?

Thank you!

**Comment by xiaoleih41** [comment]
This error might have something to do with your transaction specifics.  PayPal is deprecating direct credit card processing for REST API. I would strongly suggest to integration Braintree SDK from Braintreepayments.com, PayPal Payments pro or Payflow product for your direct credit card processing needs.

**Comment by xiaoleih41** [comment]
Closing this issue as direction has been given.
