### ISSUE TITLE
Need per-item options field

### ISSUE THREAD

**Issue by kryptus36** [paypal/PayPal-REST-API-issues#149]
When creating a payment, the objects in payment.transactions.item_list.items should have an "options" object where one can populate key value pairs for each item for things like "color", "size" or any other arbitrary option.

eg:

`"transactions": [
  {
    "amount":
    {
      "total": "4.00",
      "currency": "USD",
      "details":
      {
        "subtotal": "2.00",
        "shipping": "1.00",
        "tax": "2.00",
        "shipping_discount": "-1.00"
      }
    },
    "item_list":
    {
      "items": [
      {
        "quantity": "1",
        "name": "item 1",
        "price": "1",
        "currency": "USD",
        "description": "item 1 description",
        "tax": "1",
        "options": {
          "color": "red",
          "size": "large"
        }
      }
    }
  }
]

### General information

* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by xiaoleih41** [comment]
I have submit a request regarding this.

**Comment by xiaoleih41** [comment]
It turns out that it's a feature that only exists in PayPal website payment standard button. It's a logic that is supposedly handled on the merchant site therefore this feature will not be considered. https://github.com/paypal/PayPal-REST-API-issues/issues/137
