### ISSUE TITLE
Payment error : The requested resource ID was not found

### ISSUE THREAD

**Issue by alexstanbury** [paypal/PayPal-REST-API-issues#152]
I've filed this issue with Tech Support who have so far been silent, here's my reference number: #170926-000144

* Environment: Production
* `PayPal-Debug-ID` values: 640291b5cd2c5, 505601446321, af182a3edcf81, 5bb3aff78b32b and many more
* Language, language version, and OS: NODE paypal-rest-sdk@1.7.1

### Issue description

I'm randomly and regularly receiving the following error, I don't yet know whether the transaction is actually completing, but I do know that my users will not be shown a success message when this error happens:

```
{"response":{"name":"INVALID_RESOURCE_ID","message":"The requested resource ID was not found","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"5bb3aff78b32b","httpStatusCode":404},"httpStatusCode":404}
```

Here's my server code:

```
app.get('/paypal/executePlayerPayment/:paymentObj/', function (req, res, next) {

    var paymentObj = JSON.parse(req.params.paymentObj);

    var execute_payment_json = {
        "payer_id": req.query.PayerID,
        "transactions": [{
            "amount": {
                "currency": paymentObj.currencyCode,
                "total": paymentObj.amount
            }
        }]
    };

    var paymentId = req.query.paymentId;

    paypal.payment.execute(paymentId, execute_payment_json, function (err, payment) {
        if (err) {
            /*******///// ERROR HERE ///////*******/
           ...
            return next(err);
        } else {
           ...
        }
    });

});
```

**Comment by xiaoleih41** [comment]
This issue is current tracked at https://github.com/paypal/PayPal-REST-API-issues/issues/151 Please follow that issue for the status.
