### ISSUE TITLE
Webhooks for Invoices Not being sent in sandbox 

### ISSUE THREAD

**Issue by zshimanchik** [paypal/PayPal-REST-API-issues#153]
> For internal bookkeeping: PPPLPAYPT-28244

### General information

* Environment: Sandbox
* Language, language version, and OS: Python (`paypalrestsdk==1.13.1`) on Docker `python:3.6`

### Issue description
There is no request comes on Webhook after Invoice payment in sandbox. Here is what I have done:
1. Created two test accounts in sandbox for payment.
2. Registered and configured REST application
3. Configured Webhook for app for all events. Tested this webhook using [webhook simulator](https://developer.paypal.com/developer/webhooksSimulator/)
4. Created Invoice using API (python sdk: paypalrestsdk==1.13.1)
5. Paid Invoice using test user.
6. Made sure that Invoice is paid in [sandbox](https://www.sandbox.paypal.com/invoice/manage)

I expect request on my webhook, but it doesn't happen. Also I check [Webhook Events](https://developer.paypal.com/developer/dashboard/webhooks/sandbox) but there is no event was created.

Is this a known defect? When It will be fixed?
Will webhooks work on Live?

**Comment by pp-randy** [comment]
I've seen some delays the past few days in sandbox, should be fine in live. Did you eventually get the webhooks?  If so, are you still getting delays?  I will run some tests as well.

**Comment by pp-randy** [comment]
I received a payment webhook after a delay, and did not receive an invoice webhook.  I have escalated this internally and will provide updates when able.

**Comment by commanderZiltoid** [comment]
I am having the same issue, but with merchant onboarding completion event. Everything works with web hook simulator, but when going through the onboarding process, upon completion the configured web hook does not sent request to server.

I have my listener set to write requests to a log file. Waiting to see if this is a delay issue or not, but right now it's been about four hours and I have yet to see a request from the configured  webhook.

**Comment by commanderZiltoid** [comment]
@pp-randy Have there been any updates on this?

**Comment by xiaoleih41** [comment]
@commanderZiltoid  It is under research status. We will update the status once it's fixed.

**Comment by zshimanchik** [comment]
I received today webhook for invoice creation very fast within one minute. And received webhook for invoice paid event within 20 minutes. Let's check it for couple more days.

**Comment by commanderZiltoid** [comment]
We are still not receiving webhook requests for the MERCHANT.ONBOARDING.COMPLETED event.

**Comment by pp-randy** [comment]
Closing as the issue has been resolved.  

@commanderZiltoid that is a separate webhook issue are you still seeing an issue with it?

**Comment by commanderZiltoid** [comment]
@pp-randy We are, however after reaching out to another developer at paypal we were informed: 

"that the MERCHANT.ONBOARDING.COMPLETED webhook is specific to one of our other products which is in a closed beta at the moment"

Which would explain why we were not receiving this request.
