### ISSUE TITLE
How to disallow users from editing the provided shipping address?

### ISSUE THREAD

**Issue by cedivad** [paypal/PayPal-REST-API-issues#154]
It looks like I can provide a shipping address to the payment/payment endpoint, but how can I make sure the user doesn't change that in the checkout process, similarly to ADDROVERRIDE in the older API?

Do I need to use the older API? I guess it's compatible with the newer "checkout.js" user interface, correct?

Thank you

**Comment by xiaoleih41** [comment]
[address_override}(https://developer.paypal.com/docs/api/payment-experience/#definition-input_fields) from experience API should be the replacement of the NVP/SOAP API.

**Comment by xiaoleih41** [comment]
close the issue as the answer has been provided.

**Comment by cedivad** [comment]
Yep, your solution worked, thank you!
