### ISSUE TITLE
500 Internal Error when creating a Payout

### ISSUE THREAD

**Issue by danzrou** [paypal/PayPal-REST-API-issues#165]
> For internal tracking PPPLPAYPT-29886
### General information

* Environment: Sandox
* `PayPal-Debug-ID` values: 4321dd605b2f0
* Language, language version, and OS: Java 1.8

### Issue description

**I'm Using PayPal's Java SDK.**
When trying to create a payout, 500 is returned - I tried both with _sync_mode=true_ and _sync_mode=false_ 
I saw #130 but the error seems to reoccur. 

```
{"name":"INTERNAL_ERROR",
"message":"An internal service error has occurred.",
"debug_id":"4321dd605b2f0",
"information_link":"https://developer.paypal.com/docs/api/payments.payouts-batch/#errors"}
```

**Comment by garrettqmartin8** [comment]
Same issue here. This was working yesterday.

**Comment by xiaoleih41** [comment]
I am looking into this.

**Comment by xiaoleih41** [comment]
This issue has been solved. Close this issue.
