### ISSUE TITLE
uri is missing from invoice object

### ISSUE THREAD

**Issue by KES777** [paypal/PayPal-REST-API-issues#170]
> for internal tracking PPPLPAYPT-30847

in the [DOC](https://developer.paypal.com/docs/api/invoicing/#invoices_get)

> uri
string
The URI of the invoice.
Read only

There is not `uri` field in response object. See what I get:

```
{
    ... <snipped response>
}

```

Notice:

    metadata\payer_view_url => https://www.sandbox.paypal.com/invoice/payerView/details/INV2-5N89-MQGG-ZGGR-2H64

Please fix the DOC or response object

**Comment by xiaoleih41** [comment]
I have reported this issue. Thank you for pointing it out.

**Comment by xiaoleih41** [comment]
Close as the issue  has been solved.
