### ISSUE TITLE
`cost` object listed in Invoicing API request should be renamed to `discount`

### ISSUE THREAD

**Issue by KES777** [paypal/PayPal-REST-API-issues#172]
>For internal tracking: PPPLPAYPT-30954

And here is similar issue: [screenshot](http://joxi.ru/D2PEpdQIde8pYA)

You are saying about `discount` but field name is `cost`. 
So the `cost` should be renamed to `discount` because it is ambiguous

it is similar to #168

**Comment by KES777** [comment]
hm... you even refer from `discount` to `cost` as: 
https://developer.paypal.com/docs/api/invoicing/#definition-cost

from [here](https://developer.paypal.com/docs/api/invoicing/#invoices_create)
http://joxi.ru/brRjbK6HQpE6er

**Comment by xiaoleih41** [comment]
Thank you for pointing it out. I am submitting a feedback on this.

**Comment by xiaoleih41** [comment]
Close this issue as the documentation has been fixed accordingly.
