### ISSUE TITLE
PayPal do not resend webhooks

### ISSUE THREAD

**Issue by KES777** [paypal/PayPal-REST-API-issues#173]
### General information

* Environment: Sandbox
* `PayPal-Debug-ID` values: uname -a
Linux work 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

* Language, language version, and OS: perl 5.24

### Issue description

When I click on webhook I often get this error:
http://joxi.ru/v29DKGlcGnJkam

http://joxi.ru/8234Qvpi6kYOwA

The webhook: `WH-88646729T7415724L-36Y43238Y8394971T`

When I click the 'Resend' button dashboard says that WebHook is `Sent`[screenshot](http://joxi.ru/J2byLBlH4Jby3m). but on my side nothing is happened. I do not see any events from PayPal.

It will be handy if you in dashboard show PP requests history to our interface with reporting request details and errors

Without `resend` feature I need to repeat whole order and this slowdown me to implement express checkout

**Comment by pp-randy** [comment]
Do you ever get the initial webhook?

**Comment by pp-randy** [comment]
Can you open your browser developer tools and try to get any additional error messaging when this error when loading occurs?  I am not able to reproduce currently.

**Comment by KES777** [comment]
http://joxi.ru/vAWMwOZIk54xWm

There is no error. Response is 200 OK with no body. And sometimes there is no response at all.

**Comment by xiaoleih41** [comment]
I haven't been able to get the payment.sale.completed webhook.  I am reporting this issue.

**Comment by xiaoleih41** [comment]
Close this issue as the issue seems to be fixed.

**Comment by KES777** [comment]
I am on different task now. When I back I will check

**Comment by KES777** [comment]
Yes, seems work
