### ISSUE TITLE
422 response when try to make negative tests

### ISSUE THREAD

**Issue by webmasterdro** [paypal/PayPal-REST-API-issues#174]
### General information

* Environment: Sandbox
* `PayPal-Debug-ID` values: --
* Language, language version, and OS: PHP 7.1 on Ubuntu

### Issue description

```
$apiContext = new \PayPal\Rest\ApiContext(
            new \PayPal\Auth\OAuthTokenCredential()
 );
 $apiContext->addRequestHeader("PayPal-Mock-Response", json_encode(['mock_application_codes' => 'INSUFFICIENT_FUNDS']));


$apiContext->setConfig([
            'mode' => 'sandbox', // sandbox ou live
            'http.ConnectionTimeOut' => 30,
            'log.LogEnabled' => false,
            'log.FileName' => '',
            'log.LogLevel' => 'FINE',
            'validation.level' => 'log'
]);
```

I follow this: https://developer.paypal.com/docs/api/nt-rest/ to test PayPal errors. But I just see an exception in both (create_payment and execute_payment).

```
An uncaught Exception was encountered

Type: PayPal\Exception\PayPalConnectionException

Message: Got Http response code 422 when accessing https://api.sandbox.paypal.com/v1/oauth2/token.
```

**Comment by pp-randy** [comment]
Try the header with the payments endpoint and not the authentication endpoint.  

Can you get a debug id for your authentication failure?

**Comment by webmasterdro** [comment]
@pp-randy  Sorry but I don't understand >.<

**Comment by pp-randy** [comment]
@webmasterdro are you trying to get this failure during a payment?  The header is causing a failure when you are getting the access token, the API call made before the payment.  The PHP SDK was built before negative testing was added to the REST API, most likely the injection needs to happen here https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Common/PayPalResourceModel.php#L100-L101.

**Comment by pp-randy** [comment]
@webmasterdro I will run some testing on my suggestion above to see if it will work for your needs.

**Comment by pp-randy** [comment]
This is what worked for me.
```
$apiContext->addRequestHeader("PayPal-Mock-Response", '{"mock_application_codes":"AMOUNT_MISMATCH"}');
$payment->create($apiContext);
```

**Comment by webmasterdro** [comment]
Hello @pp-randy 

I'll try ASAP. For some reason my ISP is blocking me to access https://developer.paypal.com/ so there's no way to test it at this moment.

**Comment by webmasterdro** [comment]
Hello @pp-randy 

I tested it again and result in the same error. I've tried in two ways, but both result in the same error: "Got Http response code 422 when accessing https://api.sandbox.paypal.com/v1/oauth2/token."

```
try {
// (new \PayPal\Rest\ApiContext())->addRequestHeader("PayPal-Mock-Response", '{"mock_application_codes":"AMOUNT_MISMATCH"}');
// $apiContext->addRequestHeader("PayPal-Mock-Response", '{"mock_application_codes":"AMOUNT_MISMATCH"}');
$payment->create($apiContext);
$this->output->set_content_type("application/json")
                ->set_output(json_encode(array('transaction_code' => $payment->getId())));
            } catch (Exception $e) {
 $this->output->set_content_type("application/json")
                ->set_output(json_encode(array('transaction_code' => $e->getMessage())));
}
```

**Comment by pp-randy** [comment]
@webmasterdro it seems like your request is still hitting your get access token api call a not your payments call.

Try this as a workaround, create two payments, this should hopefully let you get past the access token issue you are facing. 
$payment->create($apiContext);   
$apiContext->addRequestHeader("PayPal-Mock-Response", '{"mock_application_codes":"AMOUNT_MISMATCH"}');
$payment->create($apiContext);

**Comment by webmasterdro** [comment]
@pp-randy Hello. I'm with bad luck. Don't work either. With this workaround, I get status 400 (in the payment creation after Mock Response). =/

**Comment by pp-randy** [comment]
The negative header was supposed to cause a 400 Bad Request for payments.  What error is being returned in the response body? 

Status Code: 400 Bad Request
JSON:`{ "name": "AMOUNT_MISMATCH", "message": "The totals of the cart item amounts do not match sale amounts.", "information_link": "https://developer.paypal.com/docs/api/payments/#errors", "details": "The amount total does not match the item amount totals." }`

**Comment by webmasterdro** [comment]
`
"Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment."`

**Comment by webmasterdro** [comment]
Whoops! My bad. I forgot to catch the full exception. It's working now! 

Thank you very much @pp-randy.

Best regards.
