### ISSUE TITLE
Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment/PAY-/execute.

### ISSUE THREAD

**Issue by drstil** [paypal/PayPal-REST-API-issues#175]
Dear all,

I'm initializing a payment with payment method "PayPal" as described in the doc (http://paypal.github.io/PayPal-PHP-SDK/sample/). Till now I'm working in sandbox environment. Sometimes, but the last two days almost always, when I want to get the payment by the payment id (`$payment = Payment::get($paymentId, $utilPayPal->apiContext);`), I got an 

`PayPalConnectionException: Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment/PAY-/execute.`

Sometimes I also got another Exception at the same step:

`PayPalConnectionException: Operation timed out after 60001 milliseconds with 0 bytes received.`

But those exceptions occur only sometimes (very often the last two days) and my configuration is always the same. Sometimes everything works correctly and the payment is approved.

I'm working with current PayPal SDK.

Thank you and best!

**Comment by pp-randy** [comment]
Are you able to provide a paypal-debug-id from some of those 500 failures?   You would get it from the response headers.  You should be able to use the PHP helper function here as well https://github.com/paypal/PayPal-PHP-SDK/tree/master/lib/PayPal/Api/Error.php#L114.

**Comment by drstil** [comment]
Sorry but I did not get more information than I have just supplied. Only PaymentId. 
There is no DebugId or anything else. Found DebugId only in \PayPal\Api\Error class and nowhere else. How could I got this when I am just getting this payment with the following code? Do I have to change something in the api code?

`
[...]
try {
        $result = $payment->execute($execution, $apiContext);
        ResultPrinter::printResult("Executed Payment", "Payment", $payment->getId(), $execution, $result);
        try {
            $payment = Payment::get($paymentId, $apiContext);
[...]
`

**Comment by walter-schuh** [comment]
Hi, I'm getting the same issue when testing the API for a new project. Payment ID is PAY-46A19430XE2532726LJCRREA and debug id is 88d6c02160e15

**Comment by pp-randy** [comment]
@walter-schuh I see two API requests at the same time in the logging, and one has completed.  Can you do a lookup on PAY-46A19430XE2532726LJCRREA and see if you have a transaction in the related resources?  Are you using an SDK if so which one? 

@drstil did your execute create a transaction for PAY-9A668468NA140602VLI4M77Q?

**Comment by drstil** [comment]
Yes it did "create" for all the payments/transactions where I got the error. I also wrote to PayPal technical support and got answer:

> I found we have an issue currently under investigation/fix for this error. Looks like an internal error that Engineers are fixing.
> I was able to find the API calls from your account and it links to the same issue.
> I will update once the Engineers fixed it.

Till now I did not get any other response from technical support. But the error occurs much less.

Thank you!

**Comment by walter-schuh** [comment]
@pp-randy I'm using the C# SDK version 1.9.1 for the server-side and checkout.js for the client side setup and I am only making one call to create the payment then redirecting to the sandbox to use my test credentials and then sending one call to execute with the PayerID and PaymentID returned.

**Comment by pp-randy** [comment]
@walter-schuh it is my understanding  from your update that your server code is making the two requests.  Did you want to paste and example of your code for me to review?

**Comment by walter-schuh** [comment]
@pp-randy it is the client side code that is making 2 calls to my server-side method from the following line:

`return paypal.request({ url: executeURL, method: 'post', json: data })`

**Comment by pp-randy** [comment]
@walter-schuh do you have a URL I can visit to see whats happening?

**Comment by xiaoleih41** [comment]
Close due to inactivity.
