### ISSUE TITLE
Check Payment Address for status, confirmed/unconfirmed

### ISSUE THREAD

**Issue by penguinstampede** [paypal/PayPal-REST-API-issues#176]
> For internal bookkeeping: PPPLPAYPT-31441

### General information

* Environment: Sandbox
* Language, language version, and OS: Python 2.7.13, Mac OS X

### Issue description

Based on the documentation I am under the impression that a Payment (sale) shipping address (payment.transactions[0].item_list.shipping_address, for example) should have a "status" field with either CONFIRMED or UNCONFIRMED.

<img width="600" alt="screen shot 2017-12-20 at 5 05 52 pm" src="https://user-images.githubusercontent.com/2476990/34236461-8c1250f4-e5ac-11e7-8228-8cb897b41934.png">

However, when making a POST to the API (sandbox and production), I see no status field under the shipping_address, and when using the Python paypalrestsdk (in sandbox), shipping_address.status returns None.

Is there another way to use the REST API to check if a buyer's shipping address is confirmed by Paypal?  I've tried looking on StackOverflow and the response from a year ago was that the functionality just isn't in place yet... is that still the case?

**Comment by pp-randy** [comment]
I am able to reproduce the issue, status is not being returned in my testing.  I have escalated internally for additional research.

**Comment by pp-randy** [comment]
`status` has been removed from the documentation.

**Comment by xiaoleih41** [comment]
Close this issue as the status has been removed from the documentation.
