### ISSUE TITLE
Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-agreements/

### ISSUE THREAD

**Issue by hanson-tapatalk** [paypal/PayPal-REST-API-issues#177]
### General information

* Environment: both sandbox and live
* `PayPal-Debug-ID` values: 5363d955c93a9
* Language, language version, and OS: php 7.0 on Ubuntu 16.04

### Issue description

Here is the code

`       $agreement = new Agreement();

        $agreement->setName($metadata->all['forum_id'] . '-' . $metadata->all['user_id'])
                  ->setDescription($description)
                  ->setStartDate($startDate);

        $plan = new Plan();
        $plan->setId($planId);
        $agreement->setPlan($plan);

        $payer = new Payer();
        $payer->setPaymentMethod('paypal');
        $agreement->setPayer($payer);

        try
        {
            $agreement = $agreement->create($apiContext);
            $token     = $this->getPayPalTokenFromUrl($agreement->getApprovalLink());
        } catch (\Exception $e)
        {
            self::payPalLog($e, '[Create Billing Agreement Failed]');
        }`

It's been running for a couple of month. But it's failed since last Friday for some reason.

Here is the Exception detail:

[25-12-2017 03:12:43] PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-agreements/.
 {
    "name":"BUSINESS_VALIDATION_ERROR",
    "details":[{"field":"validation_error","issue":"Incorrect Template Id."}],
    "message":"Validation Error.",
    "information_link":"https://developer.paypal.com/docs/api/payments.billing-agreements#errors",
    "debug_id":"5363d955c93a9"
}

What is this "Incorrect Template Id."? How do I solve this? I did not change any of my code for at least a month.

**Comment by hanson-tapatalk** [comment]
I found the problem, this file "/vendor/paypal/rest-api-sdk-php/var/auth.cache" need write permission. And we updated our vendor last Friday. The file permission has been changed. How do I config this, or do I have to give this file permission each time we update our vendor?

**Comment by pp-randy** [comment]
You have some options here https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/sdk_config.ini#L52-L67.  

Please let me know if you need additional information.

**Comment by pp-randy** [comment]
@hanson-tapatalk I have created an issue SDK side for research the error from the SDK side, since the permission problem faced caused some possible API issues it seems https://github.com/paypal/PayPal-PHP-SDK/issues/1029.

**Comment by hanson-tapatalk** [comment]
@pp-randy Thank you very much. I changed my code.

$this->apiContext->setConfig(
            [
                'mode'           => $mode,
                'log.LogEnabled' => true,
                'log.FileName'   => '/var/mypath/logs/PayPal.log',
                'log.LogLevel'   => 'INFO', // PLEASE USE `INFO` LEVEL FOR LOGGING IN LIVE ENVIRONMENTS
                'cache.enabled'  => true,
                'cache.FileName' => '/var/mypath/logs/auth.cache',
            ]
        );
