### ISSUE TITLE
APIContext looses ClientID

### ISSUE THREAD

**Issue by rlfnb** [paypal/PayPal-REST-API-issues#178]
* Environment: each and every environment
* Language, language version, and OS: MacOS, Oracle-Java 1.8.0-b132 (does not matter at all)

`
        <dependency>
            <groupId>com.paypal.sdk</groupId>
            <artifactId>rest-api-sdk</artifactId>
            <version>1.14.0</version>
        </dependency>
`

### Issue description

`
        com.paypal.base.rest.APIContext context = new com.paypal.base.rest.APIContext("myClientID", "myBla", "sandbox");
`

fails with missing client id credentials, i was able to workaround via:

`
        APIContext context = new APIContext("myClientID", "myBla", "sandbox");
        context.addConfiguration(com.paypal.base.Constants.CLIENT_ID, "myClientID");
`

I suppose, its a bug?

**Comment by pp-randy** [comment]
Thank you for the pull request. I will update it with your comments and close this in favor of it https://github.com/paypal/PayPal-Java-SDK/pull/328.
