### ISSUE TITLE
Payment application_context is not documented

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [paypal/PayPal-REST-API-issues#179]
>Migrated from paypal/PayPal-Java-SDK#330

 >For internal tracking PPPLMER-44003

Missing `application_context` in [Payments API](https://developer.paypal.com/docs/api/payments/)reference. 
Relative to https://github.com/paypal/PayPal-Java-SDK/issues/330

### General information

* Environment: documentation

### Issue description

We need to prevent customer (buyer) changes address during payment approving. As discussed with [Kristian Büsch](https://www.linkedin.com/in/kristian-büsch-57429a19/) (can't refer him from GitHub) the recommended way to do this - using `application_context#shipping_preference` entity in create payment, for example:
```bash 
curl --request POST 'https://api.sandbox.paypal.com/v1/payments/payment' \
  --data '{
  "intent": "sale",
  "payer": {
    "payment_method": "paypal"
  },
  "application_context": {
    "locale": "DE",
    "brand_name": "Company Name",
    "shipping_preference": "NO_SHIPPING"
  },
  "transactions": [
.......
```

this approach works fine (we testes on sandbox using HTTP REST API), but [`Payment API`](https://developer.paypal.com/docs/api/payments/#definition-application_context) documentation doesn't have this chapter. In the same time it is documented in [Orders API](https://developer.paypal.com/docs/api/orders/#definition-application_context). 

Also, last but not least: this feature (prevent address change) is very important for us and our customers, so pls respond as soon as possible.

Thanks.

**Comment by pp-randy** [comment]
We are following up on the documentation for this field.

**Comment by xiaoleih41** [comment]
The issue has been solved.

**Comment by radistao** [comment]
@xiaoleih41 
you mean now it is documented properly?
Guess also the PR from the SDK repo https://github.com/paypal/PayPal-Java-SDK/pull/350 is also connected to this issue, isn't it?

**Comment by xiaoleih41** [comment]
@radistao The doc has been fixed. it's now listed [here](https://developer.paypal.com/docs/api/payments/#payment-create-request-body)

**Comment by safebyte** [comment]
@xiaoleih41 it's `shipping_preference` (singular) as @andrii-kovalenko-ct mentions - the documentation says `shipping_preferences` (plural) which leads to a ` MALFORMED_REQUEST` error

**Comment by Jucedik** [comment]
Please fix **shipping_preferences** to **shipping_preference**

**Comment by zonaut** [comment]
It still says shipping_preferences in the online documentation -> https://developer.paypal.com/docs/api/payments/#definition-application_context

**Comment by EthanML** [comment]
Tripped up over the "shipping_preferences" typo today as well and struggled with the rather unhelpful "MALFORMED_REQUEST" for some time before finding this issue - could we get this fixed in the documentation?

**Comment by AL1L** [comment]
I've been wondering why this error is being caused, I've read the docs 1000s of time did a bunch of googling. Please change the docs asap.
