### ISSUE TITLE
PayPal Plus PATCH does not update the address

### ISSUE THREAD

**Issue by lojzatran** [paypal/PayPal-REST-API-issues#180]
> For internal bookkeeping: PPPLPAYPT-32284
### General information

* Environment: sandbox
* `PayPal-Debug-ID` values: 7993efba1f67a
* Language, language version, and OS: Java 1.8.0_131, Mac OS 10.13.2

### Issue description
Issue is the same as this one: https://github.com/paypal/PayPal-REST-API-issues/issues/124. It seems like the problem is still not fixed. Can you please verify?

**Comment by xiaoleih41** [comment]
Let me check internally and get back to you on this.

**Comment by pp-randy** [comment]
In my testing the PATCH updates the address, but it does not show in the Payment Lookup.  It will show on the checkout and after the buyer approves the payment. We are following up though to get it added.

**Comment by pp-randy** [comment]
The fix has been pushed live.  I ran a test in sandbox and the address was returned after being added with a patch.  Please let us know if it was not resolved for you.
