### ISSUE TITLE
Payments API REST endpoint does not return some values (payer, application context, experience profile id)

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [paypal/PayPal-REST-API-issues#181]
> For internal bookkeeping: PPPLPAYPT-32349

### General information

* Environment: Sandbox (not tested on production though)
* `PayPal-Request-Id`: 
  - _application context_:
    - create `f06276df-00f3-4de5-9b36-0ce0f9a506a8`
    - patch `f4efea9b-1e65-4352-b5e2-cc12344709bf` (could be skipped)
    - get `fb625957-6ce7-4aba-836c-2b4fefb90022`
  - _experience profile id_:
    - create `13bbdbe7-ef5e-4edc-819e-08ac73ccad4c`
    - patch `0cb7c61a-b8a6-4db7-9e92-fc085d58b979` (could be skipped)
    - get `45d66d0d-a837-4c1d-a9f3-bd1188f29015`
* Language, language version, and OS: REST API

### Issue description

Using HTTP REST API endpoints described in https://developer.paypal.com/docs/api/payments/ when payment is created, optionally updated (patched) and later got by id - some fields are missing in the response. The issue is consistent at least with _application_context_, _payer_ and _experience profile id_ values. 

#### Actual behavior:
 
  1. Create Payment:
  ```bash 
  curl --verbose --request POST 'https://api.sandbox.paypal.com/v1/payments/payment' \
  --header "Authorization:Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" \
  --header "User-Agent:PayPalSDK/  (v=1.8.0_144; vendor=Oracle Corporation; bit=64; os=Mac_OS_X 10.13.2)" \
  --header "PayPal-Request-Id:f06276df-00f3-4de5-9b36-0ce0f9a506a8" \
  --header "Content-Type:application/json" \
  --data '{
  "application_context": {
    "shipping_preference": "SET_PROVIDED_ADDRESS"
  },
  "intent": "sale",
  "payer": {
    "payment_method": "paypal"
  },
  "transactions": [
    {
      "amount": {
        "currency": "EUR",
        "total": "252.00",
        "details": {
          "subtotal": "252.00",
          "shipping": "0.00"
        }
      },
      "description": "Payment from commercetools Paypal Plus integration service",
      "item_list": {
        "items": [
          {
            "sku": "sku_MB_PREMIUM_TECH_T_variant1_1499245187441",
            "name": "MB PREMIUM TECH T",
            "quantity": "1",
            "price": "100.00",
            "currency": "EUR"
          },
          {
            "sku": "sku_GIRLS_HARTBREAK_CREW_variant1_1499245187413",
            "name": "GIRLS HARTBREAK CREW",
            "quantity": "2",
            "price": "34.00",
            "currency": "EUR"
          },
          {
            "sku": "sku_SAPPHIRE_variant1_1499245187409",
            "name": "SAPPHIRE",
            "quantity": "3",
            "price": "28.00",
            "currency": "EUR"
          }
        ]
      }
    }
  ],
  "redirect_urls": {
    "return_url": "http://example.com/success/23456789",
    "cancel_url": "http://example.com/cancel/23456789"
  }
}'
  ``` 
  **Note** supplied _application_context_ and _payer_ fields

  The response works like expected (contains payer and application context fields):
  ```json
{
  "id": "PAY-6VB489398E948173CLJKMY6I",
  "intent": "sale",
  "state": "created",
  "payer": {
    "payment_method": "paypal"
  },
  "application_context": {
    "shipping_preference": "SET_PROVIDED_ADDRESS"
  },
  "transactions": [
    {
      "amount": {
        "total": "252.00",
        "currency": "EUR",
        "details": {
          "subtotal": "252.00",
          "shipping": "0.00"
        }
      },
      "description": "Payment from commercetools Paypal Plus integration service",
      "item_list": {
        "items": [
          {
            "name": "MB PREMIUM TECH T",
            "sku": "sku_MB_PREMIUM_TECH_T_variant1_1499245187441",
            "price": "100.00",
            "currency": "EUR",
            "quantity": 1
          },
          {
            "name": "GIRLS HARTBREAK CREW",
            "sku": "sku_GIRLS_HARTBREAK_CREW_variant1_1499245187413",
            "price": "34.00",
            "currency": "EUR",
            "quantity": 2
          },
          {
            "name": "SAPPHIRE",
            "sku": "sku_SAPPHIRE_variant1_1499245187409",
            "price": "28.00",
            "currency": "EUR",
            "quantity": 3
          }
        ]
      },
      "related_resources": []
    }
  ],
  "create_time": "2018-01-09T14:06:49Z",
  "links": [
    {
      "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-6VB489398E948173CLJKMY6I",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-6B865060K89368411",
      "rel": "approval_url",
      "method": "REDIRECT"
    },
    {
      "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-6VB489398E948173CLJKMY6I/execute",
      "rel": "execute",
      "method": "POST"
    }
  ]
}
```
e.g. created payment with id **`PAY-6VB489398E948173CLJKMY6I`** and it contains _payer_ and _application context_ info 
  
  2. (Optionally) Patch the payment **`PAY-6VB489398E948173CLJKMY6I`** supplying shipping/billing address:
  ```bash
curl --verbose --request PATCH 'https://api.sandbox.paypal.com/v1/payments/payment/PAY-6VB489398E948173CLJKMY6I' \
  --header "Authorization:Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" \
  --header "User-Agent:PayPalSDK/  (v=1.8.0_144; vendor=Oracle Corporation; bit=64; os=Mac_OS_X 10.13.2)" \
  --header "PayPal-Request-Id:f4efea9b-1e65-4352-b5e2-cc12344709bf" \
  --header "Content-Type:application/json" \
  --data '[
  {
    "op": "add",
    "path": "/transactions/0/item_list/shipping_address",
    "value": {
      "recipient_name": "Max Mustermann",
      "line1": "Kurfürstendamm 100",
      "city": "Berlin",
      "country_code": "DE",
      "postal_code": "10709"
    }
  },
  {
    "op": "add",
    "path": "/payer/payer_info",
    "value": {
      "email": "max.mustermann@gmail.com",
      "first_name": "Max",
      "last_name": "Mustermann",
      "billing_address": {
        "line1": "Kurfürstendamm 100",
        "city": "Berlin",
        "country_code": "DE",
        "postal_code": "10709"
      }
    }
  }
]'
  ```

  3. Get field by id **`PAY-6VB489398E948173CLJKMY6I`**:
  ```bash 
  curl --verbose --request GET 'https://api.sandbox.paypal.com/v1/payments/payment/PAY-6VB489398E948173CLJKMY6I' \
  --header "Authorization:Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" \
  --header "User-Agent:PayPalSDK/  (v=1.8.0_144; vendor=Oracle Corporation; bit=64; os=Mac_OS_X 10.13.2)" \
  --header "PayPal-Request-Id:fb625957-6ce7-4aba-836c-2b4fefb90022" \
  --header "Content-Type:application/json" 

{
  "id": "PAY-6VB489398E948173CLJKMY6I",
  "intent": "sale",
  "state": "created",
  "cart": "6B865060K89368411",
  "transactions": [
    {
      "amount": {
        "total": "252.00",
        "currency": "EUR",
        "details": {
          "subtotal": "252.00",
          "shipping": "0.00"
        }
      },
      "payee": {
        "merchant_id": "UFXRTPZUMKQ6C",
        "email": "andrii.kovalenko-facilitator@commercetools.com"
      },
      "description": "Payment from commercetools Paypal Plus integration service",
      "item_list": {
        "items": [
          {
            "name": "MB PREMIUM TECH T",
            "sku": "sku_MB_PREMIUM_TECH_T_variant1_1499245187441",
            "price": "100.00",
            "currency": "EUR",
            "quantity": 1
          },
          {
            "name": "GIRLS HARTBREAK CREW",
            "sku": "sku_GIRLS_HARTBREAK_CREW_variant1_1499245187413",
            "price": "34.00",
            "currency": "EUR",
            "quantity": 2
          },
          {
            "name": "SAPPHIRE",
            "sku": "sku_SAPPHIRE_variant1_1499245187409",
            "price": "28.00",
            "currency": "EUR",
            "quantity": 3
          }
        ]
      },
      "related_resources": []
    }
  ],
  "redirect_urls": {
    "return_url": "http://example.com/success/23456789?paymentId=PAY-6VB489398E948173CLJKMY6I",
    "cancel_url": "http://example.com/cancel/23456789"
  },
  "create_time": "2018-01-09T14:06:49Z",
  "update_time": "2018-01-09T14:06:52Z",
  "links": [
    {
      "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-6VB489398E948173CLJKMY6I",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-6VB489398E948173CLJKMY6I/execute",
      "rel": "execute",
      "method": "POST"
    },
    {
      "href": "https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-6B865060K89368411",
      "rel": "approval_url",
      "method": "REDIRECT"
    }
  ]
}
  ```

  **Notice**: _payer_,  _application context_ and _shipping address_ info are missing!

#### Expected behavior:
if payment is created/updated with _payer_, _experience profile id_, _application context_, _shipping address_ or any other info - it should be returned by GET endpoint as well (pretty same result as a response for create/update POST requests above)

Also, this issue might be related to https://github.com/paypal/PayPal-REST-API-issues/issues/180

**Comment by pp-randy** [comment]
Thank you for the good write up.  I am reviewing the issue currently.

**Comment by pp-randy** [comment]
Since I have not tested yet I will ask here.  Are the fields not being used at all after a patch, or just missing from the lookup?

**Comment by andrii-kovalenko-ct** [comment]
not sure what do you mean exactly, but i'm complaining for lookup (GET payment by ID) functionality: 
either after payment creation or (optionally) after payment patching some fields (created or patched) are missing in _GET payment by id_ response.

**Comment by pp-randy** [comment]
Once the buyer approves the payment I see the shipping address.  Can you confirm the same on your end?

**Comment by pp-randy** [comment]
Also payer and additional details become available after the payment is approved; this is prior to execute. 

If you set the Setting Address in the Create response, it will be available.   

Can you help me understand your use case, or correct me if this is not correct.  It appears you are adding a shipping address in a patch request prior to buyer approval and not providing it to the create payment call.  Why not provide the shipping address in the create call if this lookup is occurring prior to buyer approval?

**Comment by andrii-kovalenko-ct** [comment]
> Once the buyer approves the payment I see the shipping address. Can you confirm the same on your end?

yes, i reproduced this behavior: after payment approving shipping address becomes available.
Although, `experience_profile_id` and `application_context` still missing.

> If you set the Setting Address in the Create response, it will be available.
> Can you help me understand your use case, or correct me if this is not correct. It appears you are adding a shipping address in a patch request prior to buyer approval and not providing it to the create payment call. Why not provide the shipping address in the create call if this lookup is occurring prior to buyer approval?

**In common**:
  - in our integration test we are trying to verify the changes are applied: create/update payment and assert the created/updated fields making normal payment GET request.

**as for shipping address**:
  - the _Integrating PayPal PLUS_ Chapter _04. Payments_ says:
    > Required parameters:
    > - Name, shipping / billing and any other customer related data shall not be submitted here
but later by using PATCH Payment.

    So, we create payment and patch the address later, as recommended by the doc.

**as for _application_context_ and _experience_profile_id_**:
  - looks like they are not returned in get-by-id response either payment approved or not.

So, what we have to figure out now:
  - is it correct behavior that shipping address and payer info is hidden before the payment is approved by buyer?
  - why _application_context_ and _experience_profile_id_ are still missing?
  - do you have a sandbox API workaround for integration test, so we could verify the shipping address value without manual payment approval (redirecting to _approval_url_ and clicking _Weiter_ button)?

**Comment by pp-randy** [comment]
Is this the guide you are using?  https://www.paypalobjects.com/webstatic/de_DE/downloads/PayPal-PLUS-IntegrationGuide.pdf.  I'm going to need to follow up on the patching as I would expect the create to be used with your `application_content` indicating you are providing the address. 

> is it correct behavior that payer_info/shipping_address and payer info is hidden before the payment is approved by buyer?

If you provide the shipping address in the create it will be returned.  I will create a feature request since I agree it should show up on the lookup after patching. 

> why application_context and experience_profile_id are still missing?

I can submit a feature request for this, but can you help me understand why this is needed?  Are you running a validation against the lookup?  Regardless of the lookup missing the values, in testing I can see the settings added with `application_context` don't appear to change in the checkout flow even after a patch. 


> do you have a sandbox API workaround for integration test, so we could verify the shipping address value without manual payment approval (redirecting to approval_url and clicking Weiter button)?

I think you need to validate the shipping after buyer approval so you can ensure it is matching what you are expecting.

**Comment by andrii-kovalenko-ct** [comment]
> Are you running a validation against the lookup?

yes, exactly like this

> application_context don't appear to change in the checkout flow even after a patch. 

i supplied `application_context` on payment creation, and it actually changes checkout flow - a buyer can't change shipping address in the approval page. But `application_context` property is always missing in the response, either i create payment with it, or i patch the payment.

**Comment by pp-randy** [comment]
Using https://github.com/paypal/PayPal-REST-API-issues/issues/180 for the shipping address issue.

**Comment by pp-randy** [comment]
I have tagged this issue with tracking for adding the missing fields to the payment lookup.

**Comment by xiaoleih41** [comment]
the issue has been fixed. Close this issue.
