### ISSUE TITLE
"Billing plan updated" webhook data for "setup_fee" has incorrect value  on live but correct value on sandbox.

### ISSUE THREAD

**Issue by Billydwilliams** [paypal/PayPal-REST-API-issues#182]
> For internal bookkeeping: PPPLPAYPT-31977

Here are the merchant_prefrences After creating and then updating a $5 plan with a $5 dollar fee returns the following on live. Notice the 500. This has prevented me from setting our subscription options live for fear that our users will be mischarged 500 dollars instead of the 5.

```
"merchant_preferences": {
			"setup_fee": {
				"currency": "USD",
				"value": "500"
			},
			"auto_bill_amount": "YES",
			"max_fail_attempts": "1",
			"return_url": "https://********",
			"cancel_url": "https://********",
			"initial_fail_amount_action": "CANCEL"
		},
```

Here is what the sandbox returns using the exact same input from my end.
```

"merchant_preferences": {
			"setup_fee": {
				"currency": "USD",
				"value": "5"
			},
			"auto_bill_amount": "YES",
			"initial_fail_amount_action": "CANCEL",
			"max_fail_attempts": "1"
		},
```

**Comment by xiaoleih41** [comment]
Do you have a debug Id or the transaction ID associated with this webhook.  I will report this issue.

**Comment by xiaoleih41** [comment]
What about the transaction ID from the transaction history. Has the transaction completed? was it $5.00 or $500 transaction?

**Comment by pp-randy** [comment]
@xiaoleih41 my webhook for `BILLING.PLAN.UPDATED` gave me
```
"{"merchant_preferences":{"setup_fee":{"currency":"USD","value":"5"},"
```

**Comment by Billydwilliams** [comment]
Not sure if it makes a difference but I'm using the PHP SDK

**Comment by Billydwilliams** [comment]
Also heres my hook from creation, which shows the correct values
WH-3PW82298Y66691002-53G81113YF6430355

**Comment by Billydwilliams** [comment]
Ok just to be sure I updated my SDK version to latest. Still seems to be doing it to me on live but not on sandbox.

here are all the calls I made related to my most recent attempt
```

  | /v1/payments/billing-plans/P-6H740945PJ116330S4IV3N6A | f4ce6d3e1b26 | 10 Jan 2018 14:23:25
-- | -- | -- | --
  | /v1/payments/billing-agreements/ | 4aa9949586bdb | 10 Jan 2018 14:23:25
  | /v1/payments/billing-plans/P-6H740945PJ116330S4IV3N6A | dac3f80c64eaf | 10 Jan 2018 14:23:24
  | /v1/payments/billing-plans/ | 4ff38c30c91ca | 10 Jan 2018 14:23:23


```

**Comment by pp-randy** [comment]
@Billydwilliams the webhooks have `correlation-id` in the headers.  Can you snag that for the incorrect `BILLING.PLAN.UPDATED` updated webhook?

**Comment by Billydwilliams** [comment]
"Correlation-Id":"46279990d896d"

**Comment by pp-randy** [comment]
Thank you @Billydwilliams

**Comment by Billydwilliams** [comment]
Would it be safe for me to implement this as it is now? We do currently have users waiting to use the subscription feature, but we've been hesitant to implement it for fear people would be overcharged on the creation fee.  We are actually losing revenue due to this, so any ETA would be appreciated.

**Comment by pp-randy** [comment]
I have escalated this internally for further research.  I have no reports of a plan actually creating the wrong amount outside of this webhook example.  Are you changing the value of any internal plan information based on this patch webhook?

**Comment by xiaoleih41** [comment]
There's no other report has been filed to PayPal regarding wrong amounts so far.  If you want to make sure ,  is it possible for you to do a live testing from another live account you may have and  then cancel the subscription, refund the transaction amount?

**Comment by Billydwilliams** [comment]
Thanks for the quick responses both of you! Thats great to hear as we currently do not use it for anything other than a physical comparison for when someone submits a ticket to us.

**Comment by Billydwilliams** [comment]
K returning to confirm it does not overcharge, however any amount appears to be multiplied by 100 in the webhook.

**Comment by xiaoleih41** [comment]
Ok. Thank you for identifying that it's the webhook issue. Does this issue also show in the payment webhooks as well?

**Comment by Billydwilliams** [comment]
Everything looks correct everywhere else.

**Comment by pp-randy** [comment]
Thanks both, I was able to determine the amounts were all incorrect based on the logging, this issue has been escalated internally.  I will update when more information is available regarding this webhook.

**Comment by pp-randy** [comment]
@Billydwilliams the fix for this should be available on live.  Please let us know if you still receive an invalid amount.

**Comment by xiaoleih41** [comment]
Close this issue as it's solved.
