### ISSUE TITLE
UNKNOWN_ERROR

### ISSUE THREAD

**Issue by VSilantyev** [paypal/PayPal-REST-API-issues#183]
> For internal Tracking: PPPLPAYPT-31890

* Environment: Production
* `PayPal-Debug-ID` values: e5f5248ca7831, ea73ea3ec7aae, 4adcf597c9e0a
* Language, language version, and OS: PHP7 on Ubuntu 16.10

### Issue description

We are trying to bill credit cards saved in vault and for some cards we are receiving errors like:
`
{"name":"UNKNOWN_ERROR","message":"An unknown error occurred.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"4adcf597c9e0a"}
`
Most of the saved cards are billed fine, the error is returned for about 5% of saved cards.

Could you lookup by debug ids, what does UNKNOWN_ERROR means?

**Comment by xiaoleih41** [comment]
This is what I have got from the back end ""This transaction cannot be processed. Please enter a valid credit card expiration year." I will report this issue as it should show a more specific error message.

**Comment by VSilantyev** [comment]
Thanks for quick response, indeed, checked with
`
 curl -v -X GET https://api.paypal.com/v1/vault/credit-cards/CARD-xxx
`
It is expired.

**Comment by xiaoleih41** [comment]
This has been fixed. Please test and let us know if it's not fixed.
