### ISSUE TITLE
invoice["metadata"]["payer_view_url"] is missing

### ISSUE THREAD

**Issue by zshimanchik** [paypal/PayPal-REST-API-issues#186]
### General information

* Environment: Production
* Language, language version, and OS: Python 3.6 on ubuntu 16.04

### invoice["metadata"]["payer_view_url"] is missing on production

Current program implementation that worked but stopped since Jan. 12, 2018:
- create invoice
- send invoice
- fetch again (find by id)
- retrieve invoice url for user: `return invoice["metadata"]["payer_view_url"]`

But there is no `payer_view_url` in `metadata`
Last successfully created invoice using this method: Jan. 12, 2018, 4:09 p.m. UTC
First invoice with issue: Jan. 12, 2018, 8:54 p.m. UTC

There is no such issue in sandbox. 
This ticket is urgent, because it is on production.

**Comment by xiaoleih41** [comment]
Have you filed a support ticket at www.paypal-techsupport.com?

**Comment by xiaoleih41** [comment]
can you give me some debug ID and file a ticket with www.paypal-techsupport.com and give me the ticket number.

**Comment by pp-randy** [comment]
Closing this issue as direction to contact [Technical Support](https://www.paypal-techsupport.com/app/ask/) has been provided.  It is best to work with them when things are urgent and impact your Production integration.
