### ISSUE TITLE
500 being thrown on GET /v1/checkout/orders/{order_id}

### ISSUE THREAD

**Issue by Kazanz** [paypal/PayPal-REST-API-issues#188]
### General information

* Environment: <b>Production</b>
* `PayPal-Debug-ID` values: <b>15389775e0a29</b> & <b>630e19e6c2428</b>
* Language, language version, and OS:

Two envs:
-<b>Python 3.5.4</b> on <b>Alpine 3.4.6</b>
-<b>Using curl</b> on <b>OSX 10.13.2 </B> 

### Issue description

Whenever hitting the order get endpoint: https://developer.paypal.com/docs/api/orders/#orders_get 

a 500 is returned with no error messages.  The Authorization token used works on the other rest api endpoints, and these calls were working yesterday at 4pm.

**Comment by xiaoleih41** [comment]
As it's a production issue, can you submit a support ticket at www.paypal-techsupport.com providing your PayPal account info so that they can prioritize and report the issue?

**Comment by Kazanz** [comment]
I did.  Seems they have fixed the issue.  Thanks.
