### ISSUE TITLE
PayPal Sync API is poorly documented

### ISSUE THREAD

**Issue by cschramm** [paypal/PayPal-REST-API-issues#189]
Some rather obvious things I stumbled upon while playing with that (new?) API:

Third party permissions: The Integration Guide states "If you are a partner or a third party, you must get third-party permissions from the merchant to use the API on behalf of the merchant." but does not state which permissions and how to get them. Trying the API call without that permission results in an error with `informationLink` https://developer.paypal.com/docs/classic/products/permissions/. I did not find a way to use permissions granted via that *classic* Permissions API for a REST API call. The `X-PP-AUTHORIZATION` headers seems to have no effect there. Also, one would have to guess which permission to request for which call.

Required query parameters: The service states that either `start_date` and `end_date` or `transaction_id` need to be specified. Seems undocumented. The documentation states "If you specify query parameters, the `ending_balance` field does not contain a value.". In practice it seems impossible to *not* specify query parameters. Anyway, `ending_balance` *does* contain a value for me, so the note seems to be just wrong. Later notes mention a `transaction_date` parameter that does not exist, or at least, is not documented.

`start_date` seems to be inclusive, `end_date` seems to be exclusive.

Relation between `start_date` and `end_date`: The service states that you cannot only provide one of them and the difference can be at most 31 days.

`start_date` limitations: The PayPal website allows me to go back three years. The API has a couple of additional, intransparent limits: There seems to be a minimum `start_date` before which the API returns an error. This is `2015-03-19 06:30:00+0000` (for my client application; might differ of course). I have no idea why. Additionally, there's a date before which no transactions get returned somewhere between 2016-07-04 and 2016-07-09.

Data quirks: There are some issues in the data, e.g. a lot of old transactions still have state pending (so that state seems to be completely unreliable). Ideally such things should get some documentation too, so that developers do not have to find it out by themselves.

`transaction_info`: In the documentation for `transaction_info`, some fields are marked as `required`. Most of them are fields that are definitely *not* present in all cases. It seems to be just the other way around.

...

**Comment by haukepribnow** [comment]
To add:

The documentation specifies that the object `payer_info`'s field `payer_status` may either be `Verified` or `Unverified`.

The field **actually** contains `Y` or `N` however.

**Comment by haukepribnow** [comment]
To further add:

[The documentation says](https://developer.paypal.com/docs/integration/direct/sync/): "The maximum `page_size` value is `500`. [...] The maximum number of records in a single request is 10,000."

The documentation is not clear on what happens if `page_size` is not set. Will it return 10,000 `transaction_detail`s? Or will it still only return 500 at most, counting each child object of `transaction_detail` as a "record"?

**Comment by xiaoleih41** [comment]
We are looking into all issues and will get back and address the questions one by one.

**Comment by xiaoleih41** [comment]
@cschramm I am looking into the rest of your question. However 3rd party permission will be a restricted feature upon approval. It is not available for general public. You may have to contact your PayPal account manager to apply for this feature.

**Comment by xiaoleih41** [comment]
@haukepribnow  If you don't define the page size, the default will be 100. 
page_size integer
The number of items to return in the response. So, the combination of page=0 and page_size=20 returns the first 20 items. The combination of page=20 and page_size=20 returns the next 20 items.
Default: 100.

**Comment by xiaoleih41** [comment]
Close this issue as the documentation has been updated based on the recommendation.

**Comment by alexey-pelykh** [comment]
How to get `ending_balance` of the requested time period? + `end_date` seems to be pretty inclusive to me
