### ISSUE TITLE
Sync API - Clarify Third Party Permission Process

### ISSUE THREAD

**Issue by pp-randy** [paypal/PayPal-REST-API-issues#193]
> For Internal Bookkeeping: PPPLMER-45222

The process for how to get third party access for Sync API is unclear in the documentation. 

[PayPal Sync API Integration Guide](https://developer.paypal.com/docs/integration/direct/sync/)

> If you are a partner or a third party, you must get third-party permissions from the merchant to use the API on behalf of the merchant.

**Comment by pp-randy** [comment]
Access to the third party feature requires being part of the partner program https://www.paypal.com/us/webapps/mpp/partner-program

The documentation will be updated to reflect this information.

**Comment by xiaoleih41** [comment]
Close this issue as it has been solved.

**Comment by m0bi5** [comment]
I am currently a paypal partner but yet I cannot find any documentation as to how one can access a third party account's transactions. I have seen the transaction search REST API and also seen the permissions NVP API. Is there any way to combine these two?
