### ISSUE TITLE
Empty response returned by paypal api

### ISSUE THREAD

**Issue by hidnarola** [paypal/PayPal-REST-API-issues#194]
I have made call to "https://api.sandbox.paypal.com/v1/payments/payment" api, and it returns empty response for sandbox api call.

I am using following code for php

$card_id = XXXXXXXXXX
$payer_id = XXXXXXXXXXXX
$data1 = array(
        "intent" => 'sale',
        "payer" => array(
            "payment_method" => 'credit_card',
            "funding_instruments" =>
				array(0 => array(
                    "credit_card_token" => array(
                        "credit_card_id" => $card_id,
                        "payer_id" => $payer_id
                    )
                )
            )
        ),
        "transactions" => array(
		0 => array(
                "amount" => array(
                    "total" => "01.00",
                    "currency" => "USD",
                ),
                "description" => "Test Transaction created."
            )
        ),
    );
	
	
$json = json_encode($data1);

    $ch3 = curl_init();
    curl_setopt($ch3, CURLOPT_URL, "https://api.sandbox.paypal.com/v1/payments/payment");
    curl_setopt($ch3, CURLOPT_USERPWD, 'CLIENT ID:CLIENT SECRET');
    curl_setopt($ch3, CURLOPT_HTTPHEADER, array("Content-Type: application/json",
        "Authorization: Bearer " . $access_token,
            )
    );
    curl_setopt($ch3, CURLOPT_POST, true);
    curl_setopt($ch3, CURLOPT_FOLLOWLOCATION, true);
    curl_setopt($ch3, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch3, CURLOPT_POSTFIELDS, $json);
    curl_setopt($ch3, CURLOPT_RETURNTRANSFER, true);
    $result22 = curl_exec($ch3);

**Comment by pp-randy** [comment]
Are you supporting an existing production integration or are you approved for direct credit card processing with the REST API on live?  Support for direct credit card processing is restricted and new integrations should review our Braintree offerings https://www.braintreepayments.com.  

On the other hand, if you are supporting an existing integration.  Did you get an error?  Are you able to provide the `paypal-debug-id` response header value?

**Comment by hidnarola** [comment]
Yes. I am getting debug id d333f9e630760. Please check with below url.

![debug_id](https://user-images.githubusercontent.com/7344384/35605262-a2f1e88e-066d-11e8-93e9-276bb75adc38.PNG)

**Comment by xiaoleih41** [comment]
For certain over used sandbox credit card numbers, you will get internal error. As the credit card feature has been deprecated in PayPal. no more new application will be accept or approved. Please look into Braintree SDK integration instead at www.brantreepayments.com. Braintree SDK supports both PayPal and credit card  processing.

**Comment by xiaoleih41** [comment]
Close due to inactivity. Please resubmit when you have additional information.
