### ISSUE TITLE
Is Sync API supposed to list non-REST transactions?

### ISSUE THREAD

**Issue by julienma** [paypal/PayPal-REST-API-issues#202]
### General information

* Environment: Sandbox
* `PayPal-Debug-ID` values: n/a
* Language, language version, and OS: curl on macOS 10.13.3

### Issue description

We're trying the [Sync API](https://developer.paypal.com/docs/api/sync/), hoping that it can help us list *all* transactions, including the ones not created through REST API (e.g. the javascript buttons).
Unfortunately it seems it doesn't solve this issue.

We have some transactions on our Live account:

<img width="826" alt="screen shot 2018-02-14 at 18 20 12" src="https://user-images.githubusercontent.com/201897/36218275-18a866ec-11b4-11e8-8a8d-5f167920b9be.png">

We're trying to list them:

```
curl -v -X GET https://api.paypal.com/v1/reporting/transactions?fields=all&page_size=100&page=1&start_date=2017-02-01T00:00:00Z&end_date=2017-02-20T00:00:00Z \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer [BEARER_TOKEN]"
```

Unfortunately we don't get any transaction:

```
{"transaction_details":[],"account_number":"[ACCOUNT_NUMBER]","start_date":"2017-02-01T00:00:00+0000","end_date":"2017-02-20T00:00:00+0000","last_refreshed_datetime":"2018-02-14T13:59:59+0000","page":1,"total_items":0,"total_pages":0,"links":[{"href":"https://api.paypal.com/v1/reporting/transactions?fields=all&start_date=2017-02-01T00%3A00%3A00Z&end_date=2017-02-20T00%3A00%3A00Z&page_size=100&page=1","rel":"self","method":"GET"}]}
```

Are we doing anything wrong?
Or should we forget the idea that we can use some REST API to list all transactions, and use the NVP API?

Thanks

**Comment by xiaoleih41** [comment]
It should not matter. the sync API should be able to list all transactions. Can you search by the transactionId? It takes around 2 hours for the info available for sync API to query.

**Comment by julienma** [comment]
Oh, that must explain it then: our test transactions were made a few minutes before.
We'll test again.

In any case, a 2 hours lag is too much for what we want to do, so we'll probably stick with the NVP API for now.
BTW, does the NVP API also have any lag when listing transactions?

**Comment by julienma** [comment]
@xiaoleih41 we tested again, and even though the transactions are more than 1d old, we can't see them:

```
curl -v -X GET https://api.paypal.com/v1/reporting/transactions?fields=all&page_size=100&page=1&start_date=2017-02-01T00:00:00Z&end_date=2017-02-20T00:00:00Z \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer [BEARER_TOKEN]"
```

Output:

```
{"transaction_details":[],"account_number":"[ACCOUNT_NUMBER]","start_date":"2017-02-01T00:00:00+0000","end_date":"2017-02-20T00:00:00+0000","last_refreshed_datetime":"2018-02-15T13:29:59+0000","page":1,"total_items":0,"total_pages":0,"links":[{"href":"https://api.paypal.com/v1/reporting/transactions?fields=all&start_date=2017-02-01T00%3A00%3A00Z&end_date=2017-02-20T00%3A00%3A00Z&page_size=100&page=1","rel":"self","method":"GET"}]}
```

**Comment by xiaoleih41** [comment]
You may put the year to 2018 instead.

**Comment by julienma** [comment]
😭 
Will try, thanks :D

**Comment by xiaoleih41** [comment]
Hope it helps. Please close the issue if it has been solved.

**Comment by julienma** [comment]
I can confirm this solves the issue.
We won't use it though, because of the 2h delay, but we'll keep an eye should the delay decrease by a lot.
Thanks again!
