### ISSUE TITLE
Reference Transactions / Subscriptions with german buyers

### ISSUE THREAD

**Issue by PKuebler** [paypal/PayPal-REST-API-issues#203]
Hi,

Is there any way to make regular debits in Germany?

The documentation and other posts said:

https://developer.paypal.com/webapps/developer/docs/classic/express-checkout/integration-guide/ECRecurringPayments/#limitations

> Recurring payments cannot be created for buyers in Germany or China. In this case, you can use reference transactions as an alternate solution.

It is recommended to work with Reference Transactions. In addition I find only something in the Classic API and as Deprecated marked.

https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECReferenceTxns/

> Express Checkout - NVP/SOAP (Deprecated)

greets,
philipp

**Comment by xiaoleih41** [comment]
Close this issue as the suggestion as been made.
