### ISSUE TITLE
Userinfo fields firstName, lastName are not populated anymore

### ISSUE THREAD

**Issue by tuberains** [paypal/PayPal-REST-API-issues#205]
>For internal tracking: PPPLPAYPT-34126

### General information

* Environment: Sandbox && Production
* `PayPal-Debug-ID` values: irrevelant
* Language, language version, and OS:  irrevelant

### Issue description

The identity API does not deliver the fields `firstName` and `lastName` (maybe also `middleName`) anymore. The name is only delivered through the `name` field.
All this happens in contrast to the [documenation](https://developer.paypal.com/docs/api/identity/#openidconnect_userinfo_response).

[This Stackoverflow Question](https://stackoverflow.com/questions/48638892/paypal-userinfo-does-not-return-user-first-and-last-name) further describes the problem.

I could not find relevant entries in the changelog.

**Comment by xiaoleih41** [comment]
I have reported this issue and will update this issue if there's any additional info.

**Comment by xiaoleih41** [comment]
I was told that it's a known issue.  Due to certain regulation, we do provide case by case fix on this. Please contact developer.paypal.com/support  and provide your client Id of your app and request to turn on the fileds.

**Comment by xiaoleih41** [comment]
Close as the solution has been provided.
