### ISSUE TITLE
Can't set Payer_Info country or phone

### ISSUE THREAD

**Issue by AlanMenhennet** [paypal/PayPal-REST-API-issues#208]
### General information

* Environment: Sandbox
* `PayPal-Debug-ID` values: 48d879102f339
* Language, language version, and OS: Java 1.8 on Windows 7

### Issue description

When trying to set a country code, or phone number on PayerInfo via the Java SDK, when I call payment.create() I get the following response 

{"name":"MALFORMED_REQUEST","message":"Incoming JSON request does not map to API request","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST","debug_id":"48d879102f339"}

I've scoured the docs and can't see why the country code or phone number cause this error. I can set the first name, last name, email succesfully.

Here's my request as serialized by the Java SDK. What I'm trying to achieve is prefilling the details for guest checkout.

{
  "intent": "sale",
  "payer": {
    "payment_method": "paypal",
    "payer_info": {
      "email": "john@doe.com.au",
      "first_name": "John",
      "last_name": "Doe",
      "country_code": "AU",
      "billing_address": {
        "phone": "1300123123",
        "line1": "1 Test St",
        "city": "Testville",
        "country_code": "AU",
        "postal_code": "3000",
        "state": "VIC"
      }
    }
  },
  "transactions": [
    {
      "amount": {
        "currency": "AUD",
        "total": "45.55",
        "details": {
          "subtotal": "35.00",
          "shipping": "10.55",
          "tax": "0"
        }
      },
      "description": "",
      "note_to_payee": "Sent via Australia Post Domestic Parcel Post",
      "custom": "Sent via Australia Post Domestic Parcel Post",
      "item_list": {
        "items": [
          {
            "name": "Beige knitted peaked Cap - small - C0020",
            "quantity": "1",
            "price": "35.00",
            "currency": "AUD"
          }
        ],
        "shipping_address": {
          "recipient_name": "John Doe",
          "phone": "1300123123",
          "line1": "1 Test St",
          "city": "Testville",
          "country_code": "AU",
          "postal_code": "3000",
          "state": "VIC"
        },
        "shipping_method": "Sent via Australia Post Domestic Parcel Post",
        "shipping_phone_number": "123"
      }
    }
  ],
  "redirect_urls": {
    "return_url": "http://www.test.com.au/shop/category/bag/176",
    "cancel_url": "http://www.test.com.au/shop/category/bag/176"
  }
}

**Comment by xiaoleih41** [comment]
When you choose `country_code`, you will need to include `post_code` as well.

**Comment by AlanMenhennet** [comment]
the Java SDK doesn't have a field for post code on PayerInfo, nor does the API docs reference post code on payer info https://developer.paypal.com/docs/api/payments/#definition-payer_info

What object do I set post code on?

I took a guess and set it on billing address using the following POST, and I got the same error, debug reference is 4565feb0e2bce

{
  "intent": "sale",
  "payer": {
    "payment_method": "paypal",
    "payer_info": {
      "email": "test@test.com.au",
      "first_name": "John",
      "last_name": "Doe",
      "phone": "1300123123",
      "phone_type": "MOBILE",
      "country_code": "AU",
      "billing_address": {
        "phone": "1300123123",
        "line1": "1 Test St",
        "city": "TestVille",
        "country_code": "AU",
        "postal_code": "3000",
        "state": "VIC"
      }
    }
  },
  "transactions": [
    {
      "amount": {
        "currency": "AUD",
        "total": "45.55",
        "details": {
          "subtotal": "35.00",
          "shipping": "10.55",
          "tax": "0"
        }
      },
      "description": "",
      "note_to_payee": "Sent via Australia Post Domestic Parcel Post",
      "custom": "Sent via Australia Post Domestic Parcel Post",
      "item_list": {
        "items": [
          {
            "name": "Beige knitted peaked Cap - large - C0022",
            "quantity": "1",
            "price": "35.00",
            "currency": "AUD"
          }
        ],
        "shipping_address": {
          "recipient_name": "John Doe",
          "phone": "1300123123",
          "line1": "1 Test St",
          "city": "TestVille",
          "country_code": "AU",
          "postal_code": "3000",
          "state": "VIC"
        },
        "shipping_method": "Sent via Australia Post Domestic Parcel Post",
        "shipping_phone_number": "123"
      }
    }
  ],
  "redirect_urls": {
    "return_url": "http://www.test.com.au/shop/category/bag/176",
    "cancel_url": "http://www.test.com.au/shop/category/bag/176"
  }
}

**Comment by xiaoleih41** [comment]
don't pass on the `country_code` at the **payerInfo** level. it should work.

**Comment by AlanMenhennet** [comment]
I was able to create the payment, but the country is not filled in when checking out as guest. See request and screenshot

{
  "intent": "sale",
  "payer": {
    "payment_method": "paypal",
    "payer_info": {
      "email": "test@test.com",
      "first_name": "John",
      "last_name": "Doe",
      "billing_address": {
        "phone": "1300121231",
        "line1": "1 Test Street",
        "city": "Testville",
        "country_code": "AU",
        "postal_code": "3000",
        "state": "VIC"
      }
    }
  },
  "transactions": [
    {
      "amount": {
        "currency": "AUD",
        "total": "35.00",
        "details": {
          "subtotal": "35.00",
          "shipping": "0.00",
          "tax": "0"
        }
      },
      "description": "",
      "note_to_payee": "Sent via  ",
      "custom": "Sent via  ",
      "item_list": {
        "items": [
          {
            "name": "Beige knitted peaked Cap - C002",
            "quantity": "1",
            "price": "35.00",
            "currency": "AUD"
          }
        ],
        "shipping_address": {
          "recipient_name": "John Doe",
          "phone": "1300121231",
          "line1": "1 Test Street",
          "city": "Testville",
          "country_code": "AU",
          "postal_code": "3000",
          "state": "VIC"
        },
        "shipping_method": "Sent via  ",
        "shipping_phone_number": "123"
      }
    }
  ],
  "redirect_urls": {
    "return_url": "http://www.thomasthetemplateengine.com.au/comma-comma",
    "cancel_url": "http://www.thomasthetemplateengine.com.au/comma-comma"
  }
}
![image](https://user-images.githubusercontent.com/7446065/36567751-a715840a-187b-11e8-8064-b1a02254b1d9.png)

**Comment by xiaoleih41** [comment]
You should specify the `locale code` instead.  You can set it up inside of [application context object](https://developer.paypal.com/docs/api/orders/#definition-application_context)

**Comment by AlanMenhennet** [comment]
The application context object you linked me to refers to the Orders API, I'm using the Payments API, unless I've missed an application context in the payments API?

**Comment by xiaoleih41** [comment]
Order API is the direction that REST API is taking going forward. You can consider to switch to that or you can set up `locale_code` within a web experience profile [presentation](https://developer.paypal.com/docs/api/payment-experience/#definition-presentation) object and refer the [`experience_profile_id](https://developer.paypal.com/docs/api/payments/#payment_create) when you submit the payment and it will set the country for you as well.

**Comment by AlanMenhennet** [comment]
Thanks for the reply. This was an inherited project and we thought it may have been setup wrong.

I'll look at moving to the order API

**Comment by vincentwinkel** [comment]
I don't know if it's the same error, but the `country_code` doesn't seem working for me, using node-paypal.
Here is my payload:

```
paypal.payment.create({
    "intent": "sale",
    "payer": {
        "payment_method": "paypal",
        "payer_info": {
            "email": "vincent@lusinealunettes.com",
            "billing_address": {
                "line1": "1 rue aa",
                "city": "lauzerville",
                "country_code": "FR",
                "postal_code": "31650"
            }
        }
    },
    "redirect_urls": {
        "return_url": ".....",
        "cancel_url": "....."
    },
    "transactions": [{
        "amount": {
            "total": 34.99,
            "currency": "EUR"
        },
        "item_list": {
            "shipping_address": {
                "recipient_name": "f f",
                "line1": "1 rue aa",
                "city": "lauzerville",
                "country_code": "FR",
                "postal_code": "31650"
            }
        }
    }]
});
```
But no matter my tries, it still stays stuck on United States as country, as follows:

<img width="440" alt="Screen Shot 2019-04-23 at 12 49 07" src="https://user-images.githubusercontent.com/1402505/56575586-5fff2f00-65c6-11e9-8176-f59caedcb1f0.png">
