### ISSUE TITLE
Internal Server Error on payout

### ISSUE THREAD

**Issue by nitinpund** [paypal/PayPal-REST-API-issues#209]
### General information

* Environment: Sandbox
* `PayPal-Debug-ID` values: f8fb0832d291b
* Language, language version, and OS: Centos 7

### Issue description
 From last two days we are facing this issue on sandbox while making credit card payments using sandbox

**Comment by xiaoleih41** [comment]
Credit card payments feature have been deprecated.  No more new integration will be approved for processing. Please consider to look into Braintree SDK instead.

**Comment by xiaoleih41** [comment]
Close this issue as it's regarding a deprecated product feature.
