### ISSUE TITLE
The remote server returned an error: (500) Internal Server Error.

### ISSUE THREAD

**Issue by ctallos** [paypal/PayPal-REST-API-issues#210]
Could anyone help with this? Using the most recent version of PayPal sdk
{paypal-debug-id: 82e9a35334a3d,82e9a35334a3d
Content-Language: *
X-SLR-RETRY: 500
X-SLR-RETRY-API: /v1/payments/payment
Connection: close
HTTP_X_PP_AZ_LOCATOR: sandbox.slc
Date: Sun, 04 Mar 2018 06:19:21 GMT
Set-Cookie: X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dapiplatformproxyserv%26TIME%3D3918502746%26HTTP_X_PP_AZ_LOCATOR%3Dsandbox.slc; Expires=Sun, 04 Mar 2018 06:49:51 GMT; domain=.paypal.com; path=/; Secure; HttpOnly,X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
Server: Apache
Vary: Authorization
Content-Length: 184
Content-Type: application/json}
{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"82e9a35334a3d"}
### General information

Chrome 63, Windows 10, 
### Issue description

Occurs at this line
try
            {
                APIContext apiContext = Extensions.Configuration.GetApiContext();
                Payment createdPayment = pymnt.Create(apiContext); <-----------------

**Comment by xiaoleih41** [comment]
Please close this case and open this issue under the SDK you were using.
