### ISSUE TITLE
Unsupported timezone offets for the 'transactions' (sync api). Any postive offset causes error 400

### ISSUE THREAD

**Issue by iliepandia** [paypal/PayPal-REST-API-issues#211]
> For internal tracking: PPPLPAYPT-35003

### General information

* Environment: Production
* `PayPal-Debug-ID` values: none show up in the web UI
* Language, language version, and OS: Official PHP SDK on PHP7.0

### Issue description

Hello, 

This works fine:

`/v1/reporting/transactions?start_date=2018-01-01T11:04:22Z&end_date=2018-01-02T00:00:00Z&fields=all&page_size=2&page=1`

This however gives error `400`

`/v1/reporting/transactions?start_date=2018-01-01T11:04:22+0000&end_date=2018-01-02T00:00:00+0000&fields=all&page_size=2&page=1`

This works fine (just changing the `+` in a` -` in the timezone area)

`/v1/reporting/transactions?start_date=2018-01-01T11:04:22-0000&end_date=2018-01-02T00:00:00-0000&fields=all&page_size=2&page=1`

This works:

`/v1/reporting/transactions?start_date=2018-01-01T11:04:22-0200&end_date=2018-01-02T00:00:00-0200&fields=all&page_size=2&page=1`

But positive offset fails with code `400`

`/v1/reporting/transactions?start_date=2018-01-01T11:04:22+0200&end_date=2018-01-02T00:00:00+0200&fields=all&page_size=2&page=1`

**Comment by xiaoleih41** [comment]
Thank you for pointing it out. I have reported this issue.

**Comment by xiaoleih41** [comment]
Close this issue as the issue has been solved.
