### ISSUE TITLE
An unknown error occurred

### ISSUE THREAD

**Issue by kevin-jj** [paypal/PayPal-REST-API-issues#212]
> For internal tracking: PPPLPAYPT-35062

### General information

* Environment: Sandbox
* `PayPal-Debug-ID` values: "274a4d2234f33"
* Language, language version, and OS: Ruby, ruby 2.5.0, Mac OS

### Issue description

I received a "An unknown error occurred" error message with direct CreditCard payment. The credit card number is generated by a new buyer account. 

Response.body={"name":"UNKNOWN_ERROR","message":"An unknown error occurred.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"274a4d2234f33"}	Response.header={"date"=>["Tue, 13 Mar 2018 03:04:44 GMT"], "server"=>["Apache"], "paypal-debug-id"=>["274a4d2234f33", "274a4d2234f33"], "content-language"=>["*"], "connection"=>["close"], "http_x_pp_az_locator"=>["sandbox.slc"], "set-cookie"=>["X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dapiplatformproxyserv%26TIME%3D3426723674%26HTTP_X_PP_AZ_LOCATOR%3Dsandbox.slc; Expires=Tue, 13 Mar 2018 03:34:50 GMT; domain=.paypal.com; path=/; Secure; HttpOnly", "X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT"], "vary"=>["Authorization"], "content-length"=>["166"], "content-type"=>["application/json"]}
{"name"=>"UNKNOWN_ERROR", "message"=>"An unknown error occurred.", "information_link"=>"https://developer.paypal.com/docs/api/payments/#errors", "debug_id"=>"274a4d2234f33"}

**Comment by AshleyPi1409** [comment]
**General information**
Environment: Sandbox
PayPal-Debug-ID values: "5eecc6e3b48c4"
Language, language version, and OS: JS, NodeJS 7.8, Mac OS

Same issue, with direct CreditCard payment.

**Comment by kytwb** [comment]
Same issue observed today in my recurring tests for [42-cent-paypal](https://github.com/continuous-software/42-cent-paypal). I guess this is a real unknown error on the side of Paypal and should come back up shortly.

**Comment by xiaoleih41** [comment]
I have reported this issue. However PayPal has deprecated direct credit card processing feature for REST API and REST SDK. No more live credential will be approved on this feature. Unless you have already got live feature approved, please consider to switch to braintree SDK instead. It supports both PayPal and credit card payment methods.

**Comment by kevin-jj** [comment]
What is live feature?

**Comment by xiaoleih41** [comment]
@kevin-jj Allowing you to processing credit card in production environment not just sandbox.

**Comment by kevin-jj** [comment]
How can we apply for live feature?

**Comment by kytwb** [comment]
My tests are now passing again.

**Comment by kevin-jj** [comment]
direct credit card payment? @kytwb

**Comment by kytwb** [comment]
@kevin-jj think so yeah; tests are openly available [here](https://travis-ci.org/continuous-software/42-cent-paypal) and code in the associated repository.

**Comment by kevin-jj** [comment]
@kytwb  Since direct credit card re-work well in Sandbox for now, I am wonder that whether PayPal continue to add support to it in Production?  If NOT, what's the timeline to drop support in production?

Thanks.

**Comment by xiaoleih41** [comment]
I don't think  you can apply anymore.  It used to have a link inside of  your developer.paypal.com account. Please contact customer service to confirm if there's a way to apply first before proceeding the integration.

**Comment by xiaoleih41** [comment]
Close the issue as it's a deprecated feature.
