### ISSUE TITLE
[question] Is a payment ever deleted?

### ISSUE THREAD

**Issue by KayakinKoder** [paypal/PayPal-REST-API-issues#215]
>for internal tracking: PPPLMER-49057

The docs for the endpoint `/v1/payments/payment/{payment_id}` state

> Shows details for a payment, by ID, **that has yet to complete**.

We are setting up a basic integration via express checkout server api (payment -> sale is the only use case for us) and I was hoping to use the payment id as a unique identifier. I'd like to be able to check the status of the sale months, even years in the future, using the payment id but this sentence in the docs has me worried.

- What does this sentence in the docs mean, I have not seen anything about payments "completing" anywhere else in the docs?
- Are payments ever deleted, even years in the future?
- Are we safe in using payment id as our main way of identifying user purchases, or should we get the sale id and use that instead?

Thanks for your time.

**Comment by xiaoleih41** [comment]
**sale id** is the ID for a completed transaction. **payment Id** is the id before the payment is executed.

**Comment by KayakinKoder** [comment]
@xiaoleih41 thanks yes I do see that. This fact still leaves most of my questions unanswered.

**Comment by xiaoleih41** [comment]
If the payment was completed the paymentID should be kept with the record. You can always query it later. If the payment was not executed successful. the paymentID will not be kept.

**Comment by KayakinKoder** [comment]
Thanks. Are payment ids guaranteed to be unique, even ones that are deleted?

Example:
id: PAY-123   (this payment never completes, so is eventually deleted? from your system)

Is it guaranteed that no payment with id PAY-123 will ever be created again? This is important as we are trying to figure out what we can use as an absolute unique identifier.

**Comment by KayakinKoder** [comment]
@xiaoleih41 what's the best method to get our questions answered in a timely fashion? I have submitted a ticket to support, no response. Asked here 8 days ago. For the amount of money we've sent Paypal's way over the years, I'm astounded I cannot get faster support. We are considering switching our main payment system to Stripe because we simply cannot use Paypal's API due to lack of basic documentation + lack of support. Stripe on the other hand has answered our questions in less than 12 hours, every time.

**Comment by xiaoleih41** [comment]
@KayakinKoder I am following up again and get the answer to you soon.

**Comment by xiaoleih41** [comment]
I do not find documentations on this specific information. I have submitted a documentation update on this. Based on the discussion I had with internal team, the paymentID is unique regardless the payment is completed or not.

**Comment by xiaoleih41** [comment]
@KayakinKoder It's confirmed that the Payment ID is always unique and stored in our system. It will not be deleted.
