### ISSUE TITLE
Billing Agreement Execute causing 500 error

### ISSUE THREAD

**Issue by jvjvjv** [paypal/PayPal-REST-API-issues#219]
### General information

* Environment: Sandbox
* `PayPal-Debug-ID` values: n/a
* Language, language version, and OS: HTTP/JSON & Postman, N/A, Mac OS X High Sierra

### Issue description

Using Postman, I'd created a series of API calls based on the developer documentation, to see if I can get a Payment Agreement ID to send to Express Checkout.

Spoiler alert: I couldn't.

But, what I had done when I created my Billing Agreement, was use the approval_url to allow the user to approve. At the return, I used the EC token in the next API call, and I received a 500 error, with no other response.

**Comment by jvjvjv** [comment]
*Billing Agreement Request: * POST https://api.sandbox.paypal.com/v1/payments/billing-agreements/

`{
    "description": "PayPal payment agreement",
    "name": "Billing Agreement",
    "payer": {
        "payment_method": "paypal"
    },
    "plan": {
        "id": "P-2N576876CS3547245SZ6CHVI"
    },
    "start_date": "2018-04-18T00:00:00Z"
}`

*Response:*
`{
    "name": "Billing Agreement",
    "description": "PayPal payment agreement",
    "plan": {
        "id": "P-2N576876CS3547245SZ6CHVI",
        "state": "ACTIVE",
        "name": "Plan with Regular and Trial Payment Definitions",
        "description": "Plan with regular and trial payment definitions.",
        "type": "INFINITE",
        "payment_definitions": [
            {
                "id": "PD-0BA36519V8647940USZ6CHVI",
                "name": "Regular payment definition",
                "type": "REGULAR",
                "frequency": "Month",
                "amount": {
                    "currency": "USD",
                    "value": "7.99"
                },
                "cycles": "0",
                "charge_models": [],
                "frequency_interval": "1"
            },
            {
                "id": "PD-09F153711W076870CSZ6CHVI",
                "name": "Trial payment definition",
                "type": "TRIAL",
                "frequency": "Day",
                "amount": {
                    "currency": "USD",
                    "value": "0"
                },
                "cycles": "1",
                "charge_models": [],
                "frequency_interval": "14"
            }
        ],
        "merchant_preferences": {
            "setup_fee": {
                "currency": "USD",
                "value": "0"
            },
            "max_fail_attempts": "0",
            "return_url": "https://www.flixfling.com",
            "cancel_url": "https://www.flixfling.com/cancel",
            "auto_bill_amount": "YES",
            "initial_fail_amount_action": "CONTINUE"
        }
    },
    "links": [
        {
            "href": "https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-4SK09329MM7832020",
            "rel": "approval_url",
            "method": "REDIRECT"
        },
        {
            "href": "https://api.sandbox.paypal.com/v1/payments/billing-agreements/EC-4SK09329MM7832020/agreement-execute",
            "rel": "execute",
            "method": "POST"
        }
    ],
    "start_date": "2018-04-18T00:00:00Z"
}`

*Execute Request* https://api.sandbox.paypal.com/v1/payments/billing-agreements/EC-4SK09329MM7832020/agreement-execute (after authorize url has been run)

*Response*

Status: 500 Internal Server Error

**Comment by jvjvjv** [comment]
I just checked the header from the above response and found a PayPal Debug ID: "92fc3fe35889a"

**Comment by xiaoleih41** [comment]
@jvjvjv Can you give me a more recent  debugId?

**Comment by jvjvjv** [comment]
@xiaoleih41 I would but it looks like this is no longer an issue.

**Comment by aasmm7x** [comment]
I'm getting this same bug!

Paypal Debug ID: **3c4376e495666**
