### ISSUE TITLE
Getting PayPal status ACKNOWLEDGED after creating payout batches

### ISSUE THREAD

**Issue by EfrainReyes** [paypal/PayPal-REST-API-issues#223]
> For internal tracking : PPPLPAYPT-37734

### General information

* Environment:  Sandbox
* `PayPal-Debug-ID` values:  N/A
* Language, language version, and OS:  v1 REST API, Windows (using official .NET SDK)

### Issue description

For the past three weeks, sometimes when we create a payout batch in the PayPal API sandbox, we've gotten a payout batch status of `ACKNOWLEDGED` in the response body. This never happens in the production API. We haven't been able to reproduce it manually, as we get the expected `PENDING` status if we try creating a batch using Postman.

According to the API docs, `ACKNOWLEDGED` is only supported for Web uploads, and our sandbox payouts were submitted through the REST API. Has something changed? Is this a bug in the API Sandbox, or should we be expecting that status from now on? The current .NET SDK that we use [doesn't support it](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Api/PayoutTransactionStatus.cs).

**Comment by xiaoleih41** [comment]
This should not be an expected behavior. I have submitted a report on this.

**Comment by xiaoleih41** [comment]
Please provide payouts_batch_id/sandbox email address/timestamp for us to look into this.

**Comment by EfrainReyes** [comment]
Unfortunately we don't have batch IDs since our code is set up to throw an exception if the status is not recognized. Our sandbox email is `paypal-dev [at] rev.com` and we recorded this incident in the following dates:

2018-04-23 13:48:58.727
2018-04-16 13:50:18.170
2018-04-09 13:31:25.180
2018-04-02 13:23:48.583

**Comment by EfrainReyes** [comment]
We haven't seen any more incidents since May 14th 2018.
