### ISSUE TITLE
Getting internal service error : sandbox

### ISSUE THREAD

**Issue by mitulparmar21696** [paypal/PayPal-REST-API-issues#224]
### General information
{ Error: Response Status : 500
    at IncomingMessage.<anonymous> (/var/www/html/node_modules/paypal-rest-sdk/lib/client.js:130:23)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  response: 
   { name: 'INTERNAL_SERVICE_ERROR',
     message: 'An internal service error occurred.',
     information_link: 'https://developer.paypal.com/docs/api/payments/#errors',
     debug_id: 'c42e829d5a6f8',
     httpStatusCode: 500 },
  httpStatusCode: 500 }

* Environment: Sandbox
* `PayPal-Debug-ID` values: c42e829d5a6f8
* Language, language version, and OS:NodeJS

### Issue description
When submitting payments via credit or debit card it gives internal server error like above

**Comment by xiaoleih41** [comment]
Please make sure that you are using a newly generated credit card number for your testing. If it's a new integration, please make sure that the credit card process feature has been approved and enabled on your account before you proceed as the feature has been deprecated and supposedly no more new integration will be approved going forward.

**Comment by mitulparmar21696** [comment]
Thanks for response,
We are using new generated credit card. Credit card process features is also enable. If I try with new card again and again than by luck it accepts card. else it gives error.

**Comment by mitulparmar21696** [comment]
{
  "intent": "authorize",
  "payer": {
    "payment_method": "credit_card",
    "funding_instruments": [
      {
        "credit_card": {
          "type": "visa",
          "number": "4382572575341555",
          "expire_month": "12",
          "expire_year": "2023",
          "cvv2": "123",
          "first_name": "john",
          "last_name": "user"
        }
      }
    ]
  },
  "transactions": [
    {
      "amount": {
        "total": "20.00",
        "currency": "USD"
      },
      "description": "Test",
      "invoice_number": "XX",
      "payment_options": {
        "allowed_payment_method": "INSTANT_FUNDING_SOURCE"
      }
    }
  ]
}

This is JSON. I am sending

**Comment by xiaoleih41** [comment]
Please try again to see if you still see the same issue.

**Comment by mitulparmar21696** [comment]
Still getting same error. it was in working from long time. just from last week this issue occurred.

**Comment by mitulparmar21696** [comment]
Now It works properly so closing this issue
