### ISSUE TITLE
Using Webhooks (or IPN) for Recurring Subscription billing with the REST API

### ISSUE THREAD

**Issue by jcus0006** [paypal/PayPal-REST-API-issues#228]
I am implementing Recurring subscription with the Rest API. I have managed to create a plan, create an agreement and execute it. The plan is set to bill the user daily and the notifications do appear in the PayPal Developer section, so recurring billing is happening. I have subscribed to all webhooks, but the only 2 webhooks that seem to have been fired are the Billing Plan Created and Billing Subscription Created. I would like to receive a Webhook when the user is billed daily (eventually monthly as for the time I am using daily for testing purposes). Some sources I found say that PAYMENT.SALE.COMPLETED should be used in this case but it is not firing for me. Other sources said that Webhooks should not be used to notify the system about recurring billing but instead IPN should be used. 

1) Is PAYMENT.SALE.COMPLETED indeed a webhook that fires on recurring billing for e.g. daily or monthly? If so, why is it not working for me? Does it not work in Sandbox perhaps? I have not tried with Live yet.

2) If IPN should be used for such notifications, how should IPN used with the Rest API? I have also implemented Single payments using the classic system, where a hidden form is populated with the required fields, and 'notify_url' refers to the IPN listener. I suspect that when creating the Plan for recurring billing, the 'notify_url' property in the MerchantPreferences object can be similarly used to set the IPN listener for the Plan. 

a) Is this correct? 
b) Will a recurring billing notification be sent if subscribed to IPN as described? 
c) If both the Classic and Rest API system are used for the same merchant, can there be 2 different IPN listeners: 1 for the single payments and 1 for the recurring plans? 
d) And can there be different IPN listeners for different plans?

Apologies if this is not the right medium to ask such a question, but I think the documentation is quite short of information and also misleading at times. I have opened a support request which unfortunately did not lead me towards a technical resolution, rather I was provided with a lengthy description that did not essentially answer any of my questions. In some cases I have found documentation saying that the IPN listener can be set and configured from the PayPal developer portal and I have never seen this in my portal. Furthermore I could hardly find any information regarding Webhooks for recurring billing, as well as no information specific to using the IPN for the REST API. I felt this forum was my best bet. Appreciate anyone's help.

Update 1 -

I have attempted what I discuss in this question. I have created an IPN listener and tried to susbcribe to it by adding it to the notify_url value of the MerchantPreferences object, When creating the plan, a Bad Request error is being returned. It seems that it does not work in that way. If someone could put me in the right direction, it would be most appreciated.

Update 2 - 

2 Webhooks as: PAYMENT.SALE.COMPLETED have been recorded in the webhook events section of my paypal developer portal. Ever since I created the plan/s and executed the agreement, the "customer" has been billed around 20 times, and I have being paid around 20 times, and such notifications are visible in the notifications section within the portal. Which is why these 2 random webhooks do not make any sense. This means that either:

a) there is a bug in the way this Webhook is fired, 
b) there is a problem with this Webhook in the sandbox environment
c) this kind of webhook is fired on a random basis without any pattern whatsover. 

If it is the latter case, I would understand that the webhook would not be immediate, but at least it would be within the same day and delayed by only a few hours. Besides, if there are 20 notifications, there should be 20 webhooks of payment completed, and not 2.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been given.

**Comment by thisismydesign** [comment]
I don't think the questions were answered at all. I browsed through the documentation today and have absolutely no idea whether it's possible to process subscription payments via webhooks. @xiaoleih41 could you clarify this? @jcus0006 what did you end up doing?

**Comment by jcus0006** [comment]
This has been a while but if I remember correctly we just did not pursue
the implementation of recurring payments via PayPal! Sorry for not being
able to assist you further.

**Comment by thisismydesign** [comment]
@jcus0006 thanks!

**Comment by xtempore** [comment]
What an embarrassment PayPal's "support" is. Clearly this question is NOT answered. "We are pushing to get it fixed"? Seriously. That's your "answer". This question is only answered once you are able to come back and say "It HAS been fixed. Sorry for the inconvenience".
PayPal's implementation is flaky, their documentation incomplete, and their support either incompetent or absent.
