### ISSUE TITLE
token missing scope to query Sync API

### ISSUE THREAD

**Issue by vickorian** [paypal/PayPal-REST-API-issues#229]
### General information

* Environment: Live and Sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:  Python 3.6.3 | Anaconda Custom (64-bit) | Ubuntu 16.04 LTS

### Issue description

Utilizing the python rest_sdk, i'm making queries via the Api.get call to "v1/reporting/transactions" and constantly getting 401 errors. When I check the Api.get_token_hash, everything looks fine, as in the token hasn't timed out, but I noticed on the scope, I do not have access to the reporting data. In my API settings on the paypal site, i have enabled transaction searching, but my scope remains the same. 

Is there anything else I need to do to gain access to the Sync API?

**Comment by xiaoleih41** [comment]
This should be it. You should not do anything extra.  What kind of error did you get when you try to make the call? To check your scope, you may have to submit a ticket at developer.paypal.com/support to have them look into it and add the scope if it's necessary.

**Comment by vickorian** [comment]
when making the query i get a 401: unauthorized access error. The interesting thing is that the function does not return anything, instead, when i cancel the kernel, i get a string of 401 errors as the SDK function keeps sending get requests. I wanted to see if this was a known issue before i went to support, it seems like that is what i should do next.

**Comment by xiaoleih41** [comment]
Close this issue as the correct contact path has been provided.
