### ISSUE TITLE
Brazil Sandbox REST App not available

### ISSUE THREAD

**Issue by pp-randy** [paypal/PayPal-REST-API-issues#23]
> For internal bookkeeping: PPPLPAYPT-19523

Brazil sandbox accounts are not visible in the REST app creation list because there was an error creating the sandbox account.

**Comment by fredroo** [comment]
yes, i call to brazilian support and tell me not avaliable rest api

**Comment by pp-randy** [comment]
Ahhh.... Sorry @fredroo, thank you for contacting Brazil Support on this.

**Comment by fredroo** [comment]
Do you have any predictions of when you can use it? Well you need it for my app

**Comment by pp-randy** [comment]
I talked to technical support and you should be able to create a Brazil Rest app and use it for PayPal payments.  I have created an internal issue for that as well.

**Comment by pp-randy** [comment]
Tech support tested and said they had success when the account logging into developer.paypal.com was also a BR account.

**Comment by fredroo** [comment]
![image](https://cloud.githubusercontent.com/assets/6863089/23709190/67403d28-03f7-11e7-99ae-1a696d3cbfa8.png)

**Comment by pp-randy** [comment]
I looked up the sandbox accounts and it appears they are in an error status. I will try to escalate this further.

**Comment by fredroo** [comment]
@pp-randy ok i need this, please help me

**Comment by pp-randy** [comment]
@fredroo I have escalated the issue with the Brazil Sandbox Account creation and will let you know when I have updates.

**Comment by susumuasaga** [comment]
This is the way they treat us, Brazilian developers.

**Comment by pp-randy** [comment]
The issue creating Brazil Sandbox REST Apps should be resolved.  You will need to create a new Brazil Business Sandbox Account first.  

Please let us know if you continue to experience issues with REST App creation.  I apologize for any inconvenience this issue has caused.
