### ISSUE TITLE
Transaction IDs

### ISSUE THREAD

**Issue by mdurao** [paypal/PayPal-REST-API-issues#230]
Hello,

i'm using the Paypal Sync API to get a list of transactions.
Everything is Ok, etc... until I noticed that the the transaction_id that the paying customer gets it's different from the transaction_id returned by the API.

Example: Someone donates to my account, gets an email with a transaction_id. Then, I refresh my list of transactions and see a new donation in the list... the transaction_id is different!!!!

How can I reference the user donation id against what I retrieve from the paypal API?

**Comment by xiaoleih41** [comment]
You cannot use the transaction ID listed inside of the user's account. It's different. The transaction ID is the `sale_id` after the payment is execute. you should get the data from your end.

**Comment by xiaoleih41** [comment]
close this issue as the answer has been given.
