### ISSUE TITLE
Live webhook not firing

### ISSUE THREAD

**Issue by schw4rzlicht** [paypal/PayPal-REST-API-issues#231]
### General information

* Environment: Production
* `PayPal-Debug-ID` values: n/a

### Issue description

I registered a live webhook and followed the steps provided [here](https://developer.paypal.com/docs/integration/direct/webhooks/rest-webhooks/#subscribe-to-events). I subscribed to all events.

However when I send money to the account, the webhook is not triggered. With the webhook simulator, everything works fine.

What did I miss?

**Comment by xiaoleih41** [comment]
The webhook should have been sent if the simulator works for you. There may be some delay in sandbox environment.

**Comment by schw4rzlicht** [comment]
Is it possible that there are no events to fire when money gets transferred from one account to the other? Without a sale involved?
Are there events which trigger when a donation comes in?

**Comment by xiaoleih41** [comment]
Close as the answer has been given.
