### ISSUE TITLE
No transaction_id variable in response of /v1/payments/payouts?sync_mode=false

### ISSUE THREAD

**Issue by pngnviko** [paypal/PayPal-REST-API-issues#232]
>For internal tracking: PPPLPAYPT-38652

### General information

* Environment:  Sandbox
* `PayPal-Debug-ID` values:  32037b67e3e1
* Language, language version, and OS:  Python 2.7.14, Django 1.11 on Mac OS 10.13.4

### Issue description
I use PayPal REST API both in production and sandbox.

Sandbox account was created few days ago.
 
In production environment I am sending requests to `/v1/payments/payouts?sync_mode=true` and everything works fine.

But in sandbox I cannot create payouts with `sync_mode=true`, because `sync_mode=true` is deprecated for new instances. And I an getting an error: 
```
{"name":"SYNC_MODE_NOT_APPLICABLE",
"message":"Synchronous mode will soon be deprecated and is no longer available for new integrations. You can use the asynchronous mode by specifying sync_mode= false in the request."}
```
The question is -- how can I make production and sandbox environments consistent? Unfortunatelly, big refactoring now is not an option. 

What can I do/to whom I should write to enable requests to `/v1/payments/payouts?sync_mode=true` in newly created test env?

Besides, response of `/v1/payments/payouts?sync_mode=false` has no `transaction_id` variable, but I do need it both in prod and test envs.

**Comment by xiaoleih41** [comment]
I have reported the missing transaction Id issue that you have experienced. I don't have issue with creating synchronized payout. Can you please provide debugID for me to look into for you?

**Comment by pngnviko** [comment]
@xiaoleih41, thank you for quick response!
There is missing `transaction_id` only when I create payout in **async** mode. 
Is it supposed to be so?

Also, in async mode I get `debugID` only when somethings goes wrong. When payment is going to be successful,  I don't get  `debugID` in response. So, I cannot provide it.

**Comment by pngnviko** [comment]
@xiaoleih41, how do you think, is it possible to enable requests to `/v1/payments/payouts?sync_mode=true` in newly created Sandbox, despite the fact that **sync** mode is deprecated?
I need to ensure that responses from  production PayPal REST API and Sandbox are the same.

**Comment by xiaoleih41** [comment]
It is supposed to be this case. You should follow up with GET detail later to get the transaction ID as the transaction was not completed instantly if the mode was not synchronous. It is expected behavior. You should be able to enable requests to synchronous payouts without issues. I can't reproduce your issues.

**Comment by pngnviko** [comment]
My issue for synchronous payouts can be investigated with `debug_id: f9cc070cafda` I guess. 

```
ForbiddenAccess: Failed. Response status: 403. Response message: Forbidden. Error message: {"name":"SYNC_MODE_NOT_APPLICABLE",
"message":"Synchronous mode will soon be deprecated and is no longer available for new integrations. You can use the asynchronous mode by specifying sync_mode= false in the request.",
"debug_id":"f9cc070cafda",
"information_link":"https://developer.paypal.com/docs/api/payments.payouts-batch/#errors"}
```

**Comment by xiaoleih41** [comment]
I am checking internally to see what's the cause of it and will update the thread if I hear anything back.

**Comment by pngnviko** [comment]
Thanks for the explanation. Could you tell me where I should apply to get to the white list of that feature? Maybe e-mail address or something else?

**Comment by xiaoleih41** [comment]
Please email your Business name, PayPal email address, the reason for the request to payoutsUSD@paypal.com.  You will be contacted for the next step.
