### ISSUE TITLE
Paypal Billing Creation #Internal Server Error 500

### ISSUE THREAD

**Issue by RahulLakshakar** [paypal/PayPal-REST-API-issues#238]
Hello,

I am trying to add the facility of recurring payment in my system for the users. I am trying to add billing plan but when i am going to create plan it's always sending "remote server error (500)" from the sandbox.

Please guide me, why am i getting this error??

**Comment by trainerbill** [comment]
Can you make sure your REST application has the Recurring payments permission in developer.paypal.com.  Also please post the debug id for api calls so I can look in the logs.

**Comment by xiaoleih41** [comment]
Close due to inactivity. Please resubmit when the issue is not resolved.
