### ISSUE TITLE
500 Internal_Service_Error while refund payment (PHP)

### ISSUE THREAD

**Issue by jhfyang** [paypal/PayPal-REST-API-issues#285]
* Environment: Sandbox
* `PayPal-Debug-ID` values: 2b58a666e074d
* `PayPal-PHP-SDK`: dev-2.0-beta

When trying to make a refund of a payment sale I keep encountering :

```
{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"2b58a666e074d"} 
```

Here is my code: 

```
        $getPaymentRequest = new PaymentGetRequest($paymentId);

        //Executing request to create Paypal payment
        try {
            /** @var HttpResponse $httpresponse */
            $httpresponse = $client->execute($getPaymentRequest);
        } catch (HttpException $e) {
            $this->paypalLogger->error(
                "Error while refunding paypal payment with paypal_id : ".$utPaypalTransaction->getPtPaypalId(
                ).' - '.$e->getMessage().' - '.$e->getLine()
            );
        }

        /** @var \stdClass $payment */
        $payment = $httpresponse->result;

        $saleId = $payment->transactions[0]->related_resources[0]->sale->id;

                $refundRequest = new SaleRefundRequest($saleId);

        //Executing request to create Paypal payment
        try {
            /** @var HttpResponse $httpresponse */
            $httpresponse = $client->execute($refundRequest);
        } catch (HttpException $e) {
            $this->paypalLogger->error(
                "Error while refunding paypal payment with paypal_id : ".$utPaypalTransaction->getPtPaypalId(
                ).' and sale_id :' . $saleId . ' '.$e->getMessage().' - '.$e->getLine()
            );
        }

        $plan = $httpresponse->result;
```

**Comment by flo-m** [comment]
any update on this issue? I'm also facing this issue in dev-2.0-beta

**Comment by jhfyang** [comment]
Since then I have not been able to implement Paypal refund. They have told me to try on master branch .. which is out of the question since I have built already my Paypal environment with the dev-2.0-beta

**Comment by flo-m** [comment]
seems like I have solved the issue.
You need to pass the amount to paypal - even if you want to fully refund this transaction.

this works for me:
`	$saleRefundRequest = new SaleRefundRequest($this->getPayPalTransactionID());
		$saleRefundRequest->body = [
		    "amount" => [
  				"total" => $amount,
  				"currency" => "EUR"]
  			];
  		try {
   			$refundTrans = $client->execute($saleRefundRequest);
   			if($refundTrans->result->state == 'completed'){
   				return $refundTrans->result->id;
   			}	

		} catch (HttpException $ex) {
		    echo $ex->statusCode;
		    print_r($ex->getMessage());
			return false;
		}`

**Comment by jhfyang** [comment]
@flo-m Thank you, will try this asap !

**Comment by jhfyang** [comment]
Thank you so much @flo-m this was the problem to this issue
