### ISSUE TITLE
billingPlan.update rejects some forms of valid RFC 6902 patches

### ISSUE THREAD

**Issue by pp-randy** [paypal/PayPal-REST-API-issues#50]
*Migrated issue from https://github.com/paypal/PayPal-node-SDK/issues/239*

> For internal bookkeeping: PPPLMER-41205

billingPlan.update does not correctly process some forms of valid RFC 6902 patches. 

working
patch =
```
[
  {
    "op": "replace",
    "path": "/",
    "value": {
      "state": "ACTIVE"
    }
  }
]
```

not working
patch =
```
[
  {
    "op": "replace",
    "path": "/state",
    "value": "ACTIVE"
  }
]
```

**Comment by xiaoleih41** [comment]
Close this issue as it has been solved.
