### ISSUE TITLE
500 Internal Error - Sandbox Credit Card Payments

### ISSUE THREAD

**Issue by pp-randy** [paypal/PayPal-REST-API-issues#51]
*Migrated issue from https://github.com/paypal/PayPal-NET-SDK/issues/247*

> For internal bookkeeping: PPPLMER-28970

Credit Card payments are failing with funding source credit_card

Workaround seems to be using payment_card as the funding source.

**Comment by battaile** [comment]
No longer getting the error as of this morning

**Comment by pp-randy** [comment]
Thanks @battaile for the update.  My tests are passing now as well.
