### ISSUE TITLE
Python SDK: Payment creation and payment listing returns unknown and internal server errors

### ISSUE THREAD

**Issue by astrikov-d** [paypal/PayPal-REST-API-issues#57]
### General information

* Environment: sandbox
* `PayPal-Debug-ID` values: 177bc9255c599

### Issue description

Issue: can not create payment with paypal python sdk.
Details: I'm using code from API documentation and can not create payment with initialized sdk:

```
payment = paypalrestsdk.Payment({
            "intent": "sale",
            "payer": {
                "payment_method": "credit_card",
                "funding_instruments": [{
                    "credit_card": {
                        "type": "visa",
                        "number": "4417119669820331",
                        "expire_month": "11",
                        "expire_year": "2018",
                        "cvv2": "874",
                        "first_name": "Joe",
                        "last_name": "Shopper"}}]},
            "transactions": [{
                "item_list": {
                    "items": [{
                        "name": "item",
                        "sku": "item",
                        "price": "1.00",
                        "currency": "USD",
                        "quantity": 1}]},
                "amount": {
                    "total": "1.00",
                    "currency": "USD"},
                "description": "This is the payment transaction description."}]})
if payment.create():
    print("Payment created successfully")
else:
    print(payment.error)
```
This code gives me error:

`{u'message': u'An unknown error occurred.', u'debug_id': u'177bc9255c599', u'name': u'UNKNOWN_ERROR', u'information_link': u'https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR'}`

Also, payment listing is not working too:

```
api = paypalrestsdk.configure(settings.PAYPAL_APP_CREDENTIALS)
payments = paypalrestsdk.Payment.all({'count': 5}, api=api)
```

Throws exception:

`Failed. Response status: 500. Response message: Internal Server Error. Error message: {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"b099d6095f5c4"}`

**Comment by pp-randy** [comment]
The payment issue is related to https://github.com/paypal/PayPal-REST-API-issues/issues/22

You can use the Generate CC Number button at the bottom to get a randomly generated card number https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413

I will look into the Payment Search issue and follow up with you further.

**Comment by pp-randy** [comment]
Are you still seeing the 500 error with payment listing?  I ran a test of your code and it was working for me.

**Comment by pp-randy** [comment]
Looked into your Payment listing error and seems you are impacted by https://github.com/paypal/PayPal-REST-API-issues/issues/54

**Comment by pp-randy** [comment]
Since both issues are being tracked already I will close this issue. 

Error for certain card numbers: https://github.com/paypal/PayPal-REST-API-issues/issues/22
Error for Payment List: https://github.com/paypal/PayPal-REST-API-issues/issues/54
 
Please let me know if you need further help.

**Comment by astrikov-d** [comment]
OK, thank you.

**Comment by pp-randy** [comment]
Sorry for the inconveniences.  Hopefully, a new random credit card works for you from the tool provided above.  It might be worth testing a different REST App for the payment list issue as it did work for a new one I created yesterday.
