### ISSUE TITLE
Credit card payments are not receiving webhook event

### ISSUE THREAD

**Issue by xiaoleih41** [paypal/PayPal-REST-API-issues#59]
Migrated issue from https://github.com/paypal/PayPal-Ruby-SDK/issues/277

> Known workarounds or alternative products: Braintree payments 

> For internal bookkeeping: PPPLMER-29757

Webhooks are not sent for REST API credit card payments.

**Comment by laudukang** [comment]
Sandbox mode webhooks not receive pay complete, soga 😿

**Comment by broscodo** [comment]
@laudukang I am also not receiving any notifications in Sandbox mode. The simulator works fine but sandbox transactions do not work.

**Comment by pp-randy** [comment]
Please follow this issue for updates on sandbox payment webhooks https://github.com/paypal/PayPal-REST-API-issues/issues/103

**Comment by dcag58** [comment]
@pp-randy I know this probably has been answered, but could you please confirm. Thanks.

If Webhook is NOT sent out for Direct Credit Card Payment, is there any other method to receive notification? We need it to integrate with our payment handling server.

And also if feature request has been submitted, could you update the status?

**Comment by pp-randy** [comment]
@dcag58 you can use [Instant Payment Notification](https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNIntro/). 

If you have not yet integrated I would encourage our Braintree offerings for credit card payments https://www.braintreepayments.com/. 

I will check on the status of the request.

**Comment by dcag58** [comment]
@pp-randy I just tested direct credit card on sandbox, webhhooks were successfully delivered. I couldn't test live yet because we are still waiting for PayPal to approve this on our account. It looks promising. If sandbox is working, does it mean that it will roll out to live soon? Thanks.

**Comment by pp-randy** [comment]
You got a webhook for a direct credit card payment or an Instant Payment Notification(IPN)?

**Comment by dcag58** [comment]
I'm only using REST API Apps, and the buyer used a fake credit card number without paypal log in.  I'm sure it's webhook from direct credit card payment.

**Comment by xiaoleih41** [comment]
Close this issue as no more development will be done for credit card processing on REST.
