### ISSUE TITLE
Sandbox internal server error

### ISSUE THREAD

**Issue by pp6** [paypal/PayPal-REST-API-issues#62]
I am using the nvp api to generate an encrypted "Buy now" button.
After I click the "Buy now" button, I get redirected to the sandbox, where I receive an "Internal server error".
I don't see a PayPal-Debug-ID.
![pp-crpt](https://cloud.githubusercontent.com/assets/27280300/24905648/5c47a006-1ebd-11e7-9448-3321eab46381.png)

**Comment by pp-randy** [comment]
Are you using a particular SDK, for example [buttonmanager-sdk-php](https://github.com/paypal/buttonmanager-sdk-php)?  

What is the email address of your sandbox business account?

**Comment by pp6** [comment]
No, I am not using an SDK.
The email is manuela_pungan-facilitator@yahoo.com

**Comment by pp-randy** [comment]
I looked over the code, tested it, and reproduced the same error but only using an encrypted button.  With the cleartext option the button code worked and looked good.  

Have you already contacted [PayPal Technical Support](https://www.paypal-techsupport.com/app/ask) in regards to this issue?

**Comment by pp6** [comment]
I don't want to use cleartext because the user may modify the amount field in the generated html.
The encrypted option works on production environment.
I contacted the support team last friday, they acknowledged this as a bug around 24 hours ago(after opening this ticket).

**Comment by pp-randy** [comment]
Thank you for the information.  I will close this issue as Technical Support is involved already and aware of the issue.

**Comment by lakinmohapatra** [comment]
Hi Paypal team , i faced same issue on my sandbox account . Please resolve this asap.

**Comment by lakinmohapatra** [comment]
https://www.sandbox.paypal.com/cgi-bin/webscr

**Comment by pp-randy** [comment]
@lakinmohapatra if you are experiencing issues with a Payment Standard button can you please reach out to PayPal Technical Support here: [https://www.paypal-techsupport.com/app/ask](https://www.paypal-techsupport.com/app/ask).

**Comment by erny83pd** [comment]
I've the same problem in the sandbox

**Comment by xiaoleih41** [comment]
@erny83pd  Please contact [PayPal Technical Support](https://www.paypal-techsupport.com/app/ask) regarding this issue. This forum is for PayPal REST API issues only.
