### ISSUE TITLE
Clarify Invoice Search paging parameters

### ISSUE THREAD

**Issue by JosephDev** [paypal/PayPal-REST-API-issues#64]
*Migrated issue from https://github.com/paypal/PayPal-Python-SDK/issues/195*

> Known workarounds or alternative products:  N/A

> For internal bookkeeping: DEVDOC-652

PayPal REST API document is no mention about `MAX SIZE` on `page_size`.
I think it has limit (my experiment says it is 100) but no mentions.

[Search for invoices](https://developer.paypal.com/docs/api/invoicing/#invoices_search)
```
page_size number
The page size for the search results.
```
--------------------------------------------------------
[List Merchant Invoices](https://developer.paypal.com/docs/api/invoicing/#invoices_get-all):
Clarify how `page` works and correct default to show 0, page is actually independent of page_size and reflects the entire list.

**Comment by pp-randy** [comment]
Thank you for submitting the issue. I have added tracking information to your initial comment.

**Comment by pp-randy** [comment]
The page and page_size parameters have been updated.  The max page size has not been added at this time.
