### ISSUE TITLE
INVALID_RESOURCE_ID

### ISSUE THREAD

**Issue by ebetron** [paypal/PayPal-REST-API-issues#66]
> For internal bookkeeping: PPPLPAYPT-20697

* Environment: Production
* `PayPal-Debug-ID` values: 
```
                                "debug_id": "999f63e1ad005"
                                "debug_id": "f95fc0e7a79c9"
                                "debug_id": "5da940e65ce2b"
                                "debug_id": "1b199f07a5330"
                                "debug_id": "1091ce7585fdd"
                                "debug_id": "3e2a73a9a7422"
                                "debug_id": "f45ed9c4a4ca7"
                                "debug_id": "f92d1cc881de2"
                                "debug_id": "766d4a74cc301"
                                "debug_id": "3b8d578dd690e"
                                "debug_id": "8d679c19a4610"
                                "debug_id": "d4a94766deeab"
                                "debug_id": "3bc3ab5ea5c0f"
                                "debug_id": "72ff2e1595908"
                                "debug_id": "400caa8b78424"
                                "debug_id": "22996c883bd8"
                                "debug_id": "c44044c4a8336"
                                "debug_id": "f9798118c4989"
```
* Language, language version, and OS: C# on Windows Server 

### Issue description
Trying to understand why these transactions threw this error. Any light you could shed on these issues would be greatly appreciated. Thanks.

**Comment by pp-randy** [comment]
This looks like a possible system issue to me.  The vault tokens you are using appear to be valid since I see API requests to GET them in your logs. 

Can you reach out to [PayPal Technical Support](https://www.paypal-techsupport.com/app/ask) and report the issue?

**Comment by pp-randy** [comment]
I am following up further on this as well, from how I am seeing this I would expect a 500 error to actually have been returned.

**Comment by ebetron** [comment]
@pp-randy we have contacted Paypal Technical Support and they have confirmed it is indeed a system issue.

**Comment by ebetron** [comment]
@pp-randy PayPal Technical Support is working on the issue but has not given us details on what might be the problem. Have you been able to followup on this?

**Comment by pp-randy** [comment]
Sure, what is your ticket number with PayPal Technical Support?

**Comment by ebetron** [comment]
Incident # is: 170420-000523
