### ISSUE TITLE
reference_id used in payment create throws MALFORMED_REQUEST

### ISSUE THREAD

**Issue by pp-randy** [paypal/PayPal-REST-API-issues#69]
*Migrated issue from https://github.com/paypal/PayPal-PHP-SDK/issues/828*

> For internal bookkeeping: PPPLPAYPT-20805

When `reference_id`  is supplied to a [transaction](https://developer.paypal.com/docs/api/payments/#definition-transaction) object during payment create a MALFORMED_REQUEST is returned.   `reference_id` is currently documented as usable and to be provided by the merchant.

**Comment by pp-randy** [comment]
The error should now be resolved.  Further follow up is needed on the documentation.

**Comment by PhoneixS** [comment]
Maybe I miss something, but I don't see the change in the documentation.

**Comment by pp-randy** [comment]
As indicated in my previous comment. I will be following up further on documentation.  I will spawn a new issue with tracking details.  The error is resolved, but we need to clarify how the field is supposed to be used.

**Comment by pp-randy** [comment]
https://github.com/paypal/PayPal-REST-API-issues/issues/77 has been created for further documentation clarification.
