### ISSUE TITLE
Provide helpful error for missing transaction parameter with Payment creation

### ISSUE THREAD

**Issue by pp-randy** [paypal/PayPal-REST-API-issues#70]
*Migrated issue from https://github.com/paypal/PayPal-NET-SDK/issues/253*

> For internal bookkeeping: PPPLPAYPT-20843

Improve error messaging when [`transactions`](https://developer.paypal.com/docs/api/payments/#payment_create) array is not provided in the API request. 

Current error: 
500 - `{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred"} `

**Comment by xiaoleih41** [comment]
The issue is fixed.  the fixed version error. 
````
{
"name": "VALIDATION_ERROR",
"details": [
{ "field": "transactions", "issue": "input cannot be null", "code": "NULL_INPUT" }
],
"message": "Invalid request - see details",
"information_link": "https://developer.paypal.com/docs/api/payments/#errors",
"debug_id": "a3413034b406b",
"code": "VALIDATION_ERROR"
}
````
