### ISSUE TITLE
Billing agreement state and id fields in Billing Agreements API

### ISSUE THREAD

**Issue by xiaoleih41** [paypal/PayPal-REST-API-issues#72]
Migrated issue from https://github.com/paypal/PayPal-PHP-SDK/issues/418

>Known workarounds or alternative products: N/A

>For internal bookkeeping: DEVDOC-426 DEVDOC-672

Billing Agreement state and id fields are missing from [Billing Agreements API References](https://developer.paypal.com/docs/api/payments.billing-agreements).

**Comment by pp-randy** [comment]
Closing as this is now resolved
