### ISSUE TITLE
No (good) way to retrieve token to handle cancelled payments

### ISSUE THREAD

**Issue by helgihg** [paypal/PayPal-REST-API-issues#74]
### General information

* Environment: Sandbox
* `PayPal-Debug-ID` values: What?
* Language, language version, and OS: Python 2.7.12 on Ubuntu 16.04, using paypalrestsdk version 1.12.0

### Issue description

When a payment is cancelled on PayPal's side, PayPal will redirect the user to a page, using a token to identify the payment in question. Example: http://localhost:8000/cart/paypal/cancel/?token=EC-0HY5497597422745M

However, that token is not available to the original website before it is used by PayPal, except as an HTTP parameter in the links returned when the payment is prepared. Example: {'href': u'https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-4SK23915UR135711X', 'method': u'REDIRECT', 'rel': u'approval_url'}

I cannot imagine that the programmer is expected to parse that URL in order to retrieve the token for use with cancelled payments. So the question arises; how can the token be properly retrieved on the original site's end before it is used by PayPal to indicate cancellation of payment?

**Comment by pp-randy** [comment]
We are tracking a request to get the PaymentID added to the cancel url https://github.com/paypal/PayPal-REST-API-issues/issues/29. Parsing the token from the approval URL is a workaround.  We have added helper functions to some SDKs, when requested by developers, to parse the token out.  I don't believe the Python SDK has this though.

**Comment by helgihg** [comment]
@pp-randy Thanks for the info! It's good to know the official status of this. :)
