### ISSUE TITLE
Payouts - Unexpected link array in error details for duplicate SENDER_BATCH_ID

### ISSUE THREAD

**Issue by pp-randy** [paypal/PayPal-REST-API-issues#76]
*Migrated issue from https://github.com/paypal/PayPal-NET-SDK/issues/255*

> For internal bookkeeping: PPPLPAYPT-20971 

Payouts error response for duplicate `SENDER_BATCH_ID` contains a link array that is not in the api schema for [`common_error_details`](https://developer.paypal.com/docs/api/payments.payouts-batch#definition-common_error_details:v1).

**Comment by xiaoleih41** [comment]
Close this issue as it has been solved.
