### ISSUE TITLE
Clarify purchase_order property in Payments API

### ISSUE THREAD

**Issue by trainerbill** [paypal/PayPal-REST-API-issues#82]
*Migrated issue from https://github.com/paypal/paypal-checkout/issues/319*
 
> Known workarounds or alternative products: use invoice_number

> For internal bookkeeping: PPPLPAYPT-22208
 
Clarify `purchase_order` property in [Payments API](https://developer.paypal.com/docs/api/payments/#payment).

**Comment by xiaoleih41** [comment]
This issue has been resolved. `purchase_order` can be passed without any error.
