### ISSUE TITLE
[Help] DPRP Disabled on SandBox Account

### ISSUE THREAD

**Issue by sufyan297** [paypal/PayPal-REST-API-issues#83]
*Migrated issue from https://github.com/paypal/PayPal-PHP-SDK/issues/780*

> Known workarounds or alternative products: Use US sandbox account

> For internal tracking PPPLMER-26632

**Direct credit card processing** for [billing agreement](https://developer.paypal.com/docs/integration/direct/billing-plans-and-agreements/) feature is not available for UK sandbox account. 

Hello folks,

I have created UK Based Sandbox Business Pro account (my actual account is based on Singapore). But on Sandbox account it is giving me this error.
used sandbox credit card  which was associated with one of my sandbox account.

**My Request:**
`{"name":"Awesome Subscription Plan","description":"Credit Card Payment","start_date":"2017-05-27T03:20:26+00:00","plan":{"id":"P-3M5451107P058053WIC5SOQY"},"payer":{"payment_method":"credit_card","payer_info":{"email":"xyz@gmail.com"},"funding_instruments":[{"credit_card":{"type":"mastercard","number":"5428549811526689","expire_month":"06","expire_year":"2022","cvv2":"123"}}]}}
`

**Response:**
`Array
(
    [name] => DPRP_DISABLED
    [message] => DPRP is disabled for this merchant.
    [information_link] => https://developer.paypal.com/docs/api/payments.billing-agreements#errors
    [debug_id] => aace4ca7f1023
)`

**Comment by xiaoleih41** [comment]
This function is not enabled for UK account in sandbox. Please refer to https://github.com/paypal/PayPal-PHP-SDK/issues/780 for the work around for now.

**Comment by xiaoleih41** [comment]
Please note that direct credit card processing is not available in Singapore PayPal account. So when you go live, you will not have this functionality in your Singapore account.
