### ISSUE TITLE
Create payment: UNAUTHORIZED_PAYMENT error

### ISSUE THREAD

**Issue by freedemster** [paypal/PayPal-REST-API-issues#85]
Hello,
I got this error when try to create new payment in sandbox with next payload:

```json
{
  "intent": "sale",
  "payer": {
    "payment_method": "credit_card",
    "funding_instruments": [
      {
        "credit_card_token": {
          "credit_card_id": "CARD-xxxxxxxxx",
          "payer_id": "xxxxxxxxx"
        }
      }
    ]
  },
  "transactions": [
    {
      "amount": {
        "currency": "USD",
        "total": "319.95"
      },
      "item_list": {
        "items": [
          {
            "name": "Subscription",
            "currency": "USD",
            "price": "319.95",
            "quantity": 1
          }
        ]
      },
      "invoice_number": "xxxxxxxxx",
      "custom": "xxxxxxxxx"
    }
  ]
}
```

Response:

```json
{
  "name": "UNAUTHORIZED_PAYMENT",
  "message": "Unauthorized payment.",
  "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#UNAUTHORIZED_PAYMENT",
  "debug_id": "d993ac5c37ec"
}
```

Access token obtained successfully and I can store credit card in vault, but I can't create payment with stored card. Also I try to use 'paypal' payment method, but got 500 error.

Environment: sandbox
Debug id: d993ac5c37ec
Language: PHP 7.0 with paypal/rest-api-sdk-php version 1.11.0

**Comment by xiaoleih41** [comment]
I tested the code and it works fine for me. Please make sure that you have the right **client ID** and **secret** entered to make the call. Please check on https://github.com/paypal/PayPal-Ruby-SDK/issues/229 to see if this case helps you.

**Comment by freedemster** [comment]
Thanks for your answer. Everything worked after I generate new secret.

**Comment by hakunin** [comment]
Wasted some time on this, misleading error message..

**Comment by Pezhvak** [comment]
for those who still have this issue, it seems this error is caused by variety reasons, for me idk why but v1/payment is not working, switching to v2 worked, here's the repository https://github.com/paypal/Checkout-PHP-SDK
