### ISSUE TITLE
the Cancelled State of Billing Agreement Spelled Differently between Sandbox and Live Environment

### ISSUE THREAD

**Issue by benmurden** [paypal/PayPal-REST-API-issues#86]
> For internal tracking: PPPLMER-11400

[Billing Agreement](https://developer.paypal.com/docs/api/payments.billing-agreements#agreement_create_response) response **state** is spelled differently between sandbox and live environment. 
### General information

* Environment: Sandbox/Live
* `PayPal-Debug-ID` values: Sandbox: be761fe15adc7 / Live: a321aa752d35
* Language, language version, and OS: Python 2.7 using SDK on Heroku Cedar-14

### Issue description

When our system retrieves a cancelled Billing Agreement using the Python SDK, the `state` is `Cancelled` in Sandbox mode and `Canceled` in Live. Notice the first uses two Ls, while the second doesn't.

The documentation also claims that the state will be `Cancelled`, but this is not the case in the Live environment.

https://developer.paypal.com/docs/api/payments.billing-agreements#agreement_get_response

### Example webhooks

Sandbox
```
{
	"id": "WH-26J48358WN7084142-10C43771VB745815C",
	"create_time": "2017-06-09T03:35:53.667Z",
	"resource_type": "Agreement",
	"event_type": "BILLING.SUBSCRIPTION.CANCELLED",
	"summary": "A billing subscription was cancelled",
	"resource": {
...
		"state": "Cancelled",
        }
...
}
```

Live
```
{
	"id": "WH-8G48281057362033R-4XY20870X09728633",
	"create_time": "2017-06-07T23:12:12.545Z",
	"resource_type": "Agreement",
	"event_type": "BILLING.SUBSCRIPTION.CANCELLED",
	"summary": "A billing subscription was cancelled",
	"resource": {
...
		"state": "Canceled",
...
	}
...
}
```

**Comment by xiaoleih41** [comment]
Would you please provide the correlation IDs of these two API calls. This will help us verify.

**Comment by benmurden** [comment]
I'm sorry. I'm not sure what you're asking for. The debug IDs I posted should correlate to the webhooks, but the developer dashboard doesn't let me look at the contents of those API calls, so it's rather hard to be certain.

**Comment by xiaoleih41** [comment]
@benmurden I have reported this internally for a fix.

**Comment by xiaoleih41** [comment]
@benmurden Please test as the issue has been solved.

**Comment by benmurden** [comment]
@xiaoleih41 Thanks. The `Cancelled` state appears to now be consistent in sandbox, live, and the documentation.
