### ISSUE TITLE
Unable to create personal or business Sandbox accounts

### ISSUE THREAD

**Issue by asterixorobelix** [paypal/PayPal-REST-API-issues#91]
* Environment: Sandbox
* Language, language version, and OS: Windows 8, Chrome Version 58.0.3029.110 (64-bit). Location: South Africa

### Issue description
 I have created a paypal business account. I have then logged into developer.paypal with this username and password. I am unable to create SandBox accounts (both personal and business accounts display a status of : error). When I click on the account details, it displays the message: Your sandbox account could not be created. Delete it and try again.

![screenshot 2](https://user-images.githubusercontent.com/20531795/27287706-dfb3067e-5504-11e7-8717-0865259983a7.png)

**Comment by xiaoleih41** [comment]
I can see we have some issue with testing account today. I have reported this issue. However the account has been created. Do you have issue using it?

**Comment by asterixorobelix** [comment]
Hi

All the sandbox accounts were in error state, so I was unable to create an
app in order to get the client ID and secret id to add to my code.
The bug has been fixed now, thanks

On 19 Jun 2017 4:36 PM, "Xiaolei Wheelock" <notifications@github.com> wrote:

I can see we have some issue with testing account today. I have reported
this issue. However the account has been created. Do you have issue using
it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/paypal/PayPal-REST-API-issues/issues/91#issuecomment-309459366>,
or mute the thread

**Comment by xiaoleih41** [comment]
Close the ticket as the issue has been solved.

**Comment by srok** [comment]
I can't create sandbox bussiness account. It just hung on processing for ever. I need to create an app to go live on a project. Is any workarround?
![image](https://user-images.githubusercontent.com/1906521/27594833-4a933400-5b31-11e7-9125-fc2d6478e93e.png)

**Comment by xiaoleih41** [comment]
When you create an account, try to add balance (i.e. $50000) and create again see if it works. I will report this issue.
