### ISSUE TITLE
Subscription webhooks without Agreement Id

### ISSUE THREAD

**Issue by greggy** [paypal/PayPal-REST-API-issues#93]
### General information

* Environment: Sandbox

### Issue description

When a webhook listener gets payload fo subscription events ("BILLING.SUBSCRIPTION.CREATED", "BILLING.SUBSCRIPTION.CANCELLED", "BILLING.SUBSCRIPTION.RE-ACTIVATED", "BILLING.SUBSCRIPTION.SUSPENDED") with such agreement json:

```
		"description": "update desc",
		"agreement_details": {
			"outstanding_balance": {
				"value": "0.00"
			},
			"num_cycles_remaining": "5",
			"num_cycles_completed": "0",
			"last_payment_date": "2016-04-28T11:29:54Z",
			"last_payment_amount": {
				"value": "1.00"
			},
			"final_payment_due_date": "2017-11-30T10:00:00Z",
			"failed_payment_count": "0"
		},
```

They haven't needed information. It would be good to have there additional fields: agreement_id and metadata[1]. Those fields can help to identify for which user this event belongs. Right now I use description field for extra information.

[1] Metadata will be like a dictionary in python or object in js, developers can store extra info, for ex. username, user-agent, etc.

**Comment by xiaoleih41** [comment]
I tested all of them. All of them returned the **agreementId**s. They are not under agreement detail. They are under **resource**.
````
{
    "id": "WH-8KT47529P7696805Y-3CS72897S14937140",
    "event_version": "1.0",
    "create_time": "2016-04-28T11:41:01Z",
    "resource_type": "Agreement",
    "event_type": "BILLING.SUBSCRIPTION.RE-ACTIVATED",
    "summary": "A billing subscription was reactivated",
    "resource": {
        "id": "I-PE7JWXKGVN0R",
     ...
````

**Comment by greggy** [comment]
You're right, sorry!
