### ISSUE TITLE
Billing agreement id in approvement return params

### ISSUE THREAD

**Issue by chalmagean** [paypal/PayPal-REST-API-issues#94]
### General information

* Environment: Sandbox
* Language, language version, and OS: paypal/PayPal-Ruby-SDK

### Issue description

I'm trying to implement billing agreement plans and I'm not sure how you're supposed to find an agreement to confirm, based on the payment_token you receive in the `return_url` params (https://developer.paypal.com/docs/api/payments.billing-agreements#agreement_execute).

The user is supposed to approve the agreement which is an async action (it might take a while) and you need to know when the agreement was confirmed but also which agreement it is (agreement id) so you can find it and call execute on it.

Am I missing something?

**Comment by xiaoleih41** [comment]
@chalmagean  This issue is tracked at https://github.com/paypal/PayPal-REST-API-issues/issues/19. Please follow that thread for future update.  When the browser returns after the user approves the agreement, you will get the **payment token** to execute the billing agreement.

**Comment by chalmagean** [comment]
@xiaoleih41 #19 seems to refer to a different issue (agreement.create). My issue is with the approvement redirect params. I'm not 100% sure it's the same thing.

**Comment by xiaoleih41** [comment]
when the customer approves the payment, the **payment token** will be in the query string of the return URL. you can execute the billing agreement using that **payment token**.

**Comment by chalmagean** [comment]
That's correct, but in that return url's request, you only have the payment token, not the agreement id. So how do you know which agreement you're supposed to use the token for?

**Comment by xiaoleih41** [comment]
The `token` is the unique identifier for the billing agreement at this stage. The `agreementId` will be created when you execute the agreement.

**Comment by chalmagean** [comment]
So can you use the token to find the agreement?

**Comment by xiaoleih41** [comment]
Not at this stage. PayPal doesn't consider the agreement process is completed until you execute the billing agreement. When you create the agreement, in the response, you can see both the `token` and `agreement detail`, you can store them and make connection to each other if you want to query them before executing the agreement.

**Comment by chalmagean** [comment]
In the response (return_url) I can only see the `token` (`"token"=>"EC-5YC31191S4925224E"`). I'm confused about how you're supposed to execute the agreement once you have this token.

Here's how I see the flow so far:
1. Create a plan
2. Create an agreement for the plan at step 1
3. Send the user to the `approve_url` for the user's approval
4. PayPal makes a request to the `return_url` passing in the `token` via the params
5. You should use the token to confirm the agreement you've created on step 2

How do you connect the token with the agreement at step 5?

**Comment by xiaoleih41** [comment]
We currently don't have sample code in Ruby but [this](https://developer.paypal.com/docs/integration/direct/billing-plans-and-agreements/#execute-an-agreement) is What PayPal expected to execute this call.

**Comment by chalmagean** [comment]
Ah! Ok, that make sense now.

So for [this](https://github.com/paypal/PayPal-Ruby-SDK/blob/01bf74824943951fac36861161b6302481790bdf/lib/paypal-sdk/rest/data_types.rb#L2202) to work, I need to create a new Agreement with just the payment token.

And then I can execute that.

```
agreement = PayPal::SDK::REST::DataTypes::Agreement.new(token: "EC-5YC31191S4925224E")
agreement.execute
```

This feels weird to me as you first create a throw away agreement just to get the `approve_url` and then you create a new agreement to execute it.

I was expecting you execute the first agreement (the one you got the approve_url from).

Thanks @xiaoleih41, this seems to work for now even though it's not ideal.
