### ISSUE TITLE
Sandbox payment not succeeding

### ISSUE THREAD

**Issue by asterixorobelix** [paypal/PayPal-REST-API-issues#95]
* Environment: Sandbox
* Language, language version, and OS: c# .NET Windows 8 and Chrome Version 58.0.3029.110 (64-bit)

### Issue description

When I am taken to the Paypal payment page and enter my sandbox account username and  password and click continue, the payment fails and I get the attached error screen. If I click the Return to Merchant button, I am returned to my website. 
Is the paypal functionality for this down at the moment?
![screenshot 7](https://user-images.githubusercontent.com/20531795/27387518-3babf5ae-5699-11e7-8ef6-b80520cff02c.png)

**Comment by xiaoleih41** [comment]
What kind of call were you trying to make? Is there any **debugId** in the header of API response? Does this happen to all of your sandbox accounts? Have you recently created a new sandbox account? Has the transaction ever been successful before?  I did some tests on my sandbox account, they seemed fine. We did have some issue with sandbox account creation in the past two days but it was not processing related. If it's not SDK specific questions, you may submit a ticket to [PayPal technical support team](https://www.paypal-techsupport.com/). They can help verify if it is a site issue for you.

**Comment by asterixorobelix** [comment]
Hi xiaoleih41


Some code snippets:           

/// Make Payment Towards Paypal API
    public List<string> CreatePayment(string endingURl, PurchaseItemInformation item)
        {
            var baseurl = ConfigurationManager.AppSettings["DevPaymentServiceBaseURL"];
            var endingUrl = endingURl;
            // Authenticate with PayPal
            var config = new Dictionary<string, string>();
            config.Add("paypal" ,"PayPal.SDKConfigHandler, PayPal" );
            config.Add("mode", "sandbox");
            .....
            var accessToken = new OAuthTokenCredential(config).GetAccessToken();

            var apiContext = new APIContext(accessToken);
            apiContext.Config = config;
            var payment = new Payment();


            try
            {
                // Make an API call
                payment = Payment.Create(apiContext, new Payment
                {
                    intent = "sale",
                    payer = new Payer
                    {
                        payment_method = "paypal"
                    },
                    transactions = new List<Transaction>
    {
        new Transaction
        {
            description = item.Description,
            invoice_number = "invoice" + System.Guid.NewGuid().ToString().Substring(0, 8),
            amount = new Amount
            {
                currency = "USD",
                total = item.Total,
                details = new Details
                {
                    tax = "0",
                    shipping = "0",
                    subtotal = item.Total
                }
            },
            item_list = new ItemList
            {
                items = new List<Item>
                {
                    new Item
                    {
                        name = item.Name,
                        currency = "USD",
                        price = item.Total,
                        quantity = item.Quantity,
                        sku = "sku"
                    }
                }
            }
        }
    },
                    redirect_urls = new RedirectUrls
                    {
                        return_url = baseurl + endingUrl,

                        cancel_url = ConfigurationManager.AppSettings["DevBadgePaymentCancelURL"]
                    }
                });
            } catch (Exception e)
            {
                throw;
            };
            List<string> redirecturl = new List<string>();
            redirecturl.Add(payment.links[1].href);
            redirecturl.Add(payment.links[2].href);
            HttpContext.Current.Session.Add("paymentToken", accessToken);
            HttpContext.Current.Session.Add("amount", item.Total);
            return redirecturl;
        }

At the end of the call, I am not being redirected to the website from which the call originated. I am either  getting the error screen above or I am being redirected to the Paypal account page of the Sandbox account making the test payment.

**Comment by asterixorobelix** [comment]
In answer to your other questions:
Yes, I made my sandbox account within the last few days.
No, none of my sandbox payments have succeeded

**Comment by asterixorobelix** [comment]
![screenshot 8](https://user-images.githubusercontent.com/20531795/27424142-4fe77ade-5734-11e7-8935-49733e9b995d.png)
![screenshot 9](https://user-images.githubusercontent.com/20531795/27424144-500c57a0-5734-11e7-82e4-e2a54258dafb.png)
![screenshot 10](https://user-images.githubusercontent.com/20531795/27424145-500fcd72-5734-11e7-8131-5a6713447b94.png)

**Comment by xiaoleih41** [comment]
From the last screenshot, I saw some payments were successful on Jun 20. I am not sure what those payments were. You may file a ticket with [PayPal technical support](https://www.paypal-techsupport.com/). It looks more like a sandbox issue than the API issue. They should be able to help you determine this.

**Comment by xiaoleih41** [comment]
Close this ticket as the issue should have been solved as Jun 23.
