### ISSUE TITLE
What does status "created" mean when creating a payment.

### ISSUE THREAD

**Issue by leemhenson** [paypal/PayPal-REST-API-issues#97]
### General information

* Environment: `sandbox`
* `PayPal-Debug-ID` values: `a7c5f6576791c`
* Language, language version, and OS: `node 8.1` on `OSX`

### Issue description

When I attempt to pay with a fake visa credit card (`4242 4242 4242 4242`) in my sandbox account, I receive a response that looks like this:

```
{"id":"PAY-4AH92705EN0735913LFF5Y3I","create_time":"2017-06-22T15:04:13Z","update_time":"2017-06-22T15:04:13Z","state":"created","intent":"sale","payer":{"payment_method":"credit_card","funding_instruments":[{"credit_card":{"type":"visa","number":"xxxxxxxxxxxx4242","expire_month":"12","expire_year":"2020","first_name":"Joe","last_name":"Bloggs","billing_address":{"line1":"House","line2":"Road","city":"London","state":"London","postal_code":"SW1A 1AA","country_code":"HU"}}}]},"transactions":[{"amount":{"total":"2308","currency":"HUF","details":{"subtotal":"2308"}},"description":"Order 924d6ef7-74c1-43fc-bbbf-512180c5cb8c","item_list":{"shipping_address":{"recipient_name":"Joe Bloggs","line1":"House","line2":"Road","city":"London","state":"London","postal_code":"SW1A 1AA","country_code":"HU"}},"related_resources":[]}],"links":[{"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-4AH92705EN0735913LFF5Y3I","rel":"self","method":"GET"}]}
```

If I use the credit card number that is listed in my sandbox account dashboard, I get `status: "approved"` instead. I would like to know exactly what `status: "created"` means. The docs (https://developer.paypal.com/docs/api/payments/) are vague: 

> The transaction was successfully created.

If I received this status code in my production account, would it mean I had captured the customer's money and could ship them their goods? Or would I need to issue a second request, e.g. `execute?id=PAY-4AH92705EN0735913LFF5Y3I` or something? Under what circumstances do you get `created` vs `approved`?

Thanks!

**Comment by xiaoleih41** [comment]
Please use a random credit card number generator to generate a random credit card number for sandbox testing. You can find this online.  I tried your number `4242 4242 4242 4242`, I got **approved** status instead. This should be the only status if the `intent` is `sale` and the transaction is successful. There may have been some internal error that sent you the `created` status. This status should only be shown in a PayPal funded transaction.

**Comment by xiaoleih41** [comment]
Close this ticket as the issue should have been solved.
