### ISSUE TITLE
When does REST API webhook BILLING.SUBSCRIPTION.UPDATED occur?

### ISSUE THREAD

**Issue by greggy** [paypal/PayPal-REST-API-issues#99]
### General information

* Environment: Sandbox

### Issue description

When does REST API webhook BILLING.SUBSCRIPTION.UPDATED occur? Can I use it to update information until which day the user's account is active? And it'd be great to have docs with information when all webhooks occur!

**Comment by xiaoleih41** [comment]
@greggy The following are the description. So it will be triggered when the billing agreement is updated. 
````
BILLING.PLAN.CREATED: This event is triggered when a billing plan is created.
BILLING.PLAN.UPDATED: This event is triggered when a billing plan is updated.
BILLING.SUBSCRIPTION.CREATED: This event is triggered when a billing subscription is created.
BILLING.SUBSCRIPTION.UPDATED: This event is triggered when a billing subscription is updated.
BILLING.SUBSCRIPTION.SUSPENDED: This event is triggered when a billing subscription is suspended.
BILLING.SUBSCRIPTION.RE-ACTIVATED: This event is triggered when a billing subscription is reactivated.
BILLING.SUBSCRIPTION.CANCELLED: This event is triggered when a billing subscription is cancelled.
````

**Comment by greggy** [comment]
It means that if user change any agreement details or next period charges, I get this event?

**Comment by greggy** [comment]
Rephrase the question, which webhook can I use to get a moment when a charge payout?

**Comment by xiaoleih41** [comment]
You should be able to receive `PAYMENT.SALE.COMPLETED` webhooks.  Please refer to 
 https://github.com/paypal/PayPal-Python-SDK/issues/163

**Comment by greggy** [comment]
It's a good point, thank you! But I don't see that event in "Webhook
Events". What can it be? I tried to turn all events on or recreated
Webhook, without lucky.

2017-06-27 22:31 GMT+03:00 Xiaolei Wheelock <notifications@github.com>:

**Comment by pp-randy** [comment]
@greggy do you see the webhooks for the billing plan and the billing agreement creation?  I'm seeing those but not getting the `PAYMENT.SALE.COMPLETED` at this time, so following up further.  However, wanted to see if you are seeing the same.

**Comment by xiaoleih41** [comment]
@greggy This issue is being tracked at https://github.com/paypal/PayPal-REST-API-issues/issues/103. Please follow that issue going forward for future updates.
